/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedProvidersRouteImport } from './routes/_authed.providers'
import { Route as AuthedModelsRouteImport } from './routes/_authed.models'
import { Route as AuthedLogsRouteImport } from './routes/_authed.logs'
import { Route as AuthedFallbackGroupsRouteImport } from './routes/_authed.fallback-groups'
import { Route as AuthedDocsRouteImport } from './routes/_authed.docs'
import { Route as AuthedApiKeysRouteImport } from './routes/_authed.api-keys'
import { Route as AuthedProvidersIndexRouteImport } from './routes/_authed.providers.index'
import { Route as AuthedProvidersNameModelsRouteImport } from './routes/_authed.providers.$name.models'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProvidersRoute = AuthedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedModelsRoute = AuthedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogsRoute = AuthedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFallbackGroupsRoute = AuthedFallbackGroupsRouteImport.update({
  id: '/fallback-groups',
  path: '/fallback-groups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocsRoute = AuthedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApiKeysRoute = AuthedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProvidersIndexRoute = AuthedProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProvidersRoute,
} as any)
const AuthedProvidersNameModelsRoute =
  AuthedProvidersNameModelsRouteImport.update({
    id: '/$name/models',
    path: '/$name/models',
    getParentRoute: () => AuthedProvidersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/docs': typeof AuthedDocsRoute
  '/fallback-groups': typeof AuthedFallbackGroupsRoute
  '/logs': typeof AuthedLogsRoute
  '/models': typeof AuthedModelsRoute
  '/providers': typeof AuthedProvidersRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/providers/': typeof AuthedProvidersIndexRoute
  '/providers/$name/models': typeof AuthedProvidersNameModelsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/api-keys': typeof AuthedApiKeysRoute
  '/docs': typeof AuthedDocsRoute
  '/fallback-groups': typeof AuthedFallbackGroupsRoute
  '/logs': typeof AuthedLogsRoute
  '/models': typeof AuthedModelsRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/providers': typeof AuthedProvidersIndexRoute
  '/providers/$name/models': typeof AuthedProvidersNameModelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/_authed/api-keys': typeof AuthedApiKeysRoute
  '/_authed/docs': typeof AuthedDocsRoute
  '/_authed/fallback-groups': typeof AuthedFallbackGroupsRoute
  '/_authed/logs': typeof AuthedLogsRoute
  '/_authed/models': typeof AuthedModelsRoute
  '/_authed/providers': typeof AuthedProvidersRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/providers/': typeof AuthedProvidersIndexRoute
  '/_authed/providers/$name/models': typeof AuthedProvidersNameModelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboard'
    | '/register'
    | '/api-keys'
    | '/docs'
    | '/fallback-groups'
    | '/logs'
    | '/models'
    | '/providers'
    | '/settings'
    | '/providers/'
    | '/providers/$name/models'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboard'
    | '/register'
    | '/api-keys'
    | '/docs'
    | '/fallback-groups'
    | '/logs'
    | '/models'
    | '/settings'
    | '/'
    | '/providers'
    | '/providers/$name/models'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/onboard'
    | '/register'
    | '/_authed/api-keys'
    | '/_authed/docs'
    | '/_authed/fallback-groups'
    | '/_authed/logs'
    | '/_authed/models'
    | '/_authed/providers'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/providers/'
    | '/_authed/providers/$name/models'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/providers': {
      id: '/_authed/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthedProvidersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/models': {
      id: '/_authed/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthedModelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/logs': {
      id: '/_authed/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthedLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/fallback-groups': {
      id: '/_authed/fallback-groups'
      path: '/fallback-groups'
      fullPath: '/fallback-groups'
      preLoaderRoute: typeof AuthedFallbackGroupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/docs': {
      id: '/_authed/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthedDocsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/api-keys': {
      id: '/_authed/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthedApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/providers/': {
      id: '/_authed/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthedProvidersIndexRouteImport
      parentRoute: typeof AuthedProvidersRoute
    }
    '/_authed/providers/$name/models': {
      id: '/_authed/providers/$name/models'
      path: '/$name/models'
      fullPath: '/providers/$name/models'
      preLoaderRoute: typeof AuthedProvidersNameModelsRouteImport
      parentRoute: typeof AuthedProvidersRoute
    }
  }
}

interface AuthedProvidersRouteChildren {
  AuthedProvidersIndexRoute: typeof AuthedProvidersIndexRoute
  AuthedProvidersNameModelsRoute: typeof AuthedProvidersNameModelsRoute
}

const AuthedProvidersRouteChildren: AuthedProvidersRouteChildren = {
  AuthedProvidersIndexRoute: AuthedProvidersIndexRoute,
  AuthedProvidersNameModelsRoute: AuthedProvidersNameModelsRoute,
}

const AuthedProvidersRouteWithChildren = AuthedProvidersRoute._addFileChildren(
  AuthedProvidersRouteChildren,
)

interface AuthedRouteChildren {
  AuthedApiKeysRoute: typeof AuthedApiKeysRoute
  AuthedDocsRoute: typeof AuthedDocsRoute
  AuthedFallbackGroupsRoute: typeof AuthedFallbackGroupsRoute
  AuthedLogsRoute: typeof AuthedLogsRoute
  AuthedModelsRoute: typeof AuthedModelsRoute
  AuthedProvidersRoute: typeof AuthedProvidersRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApiKeysRoute: AuthedApiKeysRoute,
  AuthedDocsRoute: AuthedDocsRoute,
  AuthedFallbackGroupsRoute: AuthedFallbackGroupsRoute,
  AuthedLogsRoute: AuthedLogsRoute,
  AuthedModelsRoute: AuthedModelsRoute,
  AuthedProvidersRoute: AuthedProvidersRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
