import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "gpt-5.4-mini-2026-03-17",
    name: "gpt-5.4-mini-2026-03-17",
    provider: "302ai",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "chatgpt-4o-latest",
    name: "chatgpt-4o-latest",
    provider: "302ai",
    inputPricePer1M: 5,
    outputPricePer1M: 15,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4-nano-2026-03-17",
    name: "gpt-5.4-nano-2026-03-17",
    provider: "302ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.25,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kimi-k2-0905-preview",
    name: "kimi-k2-0905-preview",
    provider: "302ai",
    inputPricePer1M: 0.632,
    outputPricePer1M: 2.53,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4.20-beta-0309-non-reasoning",
    name: "grok-4.20-beta-0309-non-reasoning",
    provider: "302ai",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-nothink",
    name: "gemini-2.5-flash-nothink",
    provider: "302ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-plus",
    name: "Qwen-Plus",
    provider: "302ai",
    inputPricePer1M: 0.12,
    outputPricePer1M: 1.2,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.7",
    name: "glm-4.7",
    provider: "302ai",
    inputPricePer1M: 0.286,
    outputPricePer1M: 1.142,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    name: "qwen3-235b-a22b-instruct-2507",
    provider: "302ai",
    inputPricePer1M: 0.29,
    outputPricePer1M: 1.143,
    contextWindow: 128000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5v",
    name: "GLM-4.5V",
    provider: "302ai",
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.86,
    contextWindow: 64000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus-4-5",
    name: "claude-opus-4-5",
    provider: "302ai",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-pro",
    name: "gemini-2.5-pro",
    provider: "302ai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5",
    name: "gpt-5",
    provider: "302ai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "claude-haiku-4-5-20251001",
    provider: "302ai",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2-thinking-turbo",
    name: "kimi-k2-thinking-turbo",
    provider: "302ai",
    inputPricePer1M: 1.265,
    outputPricePer1M: 9.119,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-3-5-haiku-20241022",
    name: "claude-3-5-haiku-20241022",
    provider: "302ai",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5",
    name: "GLM-4.5",
    provider: "302ai",
    inputPricePer1M: 0.286,
    outputPricePer1M: 1.142,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5-pro",
    name: "gpt-5-pro",
    provider: "302ai",
    inputPricePer1M: 15,
    outputPricePer1M: 120,
    contextWindow: 400000,
    maxOutputTokens: 272000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4.20-beta-0309-reasoning",
    name: "grok-4.20-beta-0309-reasoning",
    provider: "302ai",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash",
    name: "gemini-2.5-flash",
    provider: "302ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4o",
    name: "gpt-4o",
    provider: "302ai",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "MiniMax-M2.1",
    name: "MiniMax-M2.1",
    provider: "302ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-lite-preview-09-2025",
    name: "gemini-2.5-flash-lite-preview-09-2025",
    provider: "302ai",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "doubao-seed-1-6-vision-250815",
    name: "doubao-seed-1-6-vision-250815",
    provider: "302ai",
    inputPricePer1M: 0.114,
    outputPricePer1M: 1.143,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-1-20250805",
    name: "claude-opus-4-1-20250805",
    provider: "302ai",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-max-2025-09-23",
    name: "qwen3-max-2025-09-23",
    provider: "302ai",
    inputPricePer1M: 0.86,
    outputPricePer1M: 3.43,
    contextWindow: 258048,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.7-flashx",
    name: "glm-4.7-flashx",
    provider: "302ai",
    inputPricePer1M: 0.0715,
    outputPricePer1M: 0.429,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5.1",
    name: "glm-5.1",
    provider: "302ai",
    inputPricePer1M: 0.86,
    outputPricePer1M: 3.5,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "glm-4.6",
    name: "glm-4.6",
    provider: "302ai",
    inputPricePer1M: 0.286,
    outputPricePer1M: 1.142,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-thinking",
    name: "kimi-k2-thinking",
    provider: "302ai",
    inputPricePer1M: 0.575,
    outputPricePer1M: 2.3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-5",
    name: "claude-sonnet-4-5",
    provider: "302ai",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5-x",
    name: "glm-4.5-x",
    provider: "302ai",
    inputPricePer1M: 1.143,
    outputPricePer1M: 2.29,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2-thinking",
    name: "DeepSeek-V3.2-Thinking",
    provider: "302ai",
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.43,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-6-thinking",
    name: "claude-sonnet-4-6-thinking",
    provider: "302ai",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-7",
    name: "claude-opus-4-7",
    provider: "302ai",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "grok-4-1-fast-non-reasoning",
    provider: "302ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4-nano",
    name: "gpt-5.4-nano",
    provider: "302ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.25,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-1-20250805-thinking",
    name: "claude-opus-4-1-20250805-thinking",
    provider: "302ai",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5-airx",
    name: "glm-4.5-airx",
    provider: "302ai",
    inputPricePer1M: 0.572,
    outputPricePer1M: 1.714,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4.1",
    name: "grok-4.1",
    provider: "302ai",
    inputPricePer1M: 2,
    outputPricePer1M: 10,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-preview-09-2025",
    name: "gemini-2.5-flash-preview-09-2025",
    provider: "302ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-5-20251101",
    name: "claude-opus-4-5-20251101",
    provider: "302ai",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-20250514",
    name: "claude-opus-4-20250514",
    provider: "302ai",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-3-pro-image-preview",
    name: "gemini-3-pro-image-preview",
    provider: "302ai",
    inputPricePer1M: 2,
    outputPricePer1M: 120,
    contextWindow: 32768,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-image",
    name: "gemini-2.5-flash-image",
    provider: "302ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 30,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-for-coding",
    name: "glm-for-coding",
    provider: "302ai",
    inputPricePer1M: 0.086,
    outputPricePer1M: 0.343,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.2",
    name: "gpt-5.2",
    provider: "302ai",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen-flash",
    name: "Qwen-Flash",
    provider: "302ai",
    inputPricePer1M: 0.022,
    outputPricePer1M: 0.22,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-6-thinking",
    name: "claude-opus-4-6-thinking",
    provider: "302ai",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-20250514",
    name: "claude-sonnet-4-20250514",
    provider: "302ai",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-chat-latest",
    name: "gpt-5.1-chat-latest",
    provider: "302ai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.2-chat-latest",
    name: "gpt-5.2-chat-latest",
    provider: "302ai",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-fast-reasoning",
    name: "grok-4-fast-reasoning",
    provider: "302ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4.1-nano",
    name: "gpt-4.1-nano",
    provider: "302ai",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-5-20250929-thinking",
    name: "claude-sonnet-4-5-20250929-thinking",
    provider: "302ai",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "MiniMax-M2.7-highspeed",
    name: "MiniMax-M2.7-highspeed",
    provider: "302ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 4.8,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "MiniMax-M2",
    name: "MiniMax-M2",
    provider: "302ai",
    inputPricePer1M: 0.33,
    outputPricePer1M: 1.32,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-3.1-flash-image-preview",
    name: "gemini-3.1-flash-image-preview",
    provider: "302ai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 60,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-235b-a22b",
    name: "Qwen3-235B-A22B",
    provider: "302ai",
    inputPricePer1M: 0.29,
    outputPricePer1M: 2.86,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "ministral-14b-2512",
    name: "ministral-14b-2512",
    provider: "302ai",
    inputPricePer1M: 0.33,
    outputPricePer1M: 0.33,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.6v",
    name: "GLM-4.6V",
    provider: "302ai",
    inputPricePer1M: 0.145,
    outputPricePer1M: 0.43,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-haiku-4-5",
    name: "claude-haiku-4-5",
    provider: "302ai",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4",
    name: "gpt-5.4",
    provider: "302ai",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "doubao-seed-1-6-thinking-250715",
    name: "doubao-seed-1-6-thinking-250715",
    provider: "302ai",
    inputPricePer1M: 0.121,
    outputPricePer1M: 1.21,
    contextWindow: 256000,
    maxOutputTokens: 16000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4-mini",
    name: "gpt-5.4-mini",
    provider: "302ai",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-4.1",
    name: "gpt-4.1",
    provider: "302ai",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "doubao-seed-code-preview-251028",
    name: "doubao-seed-code-preview-251028",
    provider: "302ai",
    inputPricePer1M: 0.17,
    outputPricePer1M: 1.14,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-6",
    name: "claude-opus-4-6",
    provider: "302ai",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "qwen3-coder-480b-a35b-instruct",
    provider: "302ai",
    inputPricePer1M: 0.86,
    outputPricePer1M: 3.43,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "claude-sonnet-4-5-20250929",
    provider: "302ai",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-reasoner",
    name: "Deepseek-Reasoner",
    provider: "302ai",
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.43,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-reasoning",
    name: "grok-4-1-fast-reasoning",
    provider: "302ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-3-pro-preview",
    name: "gemini-3-pro-preview",
    provider: "302ai",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-thinking",
    name: "gpt-5-thinking",
    provider: "302ai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-mini",
    name: "gpt-5-mini",
    provider: "302ai",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-4.1-mini",
    name: "gpt-4.1-mini",
    provider: "302ai",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "glm-5v-turbo",
    name: "GLM-5V-Turbo",
    provider: "302ai",
    inputPricePer1M: 0.72,
    outputPricePer1M: 3.2,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4-pro",
    name: "gpt-5.4-pro",
    provider: "302ai",
    inputPricePer1M: 30,
    outputPricePer1M: 180,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5-air",
    name: "glm-4.5-air",
    provider: "302ai",
    inputPricePer1M: 0.1143,
    outputPricePer1M: 0.286,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-6",
    name: "claude-sonnet-4-6",
    provider: "302ai",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-fast-non-reasoning",
    name: "grok-4-fast-non-reasoning",
    provider: "302ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-3-flash-preview",
    name: "gemini-3-flash-preview",
    provider: "302ai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-chat",
    name: "Deepseek-Chat",
    provider: "302ai",
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.43,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "MiniMax-M1",
    name: "MiniMax-M1",
    provider: "302ai",
    inputPricePer1M: 0.132,
    outputPricePer1M: 1.254,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4.20-multi-agent-beta-0309",
    name: "grok-4.20-multi-agent-beta-0309",
    provider: "302ai",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-5",
    name: "glm-5",
    provider: "302ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.6,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-max-latest",
    name: "Qwen-Max-Latest",
    provider: "302ai",
    inputPricePer1M: 0.343,
    outputPricePer1M: 1.372,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-large-2512",
    name: "mistral-large-2512",
    provider: "302ai",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3.3,
    contextWindow: 128000,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "MiniMax-M2.7",
    name: "MiniMax-M2.7",
    provider: "302ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-3-5-haiku-latest",
    name: "claude-3-5-haiku-latest",
    provider: "302ai",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-30b-a3b",
    name: "Qwen3-30B-A3B",
    provider: "302ai",
    inputPricePer1M: 0.11,
    outputPricePer1M: 1.08,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2",
    name: "deepseek-v3.2",
    provider: "302ai",
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.43,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "doubao-seed-1-8-251215",
    name: "doubao-seed-1-8-251215",
    provider: "302ai",
    inputPricePer1M: 0.114,
    outputPricePer1M: 0.286,
    contextWindow: 224000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-5-20251101-thinking",
    name: "claude-opus-4-5-20251101-thinking",
    provider: "302ai",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "gemini-2.0-flash-lite",
    provider: "302ai",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 2000000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-5-turbo",
    name: "glm-5-turbo",
    provider: "302ai",
    inputPricePer1M: 0.72,
    outputPricePer1M: 3.2,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1",
    name: "gpt-5.1",
    provider: "302ai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class Provider302aiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "302ai", apiKey, models: MODELS, apiBase: "https://api.302.ai/v1" });
  }
}
