import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "coding-minimax-m2.7",
    name: "Coding MiniMax M2.7",
    provider: "aihubmix",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 204800,
    maxOutputTokens: 128100,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "alicloud-glm-5.1",
    name: "GLM-5.1 (Alibaba Cloud)",
    provider: "aihubmix",
    inputPricePer1M: 0.84,
    outputPricePer1M: 3.38,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-6-think",
    name: "Claude Sonnet 4.6 Thinking",
    provider: "aihubmix",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "aihubmix",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "alicloud-deepseek-v4-flash",
    name: "DeepSeek V4 Flash (Alibaba Cloud)",
    provider: "aihubmix",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "xiaomi-mimo-v2.5-pro",
    name: "Xiaomi MiMo-V2.5-Pro",
    provider: "aihubmix",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3.3,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "doubao-seed-2-0-code-preview",
    name: "Doubao Seed 2.0 Code Preview",
    provider: "aihubmix",
    inputPricePer1M: 0.48,
    outputPricePer1M: 2.41,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "coding-xiaomi-mimo-v2.5-pro",
    name: "Coding Xiaomi MiMo-V2.5-Pro",
    provider: "aihubmix",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "doubao-seed-2-0-pro",
    name: "Doubao Seed 2.0 Pro",
    provider: "aihubmix",
    inputPricePer1M: 0.48,
    outputPricePer1M: 2.41,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deep-deepseek-v4-flash",
    name: "DeepSeek V4 Flash (DeepSeek)",
    provider: "aihubmix",
    inputPricePer1M: 0.154,
    outputPricePer1M: 0.308,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "aihubmix",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4.3",
    name: "Grok 4.3",
    provider: "aihubmix",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "aihubmix",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "xiaomi-mimo-v2.5-free",
    name: "Xiaomi MiMo-V2.5 (free)",
    provider: "aihubmix",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus-4-7-think",
    name: "Claude Opus 4.7 Thinking",
    provider: "aihubmix",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "coding-glm-5.1-free",
    name: "Coding GLM 5.1 (free)",
    provider: "aihubmix",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "xiaomi-mimo-v2.5-pro-free",
    name: "Xiaomi MiMo-V2.5-Pro (free)",
    provider: "aihubmix",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "xiaomi-mimo-v2.5",
    name: "Xiaomi MiMo-V2.5",
    provider: "aihubmix",
    inputPricePer1M: 0.44,
    outputPricePer1M: 2.2,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "aihubmix",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3.6-flash",
    name: "Qwen3.6 Flash",
    provider: "aihubmix",
    inputPricePer1M: 0.17,
    outputPricePer1M: 1.01,
    contextWindow: 991000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "coding-xiaomi-mimo-v2.5",
    name: "Coding Xiaomi MiMo-V2.5",
    provider: "aihubmix",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.4,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.1-codex",
    name: "GPT-5.1 Codex",
    provider: "aihubmix",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3.1-pro-preview-customtools",
    name: "Gemini 3.1 Pro Preview Custom Tools",
    provider: "aihubmix",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "doubao-seed-2-0-mini-260428",
    name: "Doubao Seed 2.0 Mini 260428",
    provider: "aihubmix",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.28,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "doubao-seed-2-0-lite-260428",
    name: "Doubao Seed 2.0 Lite 260428",
    provider: "aihubmix",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.51,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.2",
    name: "GPT-5.2",
    provider: "aihubmix",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "aihubmix",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-m2.7",
    name: "MiniMax M2.7",
    provider: "aihubmix",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-opus-4-6-think",
    name: "Claude Opus 4.6 Thinking",
    provider: "aihubmix",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex-mini",
    name: "GPT-5.1 Codex mini",
    provider: "aihubmix",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "aihubmix",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "coding-glm-5.1",
    name: "Coding GLM 5.1",
    provider: "aihubmix",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.22,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "coding-minimax-m2.7-free",
    name: "Coding MiniMax M2.7 (Free)",
    provider: "aihubmix",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 204800,
    maxOutputTokens: 128100,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    provider: "aihubmix",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 mini",
    provider: "aihubmix",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "aihubmix",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "aihubmix",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "aihubmix",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deep-deepseek-v4-pro",
    name: "DeepSeek V4 Pro (DeepSeek)",
    provider: "aihubmix",
    inputPricePer1M: 0.478,
    outputPricePer1M: 0.956,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5v-turbo",
    name: "GLM 5 Vision Turbo",
    provider: "aihubmix",
    inputPricePer1M: 0.7042,
    outputPricePer1M: 3.09848,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-glm-5.1",
    name: "GLM-5.1 (Z.ai)",
    provider: "aihubmix",
    inputPricePer1M: 0.845,
    outputPricePer1M: 3.38,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "aihubmix",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    provider: "aihubmix",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "coding-minimax-m2.7-highspeed",
    name: "Coding MiniMax M2.7 Highspeed",
    provider: "aihubmix",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 204800,
    maxOutputTokens: 128100,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.6-max-preview",
    name: "Qwen3.6 Max Preview",
    provider: "aihubmix",
    inputPricePer1M: 1.27,
    outputPricePer1M: 7.61,
    contextWindow: 240000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.2-codex",
    name: "GPT-5.2 Codex",
    provider: "aihubmix",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    provider: "aihubmix",
    inputPricePer1M: 0.28,
    outputPricePer1M: 1.69,
    contextWindow: 991000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "alicloud-deepseek-v4-pro",
    name: "DeepSeek V4 Pro (Alibaba Cloud)",
    provider: "aihubmix",
    inputPricePer1M: 1.69,
    outputPricePer1M: 3.38,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-5.1",
    name: "GPT-5.1",
    provider: "aihubmix",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    provider: "aihubmix",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class AihubmixAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "aihubmix", apiKey, models: MODELS });
  }
}
