import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "qwen2-5-math-72b-instruct",
    name: "Qwen2.5-Math 72B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 1.721,
    contextWindow: 4096,
    maxOutputTokens: 3072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-r1-0528",
    name: "DeepSeek R1 0528",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 2.294,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-omni-flash",
    name: "Qwen3-Omni Flash",
    provider: "alibaba-cn",
    inputPricePer1M: 0.058,
    outputPricePer1M: 0.23,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "alibaba-cn",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen-plus",
    name: "Qwen Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.115,
    outputPricePer1M: 0.287,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3-Coder 30B-A3B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.216,
    outputPricePer1M: 0.861,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen2-5-coder-7b-instruct",
    name: "Qwen2.5-Coder 7B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 0.287,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 1.147,
    contextWindow: 65536,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-omni-flash-realtime",
    name: "Qwen3-Omni Flash Realtime",
    provider: "alibaba-cn",
    inputPricePer1M: 0.23,
    outputPricePer1M: 0.918,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-r1-distill-llama-70b",
    name: "DeepSeek R1 Distill Llama 70B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.861,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 1.147,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-omni-turbo-realtime",
    name: "Qwen-Omni Turbo Realtime",
    provider: "alibaba-cn",
    inputPricePer1M: 0.23,
    outputPricePer1M: 0.918,
    contextWindow: 32768,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-math-7b-instruct",
    name: "Qwen2.5-Math 7B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 0.287,
    contextWindow: 4096,
    maxOutputTokens: 3072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-next-80b-a3b-instruct",
    name: "Qwen3-Next 80B-A3B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 0.574,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "alibaba-cn",
    inputPricePer1M: 2.5,
    outputPricePer1M: 7.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-long",
    name: "Qwen Long",
    provider: "alibaba-cn",
    inputPricePer1M: 0.072,
    outputPricePer1M: 0.287,
    contextWindow: 10000000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-math-turbo",
    name: "Qwen Math Turbo",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.861,
    contextWindow: 4096,
    maxOutputTokens: 3072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    provider: "alibaba-cn",
    inputPricePer1M: 0.861,
    outputPricePer1M: 3.441,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-omni-7b",
    name: "Qwen2.5-Omni 7B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.087,
    outputPricePer1M: 0.345,
    contextWindow: 32768,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-8b",
    name: "Qwen3 8B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.072,
    outputPricePer1M: 0.287,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen2-5-14b-instruct",
    name: "Qwen2.5 14B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 0.431,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    provider: "alibaba-cn",
    inputPricePer1M: 0.87,
    outputPricePer1M: 3.48,
    contextWindow: 202752,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "alibaba-cn",
    inputPricePer1M: 0.435,
    outputPricePer1M: 0.87,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-next-80b-a3b-thinking",
    name: "Qwen3-Next 80B-A3B (Thinking)",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 1.434,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qvq-max",
    name: "QVQ Max",
    provider: "alibaba-cn",
    inputPricePer1M: 1.147,
    outputPricePer1M: 4.588,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-plus-character",
    name: "Qwen Plus Character",
    provider: "alibaba-cn",
    inputPricePer1M: 0.115,
    outputPricePer1M: 0.287,
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2-thinking",
    name: "Moonshot Kimi K2 Thinking",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 2.294,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 2.294,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.5-flash",
    name: "Qwen3.5 Flash",
    provider: "alibaba-cn",
    inputPricePer1M: 0.172,
    outputPricePer1M: 1.72,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3.6-flash",
    name: "Qwen3.6 Flash",
    provider: "alibaba-cn",
    inputPricePer1M: 0.1875,
    outputPricePer1M: 1.125,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen2-5-vl-72b-instruct",
    name: "Qwen2.5-VL 72B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 2.294,
    outputPricePer1M: 6.881,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-plus",
    name: "Qwen3-VL Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.143353,
    outputPricePer1M: 1.433525,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-vl-ocr",
    name: "Qwen-VL OCR",
    provider: "alibaba-cn",
    inputPricePer1M: 0.717,
    outputPricePer1M: 0.717,
    contextWindow: 34096,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-mt-turbo",
    name: "Qwen-MT Turbo",
    provider: "alibaba-cn",
    inputPricePer1M: 0.101,
    outputPricePer1M: 0.28,
    contextWindow: 16384,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-math-plus",
    name: "Qwen Math Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 1.721,
    contextWindow: 4096,
    maxOutputTokens: 3072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-mt-plus",
    name: "Qwen-MT Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.259,
    outputPricePer1M: 0.775,
    contextWindow: 16384,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.5-plus",
    name: "Qwen3.5 Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.573,
    outputPricePer1M: 3.44,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-omni-turbo",
    name: "Qwen-Omni Turbo",
    provider: "alibaba-cn",
    inputPricePer1M: 0.058,
    outputPricePer1M: 0.23,
    contextWindow: 32768,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-72b-instruct",
    name: "Qwen2.5 72B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 1.721,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-r1-distill-qwen-7b",
    name: "DeepSeek R1 Distill Qwen 7B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.072,
    outputPricePer1M: 0.144,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3-1",
    name: "DeepSeek V3.1",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 1.721,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-coder-32b-instruct",
    name: "Qwen2.5-Coder 32B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.861,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-flash",
    name: "Qwen Flash",
    provider: "alibaba-cn",
    inputPricePer1M: 0.022,
    outputPricePer1M: 0.216,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3-2-exp",
    name: "DeepSeek V3.2 Exp",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.431,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "moonshot-kimi-k2-instruct",
    name: "Moonshot Kimi K2 Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 2.294,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-r1-distill-qwen-14b",
    name: "DeepSeek R1 Distill Qwen 14B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 0.431,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-vl-235b-a22b",
    name: "Qwen3-VL 235B-A22B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.286705,
    outputPricePer1M: 1.14682,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-deep-research",
    name: "Qwen Deep Research",
    provider: "alibaba-cn",
    inputPricePer1M: 7.742,
    outputPricePer1M: 23.367,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2.5",
    name: "Moonshot Kimi K2.5",
    provider: "alibaba-cn",
    inputPricePer1M: 0.574,
    outputPricePer1M: 2.411,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-30b-a3b",
    name: "Qwen3-VL 30B-A3B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.108,
    outputPricePer1M: 0.431,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-vl-max",
    name: "Qwen-VL Max",
    provider: "alibaba-cn",
    inputPricePer1M: 0.23,
    outputPricePer1M: 0.574,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-r1-distill-qwen-1-5b",
    name: "DeepSeek R1 Distill Qwen 1.5B",
    provider: "alibaba-cn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-max",
    name: "Qwen Max",
    provider: "alibaba-cn",
    inputPricePer1M: 0.345,
    outputPricePer1M: 1.377,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "alibaba-cn",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-235b-a22b",
    name: "Qwen3 235B-A22B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 1.147,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-r1-distill-llama-8b",
    name: "DeepSeek R1 Distill Llama 8B",
    provider: "alibaba-cn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2.6",
    name: "Moonshot Kimi K2.6",
    provider: "alibaba-cn",
    inputPricePer1M: 0.929,
    outputPricePer1M: 3.858,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "Qwen3-Coder 480B-A35B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.861,
    outputPricePer1M: 3.441,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwq-plus",
    name: "QwQ Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.23,
    outputPricePer1M: 0.574,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-32b-instruct",
    name: "Qwen2.5 32B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.861,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B-A17B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.43,
    outputPricePer1M: 2.58,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "tongyi-intent-detect-v3",
    name: "Tongyi Intent Detect V3",
    provider: "alibaba-cn",
    inputPricePer1M: 0.058,
    outputPricePer1M: 0.144,
    contextWindow: 8192,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 0.574,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-r1-distill-qwen-32b",
    name: "DeepSeek R1 Distill Qwen 32B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.861,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwq-32b",
    name: "QwQ 32B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.861,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-14b",
    name: "Qwen3 14B",
    provider: "alibaba-cn",
    inputPricePer1M: 0.144,
    outputPricePer1M: 0.574,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-asr-flash",
    name: "Qwen3-ASR Flash",
    provider: "alibaba-cn",
    inputPricePer1M: 0.032,
    outputPricePer1M: 0.032,
    contextWindow: 53248,
    maxOutputTokens: 4096,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-doc-turbo",
    name: "Qwen Doc Turbo",
    provider: "alibaba-cn",
    inputPricePer1M: 0.087,
    outputPricePer1M: 0.144,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "alibaba-cn",
    inputPricePer1M: 0.86,
    outputPricePer1M: 3.15,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    provider: "alibaba-cn",
    inputPricePer1M: 0.044,
    outputPricePer1M: 0.087,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-7b-instruct",
    name: "Qwen2.5 7B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.072,
    outputPricePer1M: 0.144,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen2-5-vl-7b-instruct",
    name: "Qwen2.5-VL 7B Instruct",
    provider: "alibaba-cn",
    inputPricePer1M: 0.287,
    outputPricePer1M: 0.717,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.6-max-preview",
    name: "Qwen3.6 Max Preview",
    provider: "alibaba-cn",
    inputPricePer1M: 1.32,
    outputPricePer1M: 7.9,
    contextWindow: 245800,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen-vl-plus",
    name: "Qwen-VL Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.115,
    outputPricePer1M: 0.287,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "MiniMax/MiniMax-M2.7",
    name: "MiniMax-M2.7",
    provider: "alibaba-cn",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi/kimi-k2.5",
    name: "kimi/kimi-k2.5",
    provider: "alibaba-cn",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "siliconflow/deepseek-r1-0528",
    name: "siliconflow/deepseek-r1-0528",
    provider: "alibaba-cn",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.18,
    contextWindow: 163840,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "siliconflow/deepseek-v3.1-terminus",
    name: "siliconflow/deepseek-v3.1-terminus",
    provider: "alibaba-cn",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "siliconflow/deepseek-v3-0324",
    name: "siliconflow/deepseek-v3-0324",
    provider: "alibaba-cn",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "siliconflow/deepseek-v3.2",
    name: "siliconflow/deepseek-v3.2",
    provider: "alibaba-cn",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.42,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    provider: "alibaba-cn",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class AlibabaCnAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "alibaba-cn",
      apiKey,
      models: MODELS,
      apiBase: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    });
  }
}
