import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "qwen3-omni-flash",
    name: "Qwen3-Omni Flash",
    provider: "alibaba",
    inputPricePer1M: 0.43,
    outputPricePer1M: 1.66,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    provider: "alibaba",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-plus",
    name: "Qwen Plus",
    provider: "alibaba",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.2,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3-Coder 30B-A3B Instruct",
    provider: "alibaba",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.25,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-omni-flash-realtime",
    name: "Qwen3-Omni Flash Realtime",
    provider: "alibaba",
    inputPricePer1M: 0.52,
    outputPricePer1M: 1.99,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    provider: "alibaba",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.8,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-omni-turbo-realtime",
    name: "Qwen-Omni Turbo Realtime",
    provider: "alibaba",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.07,
    contextWindow: 32768,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-plus-character-ja",
    name: "Qwen Plus Character (Japanese)",
    provider: "alibaba",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.4,
    contextWindow: 8192,
    maxOutputTokens: 512,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-next-80b-a3b-instruct",
    name: "Qwen3-Next 80B-A3B Instruct",
    provider: "alibaba",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    provider: "alibaba",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-35b-a3b",
    name: "Qwen3.6 35B-A3B",
    provider: "alibaba",
    inputPricePer1M: 0.248,
    outputPricePer1M: 1.485,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "alibaba",
    inputPricePer1M: 2.5,
    outputPricePer1M: 7.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    provider: "alibaba",
    inputPricePer1M: 1.2,
    outputPricePer1M: 6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-omni-7b",
    name: "Qwen2.5-Omni 7B",
    provider: "alibaba",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 32768,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-8b",
    name: "Qwen3 8B",
    provider: "alibaba",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.7,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen2-5-14b-instruct",
    name: "Qwen2.5 14B Instruct",
    provider: "alibaba",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.4,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-next-80b-a3b-thinking",
    name: "Qwen3-Next 80B-A3B (Thinking)",
    provider: "alibaba",
    inputPricePer1M: 0.5,
    outputPricePer1M: 6,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qvq-max",
    name: "QVQ Max",
    provider: "alibaba",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4.8,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-flash",
    name: "Qwen3.6 Flash",
    provider: "alibaba",
    inputPricePer1M: 0.1875,
    outputPricePer1M: 1.125,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen2-5-vl-72b-instruct",
    name: "Qwen2.5-VL 72B Instruct",
    provider: "alibaba",
    inputPricePer1M: 2.8,
    outputPricePer1M: 8.4,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-plus",
    name: "Qwen3-VL Plus",
    provider: "alibaba",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.6,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-vl-ocr",
    name: "Qwen-VL OCR",
    provider: "alibaba",
    inputPricePer1M: 0.72,
    outputPricePer1M: 0.72,
    contextWindow: 34096,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-mt-turbo",
    name: "Qwen-MT Turbo",
    provider: "alibaba",
    inputPricePer1M: 0.16,
    outputPricePer1M: 0.49,
    contextWindow: 16384,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-mt-plus",
    name: "Qwen-MT Plus",
    provider: "alibaba",
    inputPricePer1M: 2.46,
    outputPricePer1M: 7.37,
    contextWindow: 16384,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.5-plus",
    name: "Qwen3.5 Plus",
    provider: "alibaba",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2.4,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-omni-turbo",
    name: "Qwen-Omni Turbo",
    provider: "alibaba",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.27,
    contextWindow: 32768,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-72b-instruct",
    name: "Qwen2.5 72B Instruct",
    provider: "alibaba",
    inputPricePer1M: 1.4,
    outputPricePer1M: 5.6,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-flash",
    name: "Qwen Flash",
    provider: "alibaba",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.4,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-vl-235b-a22b",
    name: "Qwen3-VL 235B-A22B",
    provider: "alibaba",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.8,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-30b-a3b",
    name: "Qwen3-VL 30B-A3B",
    provider: "alibaba",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-vl-max",
    name: "Qwen-VL Max",
    provider: "alibaba",
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.2,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.5-27b",
    name: "Qwen3.5 27B",
    provider: "alibaba",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.4,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen-max",
    name: "Qwen Max",
    provider: "alibaba",
    inputPricePer1M: 1.6,
    outputPricePer1M: 6.4,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-235b-a22b",
    name: "Qwen3 235B-A22B",
    provider: "alibaba",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.8,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-livetranslate-flash-realtime",
    name: "Qwen3-LiveTranslate Flash Realtime",
    provider: "alibaba",
    inputPricePer1M: 10,
    outputPricePer1M: 10,
    contextWindow: 53248,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-27b",
    name: "Qwen3.6 27B",
    provider: "alibaba",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.5-35b-a3b",
    name: "Qwen3.5 35B-A3B",
    provider: "alibaba",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "Qwen3-Coder 480B-A35B Instruct",
    provider: "alibaba",
    inputPricePer1M: 1.5,
    outputPricePer1M: 7.5,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwq-plus",
    name: "QwQ Plus",
    provider: "alibaba",
    inputPricePer1M: 0.8,
    outputPricePer1M: 2.4,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-32b-instruct",
    name: "Qwen2.5 32B Instruct",
    provider: "alibaba",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.8,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B-A17B",
    provider: "alibaba",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    provider: "alibaba",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-14b",
    name: "Qwen3 14B",
    provider: "alibaba",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.4,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-asr-flash",
    name: "Qwen3-ASR Flash",
    provider: "alibaba",
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.035,
    contextWindow: 53248,
    maxOutputTokens: 4096,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    provider: "alibaba",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.2,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2-5-7b-instruct",
    name: "Qwen2.5 7B Instruct",
    provider: "alibaba",
    inputPricePer1M: 0.175,
    outputPricePer1M: 0.7,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen2-5-vl-7b-instruct",
    name: "Qwen2.5-VL 7B Instruct",
    provider: "alibaba",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.05,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.6-max-preview",
    name: "Qwen3.6 Max Preview",
    provider: "alibaba",
    inputPricePer1M: 1.3,
    outputPricePer1M: 7.8,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.5-122b-a10b",
    name: "Qwen3.5 122B-A10B",
    provider: "alibaba",
    inputPricePer1M: 0.4,
    outputPricePer1M: 3.2,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen-vl-plus",
    name: "Qwen-VL Plus",
    provider: "alibaba",
    inputPricePer1M: 0.21,
    outputPricePer1M: 0.63,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    provider: "alibaba",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class AlibabaAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "alibaba",
      apiKey,
      models: MODELS,
      apiBase: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    });
  }
}
