import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.7",
    name: "GLM-4.7",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 2.5,
    outputPricePer1M: 7.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-flash",
    name: "Qwen3.6 Flash",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0.1875,
    outputPricePer1M: 1.125,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-max-2026-01-23",
    name: "Qwen3 Max",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.5-plus",
    name: "Qwen3.5 Plus",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 196608,
    maxOutputTokens: 24576,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-coder-next",
    name: "Qwen3 Coder Next",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    provider: "alibaba-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class AlibabaCodingPlanAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "alibaba-coding-plan",
      apiKey,
      models: MODELS,
      apiBase: "https://coding-intl.dashscope.aliyuncs.com/v1",
    });
  }
}
