import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "global.anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "us.meta.llama4-scout-17b-instruct-v1:0",
    name: "Llama 4 Scout 17B Instruct (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.66,
    contextWindow: 3500000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax.minimax-m2",
    name: "MiniMax M2",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204608,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "anthropic.claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "eu.anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3.3,
    outputPricePer1M: 16.5,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mistral.voxtral-small-24b-2507",
    name: "Voxtral Small 24B 2507",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.35,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistral.ministral-3-3b-instruct",
    name: "Ministral 3 3B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai.gpt-oss-20b",
    name: "gpt-oss-20b",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai.gpt-oss-safeguard-20b",
    name: "GPT OSS Safeguard 20B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "global.anthropic.claude-fable-5",
    name: "Claude Fable 5 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 10,
    outputPricePer1M: 50,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai.gpt-oss-120b-1:0",
    name: "gpt-oss-120b",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "amazon.nova-pro-v1:0",
    name: "Nova Pro",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.2,
    contextWindow: 300000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen.qwen3-coder-next",
    name: "Qwen3 Coder Next",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.22,
    outputPricePer1M: 1.8,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "us.anthropic.claude-opus-4-7",
    name: "Claude Opus 4.7 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "nvidia.nemotron-nano-9b-v2",
    name: "NVIDIA Nemotron Nano 9B v2",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.23,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen.qwen3-32b-v1:0",
    name: "Qwen3 32B (dense)",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "jp.anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (JP)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek.r1-v1:0",
    name: "DeepSeek-R1",
    provider: "amazon-bedrock",
    inputPricePer1M: 1.35,
    outputPricePer1M: 5.4,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral.mistral-large-3-675b-instruct",
    name: "Mistral Large 3",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google.gemma-3-27b-it",
    name: "Google Gemma 3 27B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.2,
    contextWindow: 202752,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "amazon.nova-2-lite-v1:0",
    name: "Nova 2 Lite",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.33,
    outputPricePer1M: 2.75,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai.gpt-oss-safeguard-120b",
    name: "GPT OSS Safeguard 120B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mistral.ministral-3-8b-instruct",
    name: "Ministral 3 8B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.15,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "eu.anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5.5,
    outputPricePer1M: 27.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "au.anthropic.claude-opus-4-6-v1",
    name: "AU Anthropic Claude Opus 4.6",
    provider: "amazon-bedrock",
    inputPricePer1M: 16.5,
    outputPricePer1M: 82.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai.gpt-oss-120b",
    name: "gpt-oss-120b",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "global.anthropic.claude-opus-4-8",
    name: "Claude Opus 4.8 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "us.meta.llama4-maverick-17b-instruct-v1:0",
    name: "Llama 4 Maverick 17B Instruct (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.97,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai.gpt-5.4",
    name: "GPT-5.4",
    provider: "amazon-bedrock",
    inputPricePer1M: 2.75,
    outputPricePer1M: 16.5,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mistral.devstral-2-123b",
    name: "Devstral 2 123B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai.glm-4.7",
    name: "GLM-4.7",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "writer.palmyra-x4-v1:0",
    name: "Palmyra X4",
    provider: "amazon-bedrock",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 122880,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral.magistral-small-2509",
    name: "Magistral Small 1.2",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 128000,
    maxOutputTokens: 40000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen.qwen3-coder-480b-a35b-v1:0",
    name: "Qwen3 Coder 480B A35B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.22,
    outputPricePer1M: 1.8,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "amazon.nova-micro-v1:0",
    name: "Nova Micro",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.14,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral.pixtral-large-2502-v1:0",
    name: "Pixtral Large (25.02)",
    provider: "amazon-bedrock",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "us.anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "jp.anthropic.claude-opus-4-7",
    name: "Claude Opus 4.7 (JP)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "au.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (AU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek.v3-v1:0",
    name: "DeepSeek-V3.1",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.58,
    outputPricePer1M: 1.68,
    contextWindow: 163840,
    maxOutputTokens: 81920,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "anthropic.claude-opus-4-1-20250805-v1:0",
    name: "Claude Opus 4.1",
    provider: "amazon-bedrock",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "jp.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (JP)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google.gemma-3-4b-it",
    name: "Gemma 3 4B IT",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.08,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3.3,
    outputPricePer1M: 16.5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen.qwen3-vl-235b-a22b",
    name: "Qwen/Qwen3-VL-235B-A22B-Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.5,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "writer.palmyra-x5-v1:0",
    name: "Palmyra X5",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.6,
    outputPricePer1M: 6,
    contextWindow: 1040000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "us.anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "au.anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5 (AU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "meta.llama3-3-70b-instruct-v1:0",
    name: "Llama 3.3 70B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.72,
    outputPricePer1M: 0.72,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai.glm-5",
    name: "GLM-5",
    provider: "amazon-bedrock",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202752,
    maxOutputTokens: 101376,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "us.anthropic.claude-opus-4-8",
    name: "Claude Opus 4.8 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "global.anthropic.claude-opus-4-7",
    name: "Claude Opus 4.7 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "us.anthropic.claude-fable-5",
    name: "Claude Fable 5 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 10,
    outputPricePer1M: 50,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "amazon.nova-lite-v1:0",
    name: "Nova Lite",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    contextWindow: 300000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "us.anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mistral.voxtral-mini-3b-2507",
    name: "Voxtral Mini 3B 2507",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.04,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["audio", "text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "moonshot.kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262143,
    maxOutputTokens: 16000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "meta.llama3-1-70b-instruct-v1:0",
    name: "Llama 3.1 70B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.72,
    outputPricePer1M: 0.72,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "us.deepseek.r1-v1:0",
    name: "DeepSeek-R1 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 1.35,
    outputPricePer1M: 5.4,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "global.anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5",
    provider: "amazon-bedrock",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "moonshotai.kimi-k2.5",
    name: "Kimi K2.5",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262143,
    maxOutputTokens: 16000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "au.anthropic.claude-opus-4-8",
    name: "Claude Opus 4.8 (AU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "nvidia.nemotron-nano-12b-v2",
    name: "NVIDIA Nemotron Nano 12B v2 VL BF16",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai.glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "meta.llama4-scout-17b-instruct-v1:0",
    name: "Llama 4 Scout 17B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.66,
    contextWindow: 3500000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen.qwen3-235b-a22b-2507-v1:0",
    name: "Qwen3 235B A22B 2507",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.88,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "eu.anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai.gpt-oss-20b-1:0",
    name: "gpt-oss-20b",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "jp.anthropic.claude-opus-4-8",
    name: "Claude Opus 4.8 (JP)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic.claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen.qwen3-coder-30b-a3b-v1:0",
    name: "Qwen3 Coder 30B A3B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen.qwen3-next-80b-a3b",
    name: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.14,
    outputPricePer1M: 1.4,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai.gpt-5.5",
    name: "GPT-5.5",
    provider: "amazon-bedrock",
    inputPricePer1M: 5.5,
    outputPricePer1M: 33,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "au.anthropic.claude-sonnet-4-6",
    name: "AU Anthropic Claude Sonnet 4.6",
    provider: "amazon-bedrock",
    inputPricePer1M: 3.3,
    outputPricePer1M: 16.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "us.anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax.minimax-m2.5",
    name: "MiniMax M2.5",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 196608,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "eu.anthropic.claude-opus-4-8",
    name: "Claude Opus 4.8 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5.5,
    outputPricePer1M: 27.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "eu.anthropic.claude-opus-4-7",
    name: "Claude Opus 4.7 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5.5,
    outputPricePer1M: 27.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "meta.llama3-1-8b-instruct-v1:0",
    name: "Llama 3.1 8B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.22,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "us.anthropic.claude-opus-4-1-20250805-v1:0",
    name: "Claude Opus 4.1 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "meta.llama4-maverick-17b-instruct-v1:0",
    name: "Llama 4 Maverick 17B Instruct",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.97,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "global.anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "nvidia.nemotron-super-3-120b",
    name: "NVIDIA Nemotron 3 Super 120B A12B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.65,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia.nemotron-nano-3-30b",
    name: "NVIDIA Nemotron Nano 3 30B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "eu.anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "global.anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6 (Global)",
    provider: "amazon-bedrock",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (US)",
    provider: "amazon-bedrock",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google.gemma-3-12b-it",
    name: "Google Gemma 3 12B",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.049999999999999996,
    outputPricePer1M: 0.09999999999999999,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax.minimax-m2.1",
    name: "MiniMax M2.1",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "eu.anthropic.claude-fable-5",
    name: "Claude Fable 5 (EU)",
    provider: "amazon-bedrock",
    inputPricePer1M: 11,
    outputPricePer1M: 55,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek.v3.2",
    name: "DeepSeek-V3.2",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.62,
    outputPricePer1M: 1.85,
    contextWindow: 163840,
    maxOutputTokens: 81920,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistral.ministral-3-14b-instruct",
    name: "Ministral 14B 3.0",
    provider: "amazon-bedrock",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class AmazonBedrockAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "amazon-bedrock", apiKey, models: MODELS });
  }
}
