import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "codex-mini",
    name: "Codex Mini",
    provider: "azure",
    inputPricePer1M: 1.5,
    outputPricePer1M: 6,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "phi-3.5-moe-instruct",
    name: "Phi-3.5-MoE-instruct",
    provider: "azure",
    inputPricePer1M: 0.16,
    outputPricePer1M: 0.64,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-3.5-turbo-instruct",
    name: "GPT-3.5 Turbo Instruct",
    provider: "azure",
    inputPricePer1M: 1.5,
    outputPricePer1M: 2,
    contextWindow: 4096,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-r1-0528",
    name: "DeepSeek-R1-0528",
    provider: "azure",
    inputPricePer1M: 1.35,
    outputPricePer1M: 5.4,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek-V4-Flash",
    provider: "azure",
    inputPricePer1M: 0.19,
    outputPricePer1M: 0.51,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-5.2-chat",
    name: "GPT-5.2 Chat",
    provider: "azure",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "o3",
    name: "o3",
    provider: "azure",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3-0324",
    name: "DeepSeek-V3-0324",
    provider: "azure",
    inputPricePer1M: 1.14,
    outputPricePer1M: 4.56,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "phi-3-small-128k-instruct",
    name: "Phi-3-small-instruct (128k)",
    provider: "azure",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama-3-8b-instruct",
    name: "Meta-Llama-3-8B-Instruct",
    provider: "azure",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.61,
    contextWindow: 8192,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-small-2503",
    name: "Mistral Small 3.1",
    provider: "azure",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "text-embedding-3-large",
    name: "text-embedding-3-large",
    provider: "azure",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0,
    contextWindow: 8191,
    maxOutputTokens: 3072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o1-mini",
    name: "o1-mini",
    provider: "azure",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 128000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "phi-3.5-mini-instruct",
    name: "Phi-3.5-mini-instruct",
    provider: "azure",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.52,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-nemo",
    name: "Mistral Nemo",
    provider: "azure",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.15,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "cohere-embed-v-4-0",
    name: "Embed v4",
    provider: "azure",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 1536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    provider: "azure",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "azure",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-chat",
    name: "GPT-5 Chat",
    provider: "azure",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cohere-command-a",
    name: "Command A",
    provider: "azure",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 256000,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.2-11b-vision-instruct",
    name: "Llama-3.2-11B-Vision-Instruct",
    provider: "azure",
    inputPricePer1M: 0.37,
    outputPricePer1M: 0.37,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5-pro",
    name: "GPT-5 Pro",
    provider: "azure",
    inputPricePer1M: 15,
    outputPricePer1M: 120,
    contextWindow: 400000,
    maxOutputTokens: 272000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "cohere-command-r-08-2024",
    name: "Command R",
    provider: "azure",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "azure",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4",
    name: "GPT-4",
    provider: "azure",
    inputPricePer1M: 60,
    outputPricePer1M: 120,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    provider: "azure",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "phi-3-medium-128k-instruct",
    name: "Phi-3-medium-instruct (128k)",
    provider: "azure",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.68,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-4-32k",
    name: "GPT-4 32K",
    provider: "azure",
    inputPricePer1M: 60,
    outputPricePer1M: 120,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "meta-llama-3.1-405b-instruct",
    name: "Meta-Llama-3.1-405B-Instruct",
    provider: "azure",
    inputPricePer1M: 5.33,
    outputPricePer1M: 16,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "cohere-command-r-plus-08-2024",
    name: "Command R+",
    provider: "azure",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "phi-4-mini",
    name: "Phi-4-mini",
    provider: "azure",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-3.5-turbo-1106",
    name: "GPT-3.5 Turbo 1106",
    provider: "azure",
    inputPricePer1M: 1,
    outputPricePer1M: 2,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout 17B 16E Instruct",
    provider: "azure",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.78,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama-3.3-70B-Instruct",
    provider: "azure",
    inputPricePer1M: 0.71,
    outputPricePer1M: 0.71,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "grok-4-20-non-reasoning",
    name: "Grok 4.20 (Non-Reasoning)",
    provider: "azure",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 262000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-chat",
    name: "GPT-5.1 Chat",
    provider: "azure",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text", "image", "audio"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek-V4-Pro",
    provider: "azure",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "azure",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "azure",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1",
    provider: "azure",
    inputPricePer1M: 1.35,
    outputPricePer1M: 5.4,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "Grok 4.1 Fast (Non-Reasoning)",
    provider: "azure",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    provider: "azure",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.25,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "phi-3-small-8k-instruct",
    name: "Phi-3-small-instruct (8k)",
    provider: "azure",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 8192,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.3-chat",
    name: "GPT-5.3 Chat",
    provider: "azure",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-3.5-turbo-0125",
    name: "GPT-3.5 Turbo 0125",
    provider: "azure",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cohere-embed-v3-multilingual",
    name: "Embed v3 Multilingual",
    provider: "azure",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0,
    contextWindow: 512,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-3.5-turbo-0613",
    name: "GPT-3.5 Turbo 0613",
    provider: "azure",
    inputPricePer1M: 3,
    outputPricePer1M: 4,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex",
    name: "GPT-5.1 Codex",
    provider: "azure",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text", "image", "audio"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex-max",
    name: "GPT-5.1 Codex Max",
    provider: "azure",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "phi-4-reasoning",
    name: "Phi-4-reasoning",
    provider: "azure",
    inputPricePer1M: 0.125,
    outputPricePer1M: 0.5,
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-medium-2505",
    name: "Mistral Medium 3",
    provider: "azure",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "meta-llama-3.1-70b-instruct",
    name: "Meta-Llama-3.1-70B-Instruct",
    provider: "azure",
    inputPricePer1M: 2.68,
    outputPricePer1M: 3.54,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "text-embedding-ada-002",
    name: "text-embedding-ada-002",
    provider: "azure",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 1536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o3-mini",
    name: "o3-mini",
    provider: "azure",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.2",
    name: "GPT-5.2",
    provider: "azure",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-4-turbo-vision",
    name: "GPT-4 Turbo Vision",
    provider: "azure",
    inputPricePer1M: 10,
    outputPricePer1M: 30,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-large-2411",
    name: "Mistral Large 24.11",
    provider: "azure",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "azure",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "text-embedding-3-small",
    name: "text-embedding-3-small",
    provider: "azure",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0,
    contextWindow: 8191,
    maxOutputTokens: 1536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2-speciale",
    name: "DeepSeek-V3.2-Speciale",
    provider: "azure",
    inputPricePer1M: 0.58,
    outputPricePer1M: 1.68,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-3.5-turbo-0301",
    name: "GPT-3.5 Turbo 0301",
    provider: "azure",
    inputPricePer1M: 1.5,
    outputPricePer1M: 2,
    contextWindow: 4096,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "meta-llama-3.1-8b-instruct",
    name: "Meta-Llama-3.1-8B-Instruct",
    provider: "azure",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.61,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus-4-1",
    name: "Claude Opus 4.1",
    provider: "azure",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex-mini",
    name: "GPT-5.1 Codex Mini",
    provider: "azure",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "azure",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "phi-4",
    name: "Phi-4",
    provider: "azure",
    inputPricePer1M: 0.125,
    outputPricePer1M: 0.5,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "grok-4-fast-reasoning",
    name: "Grok 4 Fast (Reasoning)",
    provider: "azure",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-image-1.5",
    name: "GPT-Image-1.5",
    provider: "azure",
    inputPricePer1M: 5,
    outputPricePer1M: 32,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 nano",
    provider: "azure",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    provider: "azure",
    inputPricePer1M: 10,
    outputPricePer1M: 50,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o1",
    name: "o1",
    provider: "azure",
    inputPricePer1M: 15,
    outputPricePer1M: 60,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.1",
    name: "DeepSeek-V3.1",
    provider: "azure",
    inputPricePer1M: 0.56,
    outputPricePer1M: 1.68,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.2-90b-vision-instruct",
    name: "Llama-3.2-90B-Vision-Instruct",
    provider: "azure",
    inputPricePer1M: 2.04,
    outputPricePer1M: 2.04,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "azure",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "ministral-3b",
    name: "Ministral 3B",
    provider: "azure",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.04,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    provider: "azure",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    provider: "azure",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "azure",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "azure",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "azure",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-reasoning",
    name: "Grok 4.1 Fast (Reasoning)",
    provider: "azure",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "azure",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-image-1",
    name: "GPT-Image-1",
    provider: "azure",
    inputPricePer1M: 5,
    outputPricePer1M: 40,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 mini",
    provider: "azure",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "azure",
    inputPricePer1M: 10,
    outputPricePer1M: 30,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano",
    provider: "azure",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.4,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "phi-3-medium-4k-instruct",
    name: "Phi-3-medium-instruct (4k)",
    provider: "azure",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.68,
    contextWindow: 4096,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.4-pro",
    name: "GPT-5.4 Pro",
    provider: "azure",
    inputPricePer1M: 30,
    outputPricePer1M: 180,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cohere-embed-v3-english",
    name: "Embed v3 English",
    provider: "azure",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0,
    contextWindow: 512,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "azure",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "codestral-2501",
    name: "Codestral 25.01",
    provider: "azure",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "phi-4-reasoning-plus",
    name: "Phi-4-reasoning-plus",
    provider: "azure",
    inputPricePer1M: 0.125,
    outputPricePer1M: 0.5,
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "phi-4-multimodal",
    name: "Phi-4-multimodal",
    provider: "azure",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.32,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    provider: "azure",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "model-router",
    name: "Model Router",
    provider: "azure",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-20-reasoning",
    name: "Grok 4.20 (Reasoning)",
    provider: "azure",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 262000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-codex",
    name: "GPT-5-Codex",
    provider: "azure",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek-V3.2",
    provider: "azure",
    inputPricePer1M: 0.58,
    outputPricePer1M: 1.68,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-4-maverick-17b-128e-instruct-fp8",
    name: "Llama 4 Maverick 17B 128E Instruct FP8",
    provider: "azure",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.2-codex",
    name: "GPT-5.2 Codex",
    provider: "azure",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "phi-4-mini-reasoning",
    name: "Phi-4-mini-reasoning",
    provider: "azure",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "phi-3-mini-128k-instruct",
    name: "Phi-3-mini-instruct (128k)",
    provider: "azure",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.52,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-image-2",
    name: "GPT-Image-2",
    provider: "azure",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "phi-3-mini-4k-instruct",
    name: "Phi-3-mini-instruct (4k)",
    provider: "azure",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.52,
    contextWindow: 4096,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama-3-70b-instruct",
    name: "Meta-Llama-3-70B-Instruct",
    provider: "azure",
    inputPricePer1M: 2.68,
    outputPricePer1M: 3.54,
    contextWindow: 8192,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.1",
    name: "GPT-5.1",
    provider: "azure",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text", "image", "audio"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    provider: "azure",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class AzureAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "azure", apiKey, models: MODELS });
  }
}
