import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "baseten",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    provider: "baseten",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.7-Code",
    name: "Kimi K2.7 Code",
    provider: "baseten",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "OpenAI GPT 120B",
    provider: "baseten",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.5,
    contextWindow: 128072,
    maxOutputTokens: 128072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia/Nemotron-120B-A12B",
    name: "Nemotron Super",
    provider: "baseten",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.75,
    contextWindow: 202800,
    maxOutputTokens: 202800,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
    name: "Nemotron Ultra",
    provider: "baseten",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 202800,
    maxOutputTokens: 202800,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM 5",
    provider: "baseten",
    inputPricePer1M: 0.95,
    outputPricePer1M: 3.15,
    contextWindow: 202800,
    maxOutputTokens: 202800,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7",
    name: "GLM 4.7",
    provider: "baseten",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 200000,
    maxOutputTokens: 200000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.2",
    name: "GLM 5.2",
    provider: "baseten",
    inputPricePer1M: 1.5,
    outputPricePer1M: 4.5,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1",
    name: "GLM 5.1",
    provider: "baseten",
    inputPricePer1M: 1.3,
    outputPricePer1M: 4.3,
    contextWindow: 202800,
    maxOutputTokens: 202800,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.1",
    name: "DeepSeek V3.1",
    provider: "baseten",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 164000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Pro",
    name: "Deepseek V4 Pro",
    provider: "baseten",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "baseten",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204000,
    maxOutputTokens: 204000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class BasetenAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "baseten", apiKey, models: MODELS, apiBase: "https://inference.baseten.co/v1" });
  }
}
