import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B Instruct",
    provider: "berget",
    inputPricePer1M: 0.99,
    outputPricePer1M: 0.99,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "berget",
    inputPricePer1M: 0.83,
    outputPricePer1M: 3.85,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-4-31B-it",
    name: "Gemma 4 31B Instruct",
    provider: "berget",
    inputPricePer1M: 0.275,
    outputPricePer1M: 0.55,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["audio", "image", "text", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS-120B",
    provider: "berget",
    inputPricePer1M: 0.44,
    outputPricePer1M: 0.99,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistralai/Mistral-Medium-3.5-128B",
    name: "Mistral Medium 3.5 128B",
    provider: "berget",
    inputPricePer1M: 1.65,
    outputPricePer1M: 5.5,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["image", "text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
    name: "Mistral Small 3.2 24B Instruct 2506",
    provider: "berget",
    inputPricePer1M: 0.33,
    outputPricePer1M: 0.33,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7",
    name: "GLM 4.7",
    provider: "berget",
    inputPricePer1M: 0.77,
    outputPricePer1M: 2.75,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class BergetAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "berget", apiKey, models: MODELS, apiBase: "https://api.berget.ai/v1" });
  }
}
