import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/Kimi-K2.6-TEE",
    name: "Kimi K2.6 TEE",
    provider: "chutes",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5-TEE",
    name: "Kimi K2.5 TEE",
    provider: "chutes",
    inputPricePer1M: 0.44,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-4-31B-turbo-TEE",
    name: "gemma 4 31B turbo TEE",
    provider: "chutes",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.38,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-32B-TEE",
    name: "Qwen3 32B TEE",
    provider: "chutes",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.24,
    contextWindow: 40960,
    maxOutputTokens: 40960,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen2.5-VL-32B-Instruct",
    name: "Qwen2.5 VL 32B Instruct",
    provider: "chutes",
    inputPricePer1M: 0.0543,
    outputPricePer1M: 0.2174,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    name: "Qwen3 Next 80B A3B Instruct",
    provider: "chutes",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Instruct-2507-TEE",
    name: "Qwen3 235B A22B Instruct 2507 TEE",
    provider: "chutes",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen3 235B A22B Thinking 2507",
    provider: "chutes",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.6-27B-TEE",
    name: "Qwen3.6 27B TEE",
    provider: "chutes",
    inputPricePer1M: 0.195,
    outputPricePer1M: 1.56,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3Guard-Gen-0.6B",
    name: "Qwen3Guard Gen 0.6B",
    provider: "chutes",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.0109,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-Next-TEE",
    name: "Qwen3 Coder Next TEE",
    provider: "chutes",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.75,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen2.5-Coder-32B-Instruct",
    name: "Qwen2.5 Coder 32B Instruct",
    provider: "chutes",
    inputPricePer1M: 0.0272,
    outputPricePer1M: 0.1087,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen2.5-72B-Instruct",
    name: "Qwen2.5 72B Instruct",
    provider: "chutes",
    inputPricePer1M: 0.2989,
    outputPricePer1M: 1.1957,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B-TEE",
    name: "Qwen3.5 397B A17B TEE",
    provider: "chutes",
    inputPricePer1M: 0.39,
    outputPricePer1M: 2.34,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-30B-A3B",
    name: "Qwen3 30B A3B",
    provider: "chutes",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.22,
    contextWindow: 40960,
    maxOutputTokens: 40960,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b-TEE",
    name: "gpt oss 120b TEE",
    provider: "chutes",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.36,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "XiaomiMiMo/MiMo-V2-Flash-TEE",
    name: "MiMo V2 Flash TEE",
    provider: "chutes",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.29,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "NousResearch/Hermes-4-14B",
    name: "Hermes 4 14B",
    provider: "chutes",
    inputPricePer1M: 0.0136,
    outputPricePer1M: 0.0543,
    contextWindow: 40960,
    maxOutputTokens: 40960,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "NousResearch/DeepHermes-3-Mistral-24B-Preview",
    name: "DeepHermes 3 Mistral 24B Preview",
    provider: "chutes",
    inputPricePer1M: 0.0245,
    outputPricePer1M: 0.0978,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "unsloth/Llama-3.2-1B-Instruct",
    name: "Llama 3.2 1B Instruct",
    provider: "chutes",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.0109,
    contextWindow: 16384,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "unsloth/gemma-3-12b-it",
    name: "gemma 3 12b it",
    provider: "chutes",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.1,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "unsloth/gemma-3-4b-it",
    name: "gemma 3 4b it",
    provider: "chutes",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.0272,
    contextWindow: 96000,
    maxOutputTokens: 96000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "unsloth/gemma-3-27b-it",
    name: "gemma 3 27b it",
    provider: "chutes",
    inputPricePer1M: 0.0272,
    outputPricePer1M: 0.1087,
    contextWindow: 128000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "unsloth/Mistral-Nemo-Instruct-2407",
    name: "Mistral Nemo Instruct 2407",
    provider: "chutes",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.04,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "unsloth/Llama-3.2-3B-Instruct",
    name: "Llama 3.2 3B Instruct",
    provider: "chutes",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.0136,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "tngtech/DeepSeek-TNG-R1T2-Chimera-TEE",
    name: "DeepSeek TNG R1T2 Chimera TEE",
    provider: "chutes",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.1,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7-TEE",
    name: "GLM 4.7 TEE",
    provider: "chutes",
    inputPricePer1M: 0.39,
    outputPricePer1M: 1.75,
    contextWindow: 202752,
    maxOutputTokens: 65535,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5-TEE",
    name: "GLM 5 TEE",
    provider: "chutes",
    inputPricePer1M: 0.95,
    outputPricePer1M: 2.55,
    contextWindow: 202752,
    maxOutputTokens: 65535,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1-TEE",
    name: "GLM 5.1 TEE",
    provider: "chutes",
    inputPricePer1M: 1.05,
    outputPricePer1M: 3.5,
    contextWindow: 202752,
    maxOutputTokens: 65535,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.6V",
    name: "GLM 4.6V",
    provider: "chutes",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5-Turbo",
    name: "GLM 5 Turbo",
    provider: "chutes",
    inputPricePer1M: 0.4891,
    outputPricePer1M: 1.9565,
    contextWindow: 202752,
    maxOutputTokens: 65535,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7-FP8",
    name: "GLM 4.7 FP8",
    provider: "chutes",
    inputPricePer1M: 0.2989,
    outputPricePer1M: 1.1957,
    contextWindow: 202752,
    maxOutputTokens: 65535,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2-TEE",
    name: "DeepSeek V3.2 TEE",
    provider: "chutes",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.42,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3-0324-TEE",
    name: "DeepSeek V3 0324 TEE",
    provider: "chutes",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.1-TEE",
    name: "DeepSeek V3.1 TEE",
    provider: "chutes",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    name: "DeepSeek R1 Distill Llama 70B",
    provider: "chutes",
    inputPricePer1M: 0.0272,
    outputPricePer1M: 0.1087,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-0528-TEE",
    name: "DeepSeek R1 0528 TEE",
    provider: "chutes",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.15,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5-TEE",
    name: "MiniMax M2.5 TEE",
    provider: "chutes",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.2,
    contextWindow: 196608,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "rednote-hilab/dots.ocr",
    name: "dots.ocr",
    provider: "chutes",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.0109,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
];

export class ChutesAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "chutes", apiKey, models: MODELS, apiBase: "https://llm.chutes.ai/v1" });
  }
}
