import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/chat-completion/models/Kimi-K2_6",
    name: "Kimi K2.6",
    provider: "clarifai",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimaxai/chat-completion/models/MiniMax-M2_5-high-throughput",
    name: "MiniMax-M2.5 High Throughput",
    provider: "clarifai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/chat-completion/models/gpt-oss-120b-high-throughput",
    name: "GPT OSS 120B High Throughput",
    provider: "clarifai",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.36,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/chat-completion/models/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "clarifai",
    inputPricePer1M: 0.045,
    outputPricePer1M: 0.18,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistralai/completion/models/Ministral-3-14B-Reasoning-2512",
    name: "Ministral 3 14B Reasoning 2512",
    provider: "clarifai",
    inputPricePer1M: 2.5,
    outputPricePer1M: 1.7,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistralai/completion/models/Ministral-3-3B-Reasoning-2512",
    name: "Ministral 3 3B Reasoning 2512",
    provider: "clarifai",
    inputPricePer1M: 1.039,
    outputPricePer1M: 0.54825,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/deepseek-ocr/models/DeepSeek-OCR",
    name: "DeepSeek OCR",
    provider: "clarifai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.7,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwenLM/models/Qwen3-30B-A3B-Thinking-2507",
    name: "Qwen3 30B A3B Thinking 2507",
    provider: "clarifai",
    inputPricePer1M: 0.36,
    outputPricePer1M: 1.3,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwenLM/models/Qwen3-30B-A3B-Instruct-2507",
    name: "Qwen3 30B A3B Instruct 2507",
    provider: "clarifai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwenCoder/models/Qwen3-Coder-30B-A3B-Instruct",
    name: "Qwen3 Coder 30B A3B Instruct",
    provider: "clarifai",
    inputPricePer1M: 0.11458,
    outputPricePer1M: 0.74812,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "arcee_ai/AFM/models/trinity-mini",
    name: "Trinity Mini",
    provider: "clarifai",
    inputPricePer1M: 0.045,
    outputPricePer1M: 0.15,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "clarifai/main/models/mm-poly-8b",
    name: "MM Poly 8B",
    provider: "clarifai",
    inputPricePer1M: 0.658,
    outputPricePer1M: 1.11,
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
];

export class ClarifaiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "clarifai",
      apiKey,
      models: MODELS,
      apiBase: "https://api.clarifai.com/v2/ext/openai/v1",
    });
  }
}
