import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "workers-ai/@cf/baai/bge-m3",
    name: "BGE M3",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.012,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/baai/bge-small-en-v1.5",
    name: "BGE Small EN v1.5",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/baai/bge-reranker-base",
    name: "BGE Reranker Base",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.0031,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/baai/bge-base-en-v1.5",
    name: "BGE Base EN v1.5",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.067,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/baai/bge-large-en-v1.5",
    name: "BGE Large EN v1.5",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/ai4bharat/indictrans2-en-indic-1B",
    name: "IndicTrans2 EN-Indic 1B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.34,
    outputPricePer1M: 0.34,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/ibm-granite/granite-4.0-h-micro",
    name: "IBM Granite 4.0 H Micro",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.017,
    outputPricePer1M: 0.11,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/huggingface/distilbert-sst-2-int8",
    name: "DistilBERT SST-2 INT8",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.026,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "workers-ai/@cf/moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "workers-ai/@cf/mistral/mistral-7b-instruct-v0.1",
    name: "Mistral 7B Instruct v0.1",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.19,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/google/gemma-3-12b-it",
    name: "Gemma 3 12B IT",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.56,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/myshell-ai/melotts",
    name: "MyShell MeloTTS",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.75,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/mistralai/mistral-small-3.1-24b-instruct",
    name: "Mistral Small 3.1 24B Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.56,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/nvidia/nemotron-3-120b-a12b",
    name: "Nemotron 3 Super 120B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "workers-ai/@cf/pfnet/plamo-embedding-1b",
    name: "PLaMo Embedding 1B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.019,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/deepgram/aura-2-es",
    name: "Deepgram Aura 2 (ES)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/deepgram/aura-2-en",
    name: "Deepgram Aura 2 (EN)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/deepgram/nova-3",
    name: "Deepgram Nova 3",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/zai-org/glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.4,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "workers-ai/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    name: "DeepSeek R1 Distill Qwen 32B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 4.88,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/qwen/qwen3-embedding-0.6b",
    name: "Qwen3 Embedding 0.6B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.012,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/qwen/qwen3-30b-a3b-fp8",
    name: "Qwen3 30B A3B FP8",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.051,
    outputPricePer1M: 0.34,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/qwen/qwen2.5-coder-32b-instruct",
    name: "Qwen 2.5 Coder 32B Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.66,
    outputPricePer1M: 1,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/qwen/qwq-32b",
    name: "QwQ 32B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.66,
    outputPricePer1M: 1,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/pipecat-ai/smart-turn-v2",
    name: "Pipecat Smart Turn v2",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.8299999999999998,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/m2m100-1.2b",
    name: "M2M100 1.2B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.34,
    outputPricePer1M: 0.34,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.2-1b-instruct",
    name: "Llama 3.2 1B Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.027,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.2-11b-vision-instruct",
    name: "Llama 3.2 11B Vision Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.049,
    outputPricePer1M: 0.68,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout 17B 16E Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.85,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-guard-3-8b",
    name: "Llama Guard 3 8B",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.48,
    outputPricePer1M: 0.03,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3-8b-instruct-awq",
    name: "Llama 3 8B Instruct AWQ",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.27,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.1-8b-instruct-awq",
    name: "Llama 3.1 8B Instruct AWQ",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.27,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    name: "Llama 3.3 70B Instruct FP8 Fast",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.29,
    outputPricePer1M: 2.25,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3-8b-instruct",
    name: "Llama 3 8B Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.83,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.1-8b-instruct-fp8",
    name: "Llama 3.1 8B Instruct FP8",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.29,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-2-7b-chat-fp16",
    name: "Llama 2 7B Chat FP16",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.56,
    outputPricePer1M: 6.67,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.051,
    outputPricePer1M: 0.34,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/facebook/bart-large-cnn",
    name: "BART Large CNN",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "workers-ai/@cf/aisingapore/gemma-sea-lion-v4-27b-it",
    name: "Gemma SEA-LION v4 27B IT",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.56,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o3",
    name: "o3",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-3.5-turbo",
    name: "GPT-3.5-turbo",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 16385,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-4",
    name: "GPT-4",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 30,
    outputPricePer1M: 60,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o4-mini",
    name: "o4-mini",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/o3-pro",
    name: "o3-pro",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 20,
    outputPricePer1M: 80,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-codex",
    name: "GPT-5.1 Codex",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/o3-mini",
    name: "o3-mini",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2",
    name: "GPT-5.2",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/o1",
    name: "o1",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 15,
    outputPricePer1M: 60,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4",
    name: "GPT-5.4",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 10,
    outputPricePer1M: 30,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o mini",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2-codex",
    name: "GPT-5.2 Codex",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1",
    name: "GPT-5.1",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.5",
    name: "GPT-5.5",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3.5-haiku",
    name: "Claude Haiku 3.5 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Claude Sonnet 3.5 v2",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4",
    name: "Claude Sonnet 4 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4-5",
    name: "Claude Opus 4.5 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4-5",
    name: "Claude Sonnet 4.5 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3-sonnet",
    name: "Claude Sonnet 3",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3-opus",
    name: "Claude Opus 3",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3-5-haiku",
    name: "Claude Haiku 3.5 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4-1",
    name: "Claude Opus 4.1 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-fable-5",
    name: "Claude Fable 5",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 10,
    outputPricePer1M: 50,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-haiku-4-5",
    name: "Claude Haiku 4.5 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4-6",
    name: "Claude Opus 4.6 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3-haiku",
    name: "Claude Haiku 3",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.25,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4",
    name: "Claude Opus 4 (latest)",
    provider: "cloudflare-ai-gateway",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class CloudflareAiGatewayAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "cloudflare-ai-gateway", apiKey, models: MODELS });
  }
}
