import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "@cf/ibm-granite/granite-4.0-h-micro",
    name: "Granite 4.0 H Micro",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.017,
    outputPricePer1M: 0.112,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/moonshotai/kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/google/gemma-4-26b-a4b-it",
    name: "Gemma 4 26B A4B IT",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.75,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/mistralai/mistral-small-3.1-24b-instruct",
    name: "Mistral Small 3.1 24B Instruct",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.351,
    outputPricePer1M: 0.555,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/nvidia/nemotron-3-120b-a12b",
    name: "Nemotron 3 Super 120B",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/zai-org/glm-5.2",
    name: "Glm 5.2",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/zai-org/glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.0605,
    outputPricePer1M: 0.4,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    name: "Deepseek R1 Distill Qwen 32B",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.497,
    outputPricePer1M: 4.881,
    contextWindow: 80000,
    maxOutputTokens: 80000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/qwen/qwen3-30b-a3b-fp8",
    name: "Qwen3 30B A3b fp8",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.0509,
    outputPricePer1M: 0.335,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/qwen/qwen2.5-coder-32b-instruct",
    name: "Qwen2.5 Coder 32B Instruct",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.66,
    outputPricePer1M: 1,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/qwen/qwq-32b",
    name: "Qwq 32B",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.66,
    outputPricePer1M: 1,
    contextWindow: 24000,
    maxOutputTokens: 24000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/meta/llama-3.2-1b-instruct",
    name: "Llama 3.2 1B Instruct",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.027,
    outputPricePer1M: 0.201,
    contextWindow: 60000,
    maxOutputTokens: 60000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/meta/llama-3.2-11b-vision-instruct",
    name: "Llama 3.2 11B Vision Instruct",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.0485,
    outputPricePer1M: 0.676,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/meta/llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout 17B 16E Instruct",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.85,
    contextWindow: 131000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/meta/llama-guard-3-8b",
    name: "Llama Guard 3 8B",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.484,
    outputPricePer1M: 0.03,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    name: "Llama 3.3 70B Instruct fp8 Fast",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.293,
    outputPricePer1M: 2.253,
    contextWindow: 24000,
    maxOutputTokens: 24000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/meta/llama-3.1-8b-instruct-fp8",
    name: "Llama 3.1 8B Instruct fp8",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.152,
    outputPricePer1M: 0.287,
    contextWindow: 32000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/meta/llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.0509,
    outputPricePer1M: 0.335,
    contextWindow: 80000,
    maxOutputTokens: 80000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
    name: "Gemma Sea Lion V4 27B It",
    provider: "cloudflare-workers-ai",
    inputPricePer1M: 0.351,
    outputPricePer1M: 0.555,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
];

export class CloudflareWorkersAiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "cloudflare-workers-ai",
      apiKey,
      models: MODELS,
    });
  }
}
