import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "c4ai-aya-expanse-32b",
    name: "Aya Expanse 32B",
    provider: "cohere",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-a-03-2025",
    name: "Command A",
    provider: "cohere",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 256000,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "c4ai-aya-vision-32b",
    name: "Aya Vision 32B",
    provider: "cohere",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 16000,
    maxOutputTokens: 4000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-r7b-arabic-02-2025",
    name: "Command R7B Arabic",
    provider: "cohere",
    inputPricePer1M: 0.0375,
    outputPricePer1M: 0.15,
    contextWindow: 128000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "c4ai-aya-vision-8b",
    name: "Aya Vision 8B",
    provider: "cohere",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 16000,
    maxOutputTokens: 4000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-r-08-2024",
    name: "Command R",
    provider: "cohere",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-r7b-12-2024",
    name: "Command R7B",
    provider: "cohere",
    inputPricePer1M: 0.0375,
    outputPricePer1M: 0.15,
    contextWindow: 128000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-a-vision-07-2025",
    name: "Command A Vision",
    provider: "cohere",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 8000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-a-plus-05-2026",
    name: "Command A Plus",
    provider: "cohere",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "command-a-translate-08-2025",
    name: "Command A Translate",
    provider: "cohere",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 8000,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-r-plus-08-2024",
    name: "Command R+",
    provider: "cohere",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "command-a-reasoning-08-2025",
    name: "Command A Reasoning",
    provider: "cohere",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "north-mini-code-1-0",
    name: "North Mini Code",
    provider: "cohere",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "c4ai-aya-expanse-8b",
    name: "Aya Expanse 8B",
    provider: "cohere",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
];

export class CohereAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "cohere", apiKey, models: MODELS });
  }
}
