import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "deepseek-r1-0528",
    name: "DeepSeek R1 0528",
    provider: "cortecs",
    inputPricePer1M: 0.585,
    outputPricePer1M: 2.307,
    contextWindow: 164000,
    maxOutputTokens: 164000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "cortecs",
    inputPricePer1M: 0.133,
    outputPricePer1M: 0.266,
    contextWindow: 1048576,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax-M2.5",
    provider: "cortecs",
    inputPricePer1M: 0.32,
    outputPricePer1M: 1.18,
    contextWindow: 196608,
    maxOutputTokens: 196608,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v3-0324",
    name: "DeepSeek V3 0324",
    provider: "cortecs",
    inputPricePer1M: 0.551,
    outputPricePer1M: 1.654,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus4-7",
    name: "Claude Opus 4.7",
    provider: "cortecs",
    inputPricePer1M: 5.6,
    outputPricePer1M: 27.99,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.7",
    name: "GLM 4.7",
    provider: "cortecs",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.23,
    contextWindow: 198000,
    maxOutputTokens: 198000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    provider: "cortecs",
    inputPricePer1M: 0.062,
    outputPricePer1M: 0.408,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3 Coder 30B A3B Instruct",
    provider: "cortecs",
    inputPricePer1M: 0.053,
    outputPricePer1M: 0.222,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax-m2.1",
    name: "MiniMax-M2.1",
    provider: "cortecs",
    inputPricePer1M: 0.34,
    outputPricePer1M: 1.34,
    contextWindow: 196000,
    maxOutputTokens: 196000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    provider: "cortecs",
    inputPricePer1M: 0.099,
    outputPricePer1M: 0.33,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-4-6-sonnet",
    name: "Claude Sonnet 4.6",
    provider: "cortecs",
    inputPricePer1M: 3.59,
    outputPricePer1M: 17.92,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "cortecs",
    inputPricePer1M: 3.307,
    outputPricePer1M: 16.536,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick 17B Instruct",
    provider: "cortecs",
    inputPricePer1M: 0.124,
    outputPricePer1M: 0.603,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "cortecs",
    inputPricePer1M: 1.654,
    outputPricePer1M: 11.024,
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-4-5-sonnet",
    name: "Claude 4.5 Sonnet",
    provider: "cortecs",
    inputPricePer1M: 3.259,
    outputPricePer1M: 16.296,
    contextWindow: 200000,
    maxOutputTokens: 200000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mixtral-8x7B-instruct-v0.1",
    name: "Mixtral 8x7B Instruct v0.1",
    provider: "cortecs",
    inputPricePer1M: 0.438,
    outputPricePer1M: 0.68,
    contextWindow: 32000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.5",
    name: "GLM 4.5",
    provider: "cortecs",
    inputPricePer1M: 0.67,
    outputPricePer1M: 2.46,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-instruct",
    name: "Kimi K2 Instruct",
    provider: "cortecs",
    inputPricePer1M: 0.551,
    outputPricePer1M: 2.646,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    provider: "cortecs",
    inputPricePer1M: 0.089,
    outputPricePer1M: 0.275,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus4-8",
    name: "Claude Opus 4.8",
    provider: "cortecs",
    inputPricePer1M: 5.64,
    outputPricePer1M: 28.198,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "cortecs",
    inputPricePer1M: 1.28,
    outputPricePer1M: 4.63,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    provider: "cortecs",
    inputPricePer1M: 1.31,
    outputPricePer1M: 4.1,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "cortecs",
    inputPricePer1M: 1.553,
    outputPricePer1M: 3.106,
    contextWindow: 1048576,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-next-80b-a3b-thinking",
    name: "Qwen3 Next 80B A3B Thinking",
    provider: "cortecs",
    inputPricePer1M: 0.164,
    outputPricePer1M: 1.311,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "cortecs",
    inputPricePer1M: 0.656,
    outputPricePer1M: 2.731,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5.2",
    name: "GLM-5.2",
    provider: "cortecs",
    inputPricePer1M: 1.44,
    outputPricePer1M: 4.53,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax-m3",
    name: "MiniMax-M3",
    provider: "cortecs",
    inputPricePer1M: 0.355,
    outputPricePer1M: 1.775,
    contextWindow: 512000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax-m2",
    name: "MiniMax-M2",
    provider: "cortecs",
    inputPricePer1M: 0.39,
    outputPricePer1M: 1.57,
    contextWindow: 400000,
    maxOutputTokens: 400000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax-m2.7",
    name: "MiniMax-m2.7",
    provider: "cortecs",
    inputPricePer1M: 0.47,
    outputPricePer1M: 1.4,
    contextWindow: 202752,
    maxOutputTokens: 196072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "cortecs",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.76,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-oss-120b",
    name: "GPT Oss 120b",
    provider: "cortecs",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-2.5-72b-instruct",
    name: "Qwen2.5 72B Instruct",
    provider: "cortecs",
    inputPricePer1M: 0.062,
    outputPricePer1M: 0.231,
    contextWindow: 33000,
    maxOutputTokens: 33000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hermes-4-70b",
    name: "Hermes 4 70B",
    provider: "cortecs",
    inputPricePer1M: 0.116,
    outputPricePer1M: 0.358,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "cortecs",
    inputPricePer1M: 1.09,
    outputPricePer1M: 5.43,
    contextWindow: 200000,
    maxOutputTokens: 200000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    provider: "cortecs",
    inputPricePer1M: 3,
    outputPricePer1M: 16.13,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "cortecs",
    inputPricePer1M: 0.81,
    outputPricePer1M: 3.54,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-4.1",
    name: "GPT 4.1",
    provider: "cortecs",
    inputPricePer1M: 2.354,
    outputPricePer1M: 9.417,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "nova-pro-v1",
    name: "Nova Pro 1.0",
    provider: "cortecs",
    inputPricePer1M: 1.016,
    outputPricePer1M: 4.061,
    contextWindow: 300000,
    maxOutputTokens: 5000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-next",
    name: "Qwen3 Coder Next 80B",
    provider: "cortecs",
    inputPricePer1M: 0.158,
    outputPricePer1M: 0.84,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus4-5",
    name: "Claude Opus 4.5",
    provider: "cortecs",
    inputPricePer1M: 5.98,
    outputPricePer1M: 29.89,
    contextWindow: 200000,
    maxOutputTokens: 200000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "Qwen3 Coder 480B A35B Instruct",
    provider: "cortecs",
    inputPricePer1M: 0.441,
    outputPricePer1M: 1.984,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "devstral-2512",
    name: "Devstral 2 2512",
    provider: "cortecs",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B A17B",
    provider: "cortecs",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 250000,
    maxOutputTokens: 250000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5v-turbo",
    name: "GLM-5V-Turbo",
    provider: "cortecs",
    inputPricePer1M: 1.235,
    outputPricePer1M: 4.118,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5-air",
    name: "GLM 4.5 Air",
    provider: "cortecs",
    inputPricePer1M: 0.22,
    outputPricePer1M: 1.34,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "cortecs",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.53,
    contextWindow: 203000,
    maxOutputTokens: 203000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "intellect-3",
    name: "INTELLECT 3",
    provider: "cortecs",
    inputPricePer1M: 0.219,
    outputPricePer1M: 1.202,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.1-405b-instruct",
    name: "Llama 3.1 405B Instruct",
    provider: "cortecs",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5",
    name: "GLM 5",
    provider: "cortecs",
    inputPricePer1M: 1.08,
    outputPricePer1M: 3.44,
    contextWindow: 202752,
    maxOutputTokens: 202752,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-large-2512",
    name: "Mistral Large 3 2512",
    provider: "cortecs",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "cortecs",
    inputPricePer1M: 0.266,
    outputPricePer1M: 0.444,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "codestral-2508",
    name: "Codestral 2508",
    provider: "cortecs",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.5-122b-a10b",
    name: "Qwen3.5 122B A10B",
    provider: "cortecs",
    inputPricePer1M: 0.444,
    outputPricePer1M: 3.106,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "nemotron-3-super-120b-a12b",
    name: "Nemotron 3 Super 120B A12B",
    provider: "cortecs",
    inputPricePer1M: 0.266,
    outputPricePer1M: 0.799,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5-turbo",
    name: "GLM-5-Turbo",
    provider: "cortecs",
    inputPricePer1M: 1.235,
    outputPricePer1M: 4.118,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus4-6",
    name: "Claude Opus 4.6",
    provider: "cortecs",
    inputPricePer1M: 5.98,
    outputPricePer1M: 29.89,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class CortecsAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "cortecs", apiKey, models: MODELS, apiBase: "https://api.cortecs.ai/v1" });
  }
}
