import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "crof",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.21,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax-M2.5",
    provider: "crof",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.95,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "greg-2-ultra",
    name: "Greg 2 Ultra",
    provider: "crof",
    inputPricePer1M: 3,
    outputPricePer1M: 10,
    contextWindow: 229376,
    maxOutputTokens: 229376,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.7",
    name: "GLM-4.7",
    provider: "crof",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.1,
    contextWindow: 202752,
    maxOutputTokens: 202752,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v4-pro-lightning",
    name: "DeepSeek V4 Pro Lightning",
    provider: "crof",
    inputPricePer1M: 0.8,
    outputPricePer1M: 1.6,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "greg-rp",
    name: "Greg (Roleplay)",
    provider: "crof",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 229376,
    maxOutputTokens: 229376,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    provider: "crof",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "crof",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.25,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    provider: "crof",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.15,
    contextWindow: 202752,
    maxOutputTokens: 202752,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "crof",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.8,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5.2",
    name: "GLM-5.2",
    provider: "crof",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.2,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "greg-2-super",
    name: "Greg 2 Super",
    provider: "crof",
    inputPricePer1M: 1.5,
    outputPricePer1M: 5,
    contextWindow: 229376,
    maxOutputTokens: 229376,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2.5-lightning",
    name: "Kimi K2.5 (Lightning)",
    provider: "crof",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "crof",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.7,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "crof",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.99,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.6-27b",
    name: "Qwen3.6 27B",
    provider: "crof",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5 9B",
    provider: "crof",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.15,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B-A17B",
    provider: "crof",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.75,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "crof",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.3,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo-V2.5-Pro",
    provider: "crof",
    inputPricePer1M: 0.4,
    outputPricePer1M: 0.8,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "crof",
    inputPricePer1M: 0.48,
    outputPricePer1M: 1.9,
    contextWindow: 202752,
    maxOutputTokens: 202752,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "crof",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.35,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "greg-1-mini",
    name: "Greg 1 Mini",
    provider: "crof",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.15,
    contextWindow: 229376,
    maxOutputTokens: 229376,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
];

export class CrofAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "crof", apiKey, models: MODELS, apiBase: "https://crof.ai/v1" });
  }
}
