import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    name: "Llama 4 Maverick 17B FP8",
    provider: "deepinfra",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    name: "Llama 4 Scout 17B",
    provider: "deepinfra",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 327680,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    name: "Llama 3.3 70B Turbo",
    provider: "deepinfra",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.32,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "deepinfra",
    inputPricePer1M: 0.75,
    outputPricePer1M: 3.5,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    provider: "deepinfra",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.25,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-4-31B-it",
    name: "Gemma 4 31B IT",
    provider: "deepinfra",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.38,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-4-26B-A4B-it",
    name: "Gemma 4 26B A4B IT",
    provider: "deepinfra",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.34,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.6-35B-A3B",
    name: "Qwen3.6 35B A3B",
    provider: "deepinfra",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.95,
    contextWindow: 262144,
    maxOutputTokens: 81920,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B",
    name: "Qwen 3.5 397B A17B",
    provider: "deepinfra",
    inputPricePer1M: 0.45,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 81920,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo",
    name: "Qwen3 Coder 480B A35B Instruct Turbo",
    provider: "deepinfra",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1,
    contextWindow: 262144,
    maxOutputTokens: 66536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-35B-A3B",
    name: "Qwen 3.5 35B A3B",
    provider: "deepinfra",
    inputPricePer1M: 0.14,
    outputPricePer1M: 1,
    contextWindow: 262144,
    maxOutputTokens: 81920,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "deepinfra",
    inputPricePer1M: 0.039,
    outputPricePer1M: 0.19,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "deepinfra",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.14,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "XiaomiMiMo/MiMo-V2.5",
    name: "MiMo-V2.5",
    provider: "deepinfra",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "XiaomiMiMo/MiMo-V2.5-Pro",
    name: "MiMo-V2.5-Pro",
    provider: "deepinfra",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7-Flash",
    name: "GLM-4.7-Flash",
    provider: "deepinfra",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.4,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.6",
    name: "GLM-4.6",
    provider: "deepinfra",
    inputPricePer1M: 0.43,
    outputPricePer1M: 1.74,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    provider: "deepinfra",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.08,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7",
    name: "GLM-4.7",
    provider: "deepinfra",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.75,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1",
    name: "GLM-5.1",
    provider: "deepinfra",
    inputPricePer1M: 1.05,
    outputPricePer1M: 3.5,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-0528",
    name: "DeepSeek-R1-0528",
    provider: "deepinfra",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.15,
    contextWindow: 163840,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Flash",
    name: "DeepSeek V4 Flash",
    provider: "deepinfra",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.2,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Pro",
    name: "DeepSeek V4 Pro",
    provider: "deepinfra",
    inputPricePer1M: 1.3,
    outputPricePer1M: 2.6,
    contextWindow: 1048576,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2",
    name: "DeepSeek-V3.2",
    provider: "deepinfra",
    inputPricePer1M: 0.26,
    outputPricePer1M: 0.38,
    contextWindow: 163840,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax M2.5",
    provider: "deepinfra",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.15,
    contextWindow: 196608,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class DeepinfraAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "deepinfra", apiKey, models: MODELS });
  }
}
