import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "anthropic-claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "digitalocean",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-image-1",
    name: "GPT Image 1",
    provider: "digitalocean",
    inputPricePer1M: 5,
    outputPricePer1M: 40,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "e5-large-v2",
    name: "E5 Large v2",
    provider: "digitalocean",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0,
    contextWindow: 512,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "bge-m3",
    name: "BGE M3",
    provider: "digitalocean",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-3-14B",
    name: "Ministral 3 14B Instruct",
    provider: "digitalocean",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 262144,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nemotron-3-ultra-550b",
    name: "Nemotron 3 Ultra",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax M2.5",
    provider: "digitalocean",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5.4-nano",
    name: "GPT-5.4 nano",
    provider: "digitalocean",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.25,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 163840,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-image-2",
    name: "GPT Image 2",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-5.2",
    name: "GPT-5.2",
    provider: "digitalocean",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-r1-distill-llama-70b",
    name: "DeepSeek R1 Distill Llama 70B",
    provider: "digitalocean",
    inputPricePer1M: 0.99,
    outputPricePer1M: 0.99,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-embedding-0.6b",
    name: "Qwen3 Embedding 0.6B",
    provider: "digitalocean",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0,
    contextWindow: 8000,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gemma-4-31B-it",
    name: "Gemma 4 31B",
    provider: "digitalocean",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.5,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick 17B 128E Instruct",
    provider: "digitalocean",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.87,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "anthropic-claude-3.7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "digitalocean",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-4o-mini",
    name: "GPT-4o mini",
    provider: "digitalocean",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic-claude-opus-4.7",
    name: "Claude Opus 4.7",
    provider: "digitalocean",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-4-flash",
    name: "Deepseek V4 Flash",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-4.5-haiku",
    name: "Claude Haiku 4.5",
    provider: "digitalocean",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-4.6-sonnet",
    name: "Claude Sonnet 4.6",
    provider: "digitalocean",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "digitalocean",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "ministral-3-8b-instruct-2512",
    name: "Ministral 3 8B",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "anthropic-claude-4.5-sonnet",
    name: "Claude Sonnet 4.5",
    provider: "digitalocean",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-opus-4.6",
    name: "Claude Opus 4.6",
    provider: "digitalocean",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "digitalocean",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 1048576,
    maxOutputTokens: 393216,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai-gpt-oss-20b",
    name: "gpt-oss-20b",
    provider: "digitalocean",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.45,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen-2.5-14b-instruct",
    name: "Qwen 2.5 14B Instruct",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "anthropic-claude-opus-4.8",
    name: "Claude Opus 4.8",
    provider: "digitalocean",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-opus-4.5",
    name: "Claude Opus 4.5",
    provider: "digitalocean",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-4.1-opus",
    name: "Claude Opus 4.1",
    provider: "digitalocean",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama3-8b-instruct",
    name: "Llama 3.1 Instruct (8B)",
    provider: "digitalocean",
    inputPricePer1M: 0.198,
    outputPricePer1M: 0.198,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "stable-diffusion-3.5-large",
    name: "Stable Diffusion 3.5 Large",
    provider: "digitalocean",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0,
    contextWindow: 256,
    maxOutputTokens: 1,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5.4-pro",
    name: "GPT-5.4 pro",
    provider: "digitalocean",
    inputPricePer1M: 30,
    outputPricePer1M: 180,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "all-mini-lm-l6-v2",
    name: "All-MiniLM-L6-v2",
    provider: "digitalocean",
    inputPricePer1M: 0.009,
    outputPricePer1M: 0,
    contextWindow: 256,
    maxOutputTokens: 384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-image-1.5",
    name: "GPT Image 1.5",
    provider: "digitalocean",
    inputPricePer1M: 5,
    outputPricePer1M: 10,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-4o",
    name: "GPT-4o",
    provider: "digitalocean",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic-claude-opus-4",
    name: "Claude Opus 4",
    provider: "digitalocean",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "bge-reranker-v2-m3",
    name: "BGE Reranker v2 M3",
    provider: "digitalocean",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 1,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5",
    name: "GPT-5",
    provider: "digitalocean",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-o3-mini",
    name: "o3-mini",
    provider: "digitalocean",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "multi-qa-mpnet-base-dot-v1",
    name: "Multi-QA-mpnet-base-dot-v1",
    provider: "digitalocean",
    inputPricePer1M: 0.009,
    outputPricePer1M: 0,
    contextWindow: 512,
    maxOutputTokens: 768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "digitalocean",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.7,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "llama3.3-70b-instruct",
    name: "Llama 3.3 Instruct 70B",
    provider: "digitalocean",
    inputPricePer1M: 0.65,
    outputPricePer1M: 0.65,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gte-large-en-v1.5",
    name: "GTE Large (v1.5)",
    provider: "digitalocean",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 1024,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5.4-mini",
    name: "GPT-5.4 mini",
    provider: "digitalocean",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-5.5",
    name: "GPT-5.5",
    provider: "digitalocean",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "nemotron-3-nano-30b",
    name: "Nemotron 3 Nano 30B A3B",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-oss-120b",
    name: "gpt-oss-120b",
    provider: "digitalocean",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.7,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai-gpt-5-nano",
    name: "GPT-5 nano",
    provider: "digitalocean",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.4,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "wan2-2-t2v-a14b",
    name: "Wan2.2-T2V-A14B",
    provider: "digitalocean",
    inputPricePer1M: 0.6,
    outputPricePer1M: 0,
    contextWindow: 100,
    maxOutputTokens: 1,
    inputModalities: ["text"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-7b-instruct-v0.3",
    name: "Mistral 7B Instruct v0.3",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-tts-voicedesign",
    name: "Qwen3 TTS VoiceDesign",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 1,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-nemo-instruct-2407",
    name: "Mistral Nemo Instruct",
    provider: "digitalocean",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "digitalocean",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-3.2",
    name: "DeepSeek V3.2",
    provider: "digitalocean",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.6,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-o1",
    name: "o1",
    provider: "digitalocean",
    inputPricePer1M: 15,
    outputPricePer1M: 60,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen 3.5 397B A17B",
    provider: "digitalocean",
    inputPricePer1M: 0.55,
    outputPricePer1M: 3.5,
    contextWindow: 262144,
    maxOutputTokens: 81920,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    provider: "digitalocean",
    inputPricePer1M: 0.45,
    outputPricePer1M: 1.7,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "digitalocean",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-4.1",
    name: "GPT-4.1",
    provider: "digitalocean",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic-claude-3.5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "digitalocean",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-5.4",
    name: "GPT-5.4",
    provider: "digitalocean",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "arcee-trinity-large-thinking",
    name: "Trinity Large Thinking",
    provider: "digitalocean",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.9,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-o3",
    name: "o3",
    provider: "digitalocean",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "anthropic-claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "digitalocean",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-5-mini",
    name: "GPT-5 mini",
    provider: "digitalocean",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "nvidia-nemotron-3-super-120b",
    name: "Nemotron-3-Super-120B",
    provider: "digitalocean",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.65,
    contextWindow: 256000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5",
    name: "GLM 5",
    provider: "digitalocean",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202752,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5.2-pro",
    name: "GPT-5.2 pro",
    provider: "digitalocean",
    inputPricePer1M: 21,
    outputPricePer1M: 168,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-3-opus",
    name: "Claude 3 Opus",
    provider: "digitalocean",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic-claude-fable-5",
    name: "Anthropic Claude Fable 5",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "nemotron-3-nano-omni",
    name: "Nemotron Nano 3 Omni",
    provider: "digitalocean",
    inputPricePer1M: 0.5,
    outputPricePer1M: 0.9,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "alibaba-qwen3-32b",
    name: "Qwen3-32B",
    provider: "digitalocean",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.55,
    contextWindow: 131000,
    maxOutputTokens: 40960,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nemotron-nano-12b-v2-vl",
    name: "Nemotron Nano 12B v2 VL",
    provider: "digitalocean",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5.1-codex-max",
    name: "GPT-5.1 Codex Max",
    provider: "digitalocean",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "fal-ai/fast-sdxl",
    name: "Fast SDXL",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "fal-ai/elevenlabs/tts/multilingual-v2",
    name: "ElevenLabs Multilingual TTS v2",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "fal-ai/flux/schnell",
    name: "FLUX.1 [schnell]",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "fal-ai/stable-audio-25/text-to-audio",
    name: "Stable Audio 2.5 (Text-to-Audio)",
    provider: "digitalocean",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
];

export class DigitaloceanAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "digitalocean",
      apiKey,
      models: MODELS,
      apiBase: "https://inference.do-ai.run/v1",
    });
  }
}
