import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    provider: "evroc",
    inputPricePer1M: 1.47,
    outputPricePer1M: 5.9,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "microsoft/Phi-4-multimodal-instruct",
    name: "Phi-4 15B",
    provider: "evroc",
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.47,
    contextWindow: 32000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Embedding-8B",
    name: "Qwen3 Embedding 8B",
    provider: "evroc",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.12,
    contextWindow: 40960,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Instruct-2507-FP8",
    name: "Qwen3 30B 2507",
    provider: "evroc",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.42,
    contextWindow: 64000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-VL-30B-A3B-Instruct",
    name: "Qwen3 VL 30B",
    provider: "evroc",
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.94,
    contextWindow: 100000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "evroc",
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.94,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/whisper-large-v3",
    name: "Whisper 3 Large",
    provider: "evroc",
    inputPricePer1M: 0.00236,
    outputPricePer1M: 0.00236,
    contextWindow: 448,
    maxOutputTokens: 4096,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistralai/devstral-small-2-24b-instruct-2512",
    name: "Devstral Small 2 24B Instruct 2512",
    provider: "evroc",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.47,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistralai/Magistral-Small-2509",
    name: "Magistral Small 1.2 24B",
    provider: "evroc",
    inputPricePer1M: 0.59,
    outputPricePer1M: 2.36,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistralai/Voxtral-Small-24B-2507",
    name: "Voxtral Small 24B",
    provider: "evroc",
    inputPricePer1M: 0.00236,
    outputPricePer1M: 0.00236,
    contextWindow: 32000,
    maxOutputTokens: 32000,
    inputModalities: ["audio", "text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "nvidia/Llama-3.3-70B-Instruct-FP8",
    name: "Llama 3.3 70B",
    provider: "evroc",
    inputPricePer1M: 1.18,
    outputPricePer1M: 1.18,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "KBLab/kb-whisper-large",
    name: "KB Whisper",
    provider: "evroc",
    inputPricePer1M: 0.00236,
    outputPricePer1M: 0.00236,
    contextWindow: 448,
    maxOutputTokens: 448,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "intfloat/multilingual-e5-large-instruct",
    name: "E5 Multi-Lingual Large Embeddings 0.6B",
    provider: "evroc",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.12,
    contextWindow: 512,
    maxOutputTokens: 512,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
];

export class EvrocAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "evroc", apiKey, models: MODELS, apiBase: "https://models.think.evroc.com/v1" });
  }
}
