import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "accounts/fireworks/routers/kimi-k2p6-turbo",
    name: "Kimi K2.6 Turbo",
    provider: "fireworks-ai",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/routers/kimi-k2p7-code-fast",
    name: "Kimi K2.7 Code Fast",
    provider: "fireworks-ai",
    inputPricePer1M: 1.9,
    outputPricePer1M: 8,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/routers/glm-5p1-fast",
    name: "GLM 5.1 Fast",
    provider: "fireworks-ai",
    inputPricePer1M: 2.8,
    outputPricePer1M: 8.8,
    contextWindow: 202800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/routers/kimi-k2p6-fast",
    name: "Kimi K2.6 Fast",
    provider: "fireworks-ai",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "fireworks-ai",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "fireworks-ai",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/minimax-m2p7",
    name: "MiniMax-M2.7",
    provider: "fireworks-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 196608,
    maxOutputTokens: 196608,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/minimax-m3",
    name: "MiniMax-M3",
    provider: "fireworks-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 512000,
    maxOutputTokens: 512000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/kimi-k2p6",
    name: "Kimi K2.6",
    provider: "fireworks-ai",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/qwen3p7-plus",
    name: "Qwen 3.7 Plus",
    provider: "fireworks-ai",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "accounts/fireworks/models/glm-5p1",
    name: "GLM 5.1",
    provider: "fireworks-ai",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 202800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/glm-5p2",
    name: "GLM 5.2",
    provider: "fireworks-ai",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "fireworks-ai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "fireworks-ai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.3,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "accounts/fireworks/models/kimi-k2p7-code",
    name: "Kimi K2.7 Code",
    provider: "fireworks-ai",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class FireworksAiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "fireworks-ai",
      apiKey,
      models: MODELS,
      apiBase: "https://api.fireworks.ai/inference/v1/",
    });
  }
}
