import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "duo-chat-opus-4-5",
    name: "Agentic Chat (Claude Opus 4.5)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "duo-chat-opus-4-8",
    name: "Agentic Chat (Claude Opus 4.8)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "duo-chat-opus-4-7",
    name: "Agentic Chat (Claude Opus 4.7)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-2-codex",
    name: "Agentic Chat (GPT-5.2 Codex)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-5",
    name: "Agentic Chat (GPT-5.5)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-opus-4-6",
    name: "Agentic Chat (Claude Opus 4.6)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-4",
    name: "Agentic Chat (GPT-5.4)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-codex",
    name: "Agentic Chat (GPT-5 Codex)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-4-nano",
    name: "Agentic Chat (GPT-5.4 Nano)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-sonnet-4-6",
    name: "Agentic Chat (Claude Sonnet 4.6)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-mini",
    name: "Agentic Chat (GPT-5 Mini)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-4-mini",
    name: "Agentic Chat (GPT-5.4 Mini)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-3-codex",
    name: "Agentic Chat (GPT-5.3 Codex)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-haiku-4-5",
    name: "Agentic Chat (Claude Haiku 4.5)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-2",
    name: "Agentic Chat (GPT-5.2)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "duo-chat-sonnet-4-5",
    name: "Agentic Chat (Claude Sonnet 4.5)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "duo-chat-gpt-5-1",
    name: "Agentic Chat (GPT-5.1)",
    provider: "gitlab",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class GitlabAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "gitlab", apiKey, models: MODELS });
  }
}
