import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "gmicloud",
    inputPricePer1M: 0.855,
    outputPricePer1M: 3.6,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "anthropic/claude-opus-4.7",
    name: "Claude Opus 4.7",
    provider: "gmicloud",
    inputPricePer1M: 4.5,
    outputPricePer1M: 22.5,
    contextWindow: 409600,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4.6",
    name: "Claude Sonnet 4.6",
    provider: "gmicloud",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 409600,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.6",
    name: "Claude Opus 4.6",
    provider: "gmicloud",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 409600,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-5.1-FP8",
    name: "GLM-5.1",
    provider: "gmicloud",
    inputPricePer1M: 0.98,
    outputPricePer1M: 3.08,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5-FP8",
    name: "GLM-5",
    provider: "gmicloud",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.92,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Flash",
    name: "DeepSeek V4 Flash",
    provider: "gmicloud",
    inputPricePer1M: 0.112,
    outputPricePer1M: 0.224,
    contextWindow: 1048575,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Pro",
    name: "DeepSeek V4 Pro",
    provider: "gmicloud",
    inputPricePer1M: 1.392,
    outputPricePer1M: 2.784,
    contextWindow: 1048576,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class GmicloudAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "gmicloud", apiKey, models: MODELS, apiBase: "https://api.gmi-serving.com/v1" });
  }
}
