import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "llama-3.3-70b-versatile",
    name: "Llama 3.3 70B",
    provider: "groq",
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.1-8b-instant",
    name: "Llama 3.1 8B",
    provider: "groq",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.08,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "whisper-large-v3-turbo",
    name: "Whisper Large V3 Turbo",
    provider: "groq",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "whisper-large-v3",
    name: "Whisper",
    provider: "groq",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-prompt-guard-2-86m",
    name: "Prompt Guard 2 86M",
    provider: "groq",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.04,
    contextWindow: 512,
    maxOutputTokens: 512,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-prompt-guard-2-22m",
    name: "Llama Prompt Guard 2 22M",
    provider: "groq",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.03,
    contextWindow: 512,
    maxOutputTokens: 512,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout 17B 16E",
    provider: "groq",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.34,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-safeguard-20b",
    name: "Safety GPT OSS 20B",
    provider: "groq",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "groq",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "groq",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "canopylabs/orpheus-v1-english",
    name: "Canopy Labs Orpheus V1 English",
    provider: "groq",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 4000,
    maxOutputTokens: 50000,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "canopylabs/orpheus-arabic-saudi",
    name: "Canopy Labs Orpheus Arabic Saudi",
    provider: "groq",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 4000,
    maxOutputTokens: 50000,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "groq/compound",
    name: "Compound",
    provider: "groq",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "groq/compound-mini",
    name: "Compound Mini",
    provider: "groq",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3-32b",
    name: "Qwen3-32B",
    provider: "groq",
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.59,
    contextWindow: 131072,
    maxOutputTokens: 40960,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class GroqAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "groq", apiKey, models: MODELS });
  }
}
