import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "chatgpt-4o-latest",
    name: "OpenAI ChatGPT-4o",
    provider: "helicone",
    inputPricePer1M: 5,
    outputPricePer1M: 20,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4.1-mini-2025-04-14",
    name: "OpenAI GPT-4.1 Mini",
    provider: "helicone",
    inputPricePer1M: 0.39999999999999997,
    outputPricePer1M: 1.5999999999999999,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.1-terminus",
    name: "DeepSeek V3.1 Terminus",
    provider: "helicone",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-3.5-haiku",
    name: "Anthropic: Claude 3.5 Haiku",
    provider: "helicone",
    inputPricePer1M: 0.7999999999999999,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-3.1-8b-instruct",
    name: "Meta Llama 3.1 8B Instruct",
    provider: "helicone",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.049999999999999996,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o3",
    name: "OpenAI o3",
    provider: "helicone",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-prompt-guard-2-86m",
    name: "Meta Llama Prompt Guard 2 86M",
    provider: "helicone",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.01,
    contextWindow: 512,
    maxOutputTokens: 2,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3 Coder 30B A3B Instruct",
    provider: "helicone",
    inputPricePer1M: 0.09999999999999999,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hermes-2-pro-llama-3-8b",
    name: "Hermes 2 Pro Llama 3 8B",
    provider: "helicone",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.14,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "helicone",
    inputPricePer1M: 0.56,
    outputPricePer1M: 1.68,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-code-fast-1",
    name: "xAI Grok Code Fast 1",
    provider: "helicone",
    inputPricePer1M: 0.19999999999999998,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 10000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o1-mini",
    name: "OpenAI: o1-mini",
    provider: "helicone",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 128000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-r1-distill-llama-70b",
    name: "DeepSeek R1 Distill Llama 70B",
    provider: "helicone",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.13,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    provider: "helicone",
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.59,
    contextWindow: 131072,
    maxOutputTokens: 40960,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4",
    name: "Anthropic: Claude Sonnet 4",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-next-80b-a3b-instruct",
    name: "Qwen3 Next 80B A3B Instruct",
    provider: "helicone",
    inputPricePer1M: 0.14,
    outputPricePer1M: 1.4,
    contextWindow: 262000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-4-maverick",
    name: "Meta Llama 4 Maverick 17B 128E",
    provider: "helicone",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-nemo",
    name: "Mistral Nemo",
    provider: "helicone",
    inputPricePer1M: 20,
    outputPricePer1M: 40,
    contextWindow: 128000,
    maxOutputTokens: 16400,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-3.3-70b-versatile",
    name: "Meta Llama 3.3 70B Versatile",
    provider: "helicone",
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.7899999999999999,
    contextWindow: 131072,
    maxOutputTokens: 32678,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemma2-9b-it",
    name: "Google Gemma 2",
    provider: "helicone",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.03,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-pro",
    name: "Google Gemini 2.5 Pro",
    provider: "helicone",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5",
    name: "OpenAI GPT-5",
    provider: "helicone",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "Anthropic: Claude 4.5 Haiku (20251001)",
    provider: "helicone",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-4.5-haiku",
    name: "Anthropic: Claude 4.5 Haiku",
    provider: "helicone",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-pro",
    name: "OpenAI: GPT-5 Pro",
    provider: "helicone",
    inputPricePer1M: 15,
    outputPricePer1M: 120,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash",
    name: "Google Gemini 2.5 Flash",
    provider: "helicone",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4o",
    name: "OpenAI GPT-4o",
    provider: "helicone",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o4-mini",
    name: "OpenAI o4 Mini",
    provider: "helicone",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-3.1-8b-instant",
    name: "Meta Llama 3.1 8B Instant",
    provider: "helicone",
    inputPricePer1M: 0.049999999999999996,
    outputPricePer1M: 0.08,
    contextWindow: 131072,
    maxOutputTokens: 32678,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-prompt-guard-2-22m",
    name: "Meta Llama Prompt Guard 2 22M",
    provider: "helicone",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.01,
    contextWindow: 512,
    maxOutputTokens: 2,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o3-pro",
    name: "OpenAI o3 Pro",
    provider: "helicone",
    inputPricePer1M: 20,
    outputPricePer1M: 80,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-3-mini",
    name: "xAI Grok 3 Mini",
    provider: "helicone",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.5,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-1-20250805",
    name: "Anthropic: Claude Opus 4.1 (20250805)",
    provider: "helicone",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-tng-r1t2-chimera",
    name: "DeepSeek TNG R1T2 Chimera",
    provider: "helicone",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 130000,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Meta Llama 3.3 70B Instruct",
    provider: "helicone",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.39,
    contextWindow: 128000,
    maxOutputTokens: 16400,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "sonar-reasoning-pro",
    name: "Perplexity Sonar Reasoning Pro",
    provider: "helicone",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 127000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-3",
    name: "xAI Grok 3",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.6",
    name: "Zai GLM-4.6",
    provider: "helicone",
    inputPricePer1M: 0.44999999999999996,
    outputPricePer1M: 1.5,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "helicone",
    inputPricePer1M: 0.48,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "xAI Grok 4.1 Fast Non-Reasoning",
    provider: "helicone",
    inputPricePer1M: 0.19999999999999998,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder",
    name: "Qwen3 Coder 480B A35B Instruct Turbo",
    provider: "helicone",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.95,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-chat-latest",
    name: "OpenAI GPT-5 Chat Latest",
    provider: "helicone",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex",
    name: "OpenAI: GPT-5.1 Codex",
    provider: "helicone",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o3-mini",
    name: "OpenAI o3 Mini",
    provider: "helicone",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-large-2411",
    name: "Mistral-Large",
    provider: "helicone",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Google Gemini 2.5 Flash Lite",
    provider: "helicone",
    inputPricePer1M: 0.09999999999999999,
    outputPricePer1M: 0.39999999999999997,
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-guard-4",
    name: "Meta Llama Guard 4 12B",
    provider: "helicone",
    inputPricePer1M: 0.21,
    outputPricePer1M: 0.21,
    contextWindow: 131072,
    maxOutputTokens: 1024,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-1",
    name: "Anthropic: Claude Opus 4.1",
    provider: "helicone",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-3.7-sonnet",
    name: "Anthropic: Claude 3.7 Sonnet",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex-mini",
    name: "OpenAI: GPT-5.1 Codex Mini",
    provider: "helicone",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-chat-latest",
    name: "OpenAI GPT-5.1 Chat",
    provider: "helicone",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-3-haiku-20240307",
    name: "Anthropic: Claude 3 Haiku",
    provider: "helicone",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.25,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-fast-reasoning",
    name: "xAI: Grok 4 Fast Reasoning",
    provider: "helicone",
    inputPricePer1M: 0.19999999999999998,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 2000000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4.1-nano",
    name: "OpenAI GPT-4.1 Nano",
    provider: "helicone",
    inputPricePer1M: 0.09999999999999999,
    outputPricePer1M: 0.39999999999999997,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-oss-120b",
    name: "OpenAI GPT-OSS 120b",
    provider: "helicone",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.16,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "sonar",
    name: "Perplexity Sonar",
    provider: "helicone",
    inputPricePer1M: 1,
    outputPricePer1M: 1,
    contextWindow: 127000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen2.5-coder-7b-fast",
    name: "Qwen2.5 Coder 7B fast",
    provider: "helicone",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.09,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o1",
    name: "OpenAI: o1",
    provider: "helicone",
    inputPricePer1M: 15,
    outputPricePer1M: 60,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "ernie-4.5-21b-a3b-thinking",
    name: "Baidu Ernie 4.5 21B A3B Thinking",
    provider: "helicone",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.28,
    contextWindow: 128000,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-4-scout",
    name: "Meta Llama 4 Scout 17B 16E",
    provider: "helicone",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.3,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "sonar-pro",
    name: "Perplexity Sonar Pro",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4.1",
    name: "OpenAI GPT-4.1",
    provider: "helicone",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "Anthropic: Claude Sonnet 4.5 (20250929)",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-reasoner",
    name: "DeepSeek Reasoner",
    provider: "helicone",
    inputPricePer1M: 0.56,
    outputPricePer1M: 1.68,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-reasoning",
    name: "xAI Grok 4.1 Fast Reasoning",
    provider: "helicone",
    inputPricePer1M: 0.19999999999999998,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 2000000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-3-pro-preview",
    name: "Google Gemini 3 Pro Preview",
    provider: "helicone",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-mini",
    name: "OpenAI GPT-5 Mini",
    provider: "helicone",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4.1-mini",
    name: "OpenAI GPT-4.1 Mini",
    provider: "helicone",
    inputPricePer1M: 0.39999999999999997,
    outputPricePer1M: 1.5999999999999999,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "sonar-reasoning",
    name: "Perplexity Sonar Reasoning",
    provider: "helicone",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 127000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "sonar-deep-research",
    name: "Perplexity Sonar Deep Research",
    provider: "helicone",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 127000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2-0905",
    name: "Kimi K2 (09/05)",
    provider: "helicone",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-nano",
    name: "OpenAI GPT-5 Nano",
    provider: "helicone",
    inputPricePer1M: 0.049999999999999996,
    outputPricePer1M: 0.39999999999999997,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4",
    name: "xAI Grok 4",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-235b-a22b-thinking",
    name: "Qwen3 235B A22B Thinking",
    provider: "helicone",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.9000000000000004,
    contextWindow: 262144,
    maxOutputTokens: 81920,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4",
    name: "Anthropic: Claude Opus 4",
    provider: "helicone",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-fast-non-reasoning",
    name: "xAI Grok 4 Fast Non-Reasoning",
    provider: "helicone",
    inputPricePer1M: 0.19999999999999998,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 2000000,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-4.5-opus",
    name: "Anthropic: Claude Opus 4.5",
    provider: "helicone",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-vl-235b-a22b-instruct",
    name: "Qwen3 VL 235B A22B Instruct",
    provider: "helicone",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2-0711",
    name: "Kimi K2 (07/11)",
    provider: "helicone",
    inputPricePer1M: 0.5700000000000001,
    outputPricePer1M: 2.3,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemma-3-12b-it",
    name: "Google Gemma 3 12B",
    provider: "helicone",
    inputPricePer1M: 0.049999999999999996,
    outputPricePer1M: 0.09999999999999999,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4o-mini",
    name: "OpenAI GPT-4o-mini",
    provider: "helicone",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-oss-20b",
    name: "OpenAI GPT-OSS 20b",
    provider: "helicone",
    inputPricePer1M: 0.049999999999999996,
    outputPricePer1M: 0.19999999999999998,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-3.5-sonnet-v2",
    name: "Anthropic: Claude 3.5 Sonnet v2",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-30b-a3b",
    name: "Qwen3 30B A3B",
    provider: "helicone",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.29,
    contextWindow: 41000,
    maxOutputTokens: 41000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5-codex",
    name: "OpenAI: GPT-5 Codex",
    provider: "helicone",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "helicone",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.41,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-4.5-sonnet",
    name: "Anthropic: Claude Sonnet 4.5",
    provider: "helicone",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-small",
    name: "Mistral Small 3.2",
    provider: "helicone",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.1-8b-instruct-turbo",
    name: "Meta Llama 3.1 8B Instruct Turbo",
    provider: "helicone",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.03,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1",
    name: "OpenAI GPT-5.1",
    provider: "helicone",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class HeliconeAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "helicone",
      apiKey,
      models: MODELS,
      apiBase: "https://ai-gateway.helicone.ai/v1",
    });
  }
}
