import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/Kimi-K2-Thinking",
    name: "Kimi-K2-Thinking",
    provider: "huggingface",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2-Instruct-0905",
    name: "Kimi-K2-Instruct-0905",
    provider: "huggingface",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2-Instruct",
    name: "Kimi-K2-Instruct",
    provider: "huggingface",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi-K2.6",
    provider: "huggingface",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi-K2.5",
    provider: "huggingface",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-Next",
    name: "Qwen3-Coder-Next",
    provider: "huggingface",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.5,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Embedding-8B",
    name: "Qwen 3 Embedding 8B",
    provider: "huggingface",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0,
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    name: "Qwen3-Next-80B-A3B-Instruct",
    provider: "huggingface",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1,
    contextWindow: 262144,
    maxOutputTokens: 66536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B",
    name: "Qwen3.5-397B-A17B",
    provider: "huggingface",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen3-235B-A22B-Thinking-2507",
    provider: "huggingface",
    inputPricePer1M: 0.3,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Embedding-4B",
    name: "Qwen 3 Embedding 4B",
    provider: "huggingface",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0,
    contextWindow: 32000,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen3-Coder-480B-A35B-Instruct",
    provider: "huggingface",
    inputPricePer1M: 2,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 66536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
    name: "Qwen3-Next-80B-A3B-Thinking",
    provider: "huggingface",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "XiaomiMiMo/MiMo-V2-Flash",
    name: "MiMo-V2-Flash",
    provider: "huggingface",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7-Flash",
    name: "GLM-4.7-Flash",
    provider: "huggingface",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    provider: "huggingface",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7",
    name: "GLM-4.7",
    provider: "huggingface",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1",
    name: "GLM-5.1",
    provider: "huggingface",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-0528",
    name: "DeepSeek-R1-0528",
    provider: "huggingface",
    inputPricePer1M: 3,
    outputPricePer1M: 5,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Pro",
    name: "DeepSeek V4 Pro",
    provider: "huggingface",
    inputPricePer1M: 0.435,
    outputPricePer1M: 0.87,
    contextWindow: 1048576,
    maxOutputTokens: 393216,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2",
    name: "DeepSeek-V3.2",
    provider: "huggingface",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.4,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.1",
    name: "MiniMax-M2.1",
    provider: "huggingface",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "huggingface",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.7",
    name: "MiniMax-M2.7",
    provider: "huggingface",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class HuggingfaceAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "huggingface",
      apiKey,
      models: MODELS,
      apiBase: "https://router.huggingface.co/v1",
    });
  }
}
