import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "qwen3-coder-plus",
    name: "Qwen3-Coder-Plus",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek-V3",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2",
    name: "Kimi-K2",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3-32B",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-max-preview",
    name: "Qwen3-Max-Preview",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-max",
    name: "Qwen3-Max",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-235b",
    name: "Qwen3-235B-A22B",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.6",
    name: "GLM-4.6",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-235b-a22b-thinking-2507",
    name: "Qwen3-235B-A22B-Thinking",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-plus",
    name: "Qwen3-VL-Plus",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-235b-a22b-instruct",
    name: "Qwen3-235B-A22B-Instruct",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-0905",
    name: "Kimi-K2-0905",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek-V3.2-Exp",
    provider: "iflowcn",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class IflowcnAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "iflowcn", apiKey, models: MODELS, apiBase: "https://apis.iflow.cn/v1" });
  }
}
