import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "mistral/mistral-nemo-12b-instruct",
    name: "Mistral Nemo 12B Instruct",
    provider: "inference",
    inputPricePer1M: 0.038,
    outputPricePer1M: 0.1,
    contextWindow: 16000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "google/gemma-3",
    name: "Google Gemma 3",
    provider: "inference",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.3,
    contextWindow: 125000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "osmosis/osmosis-structure-0.6b",
    name: "Osmosis Structure 0.6B",
    provider: "inference",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.5,
    contextWindow: 4000,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-embedding-4b",
    name: "Qwen 3 Embedding 4B",
    provider: "inference",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0,
    contextWindow: 32000,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen-2.5-7b-vision-instruct",
    name: "Qwen 2.5 7B Vision Instruct",
    provider: "inference",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 125000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta/llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    provider: "inference",
    inputPricePer1M: 0.025,
    outputPricePer1M: 0.025,
    contextWindow: 16000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta/llama-3.2-1b-instruct",
    name: "Llama 3.2 1B Instruct",
    provider: "inference",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.01,
    contextWindow: 16000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta/llama-3.2-11b-vision-instruct",
    name: "Llama 3.2 11B Vision Instruct",
    provider: "inference",
    inputPricePer1M: 0.055,
    outputPricePer1M: 0.055,
    contextWindow: 16000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta/llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    provider: "inference",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.02,
    contextWindow: 16000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class InferenceAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "inference", apiKey, models: MODELS, apiBase: "https://inference.net/v1" });
  }
}
