import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    name: "Llama 4 Maverick 17B 128E Instruct",
    provider: "io-net",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 430000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B Instruct",
    provider: "io-net",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.38,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-3.2-90B-Vision-Instruct",
    name: "Llama 3.2 90B Vision Instruct",
    provider: "io-net",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.4,
    contextWindow: 16000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2-Thinking",
    name: "Kimi K2 Thinking",
    provider: "io-net",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.25,
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "moonshotai/Kimi-K2-Instruct-0905",
    name: "Kimi K2 Instruct",
    provider: "io-net",
    inputPricePer1M: 0.39,
    outputPricePer1M: 1.9,
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-VL-32B-Instruct",
    name: "Qwen 2.5 VL 32B Instruct",
    provider: "io-net",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.22,
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    name: "Qwen 3 Next 80B Instruct",
    provider: "io-net",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.8,
    contextWindow: 262144,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen 3 235B Thinking",
    provider: "io-net",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS 120B",
    provider: "io-net",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.4,
    contextWindow: 131072,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT-OSS 20B",
    provider: "io-net",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.14,
    contextWindow: 64000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistralai/Devstral-Small-2505",
    name: "Devstral Small 2505",
    provider: "io-net",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.22,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistralai/Magistral-Small-2506",
    name: "Magistral Small 2506",
    provider: "io-net",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistralai/Mistral-Large-Instruct-2411",
    name: "Mistral Large Instruct 2411",
    provider: "io-net",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistralai/Mistral-Nemo-Instruct-2407",
    name: "Mistral Nemo Instruct 2407",
    provider: "io-net",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.04,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Intel/Qwen3-Coder-480B-A35B-Instruct-int4-mixed-ar",
    name: "Qwen 3 Coder 480B",
    provider: "io-net",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.95,
    contextWindow: 106000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.6",
    name: "GLM 4.6",
    provider: "io-net",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.75,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-0528",
    name: "DeepSeek R1",
    provider: "io-net",
    inputPricePer1M: 2,
    outputPricePer1M: 8.75,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class IoNetAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "io-net",
      apiKey,
      models: MODELS,
      apiBase: "https://api.intelligence.io.solutions/api/v1",
    });
  }
}
