import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "o3",
    name: "o3",
    provider: "jiekou",
    inputPricePer1M: 10,
    outputPricePer1M: 40,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-code-fast-1",
    name: "grok-code-fast-1",
    provider: "jiekou",
    inputPricePer1M: 0.18,
    outputPricePer1M: 1.35,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.2-pro",
    name: "gpt-5.2-pro",
    provider: "jiekou",
    inputPricePer1M: 18.9,
    outputPricePer1M: 151.2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-pro",
    name: "gemini-2.5-pro",
    provider: "jiekou",
    inputPricePer1M: 1.125,
    outputPricePer1M: 9,
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "claude-haiku-4-5-20251001",
    provider: "jiekou",
    inputPricePer1M: 0.9,
    outputPricePer1M: 4.5,
    contextWindow: 20000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-pro",
    name: "gpt-5-pro",
    provider: "jiekou",
    inputPricePer1M: 13.5,
    outputPricePer1M: 108,
    contextWindow: 400000,
    maxOutputTokens: 272000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash",
    name: "gemini-2.5-flash",
    provider: "jiekou",
    inputPricePer1M: 0.27,
    outputPricePer1M: 2.25,
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    provider: "jiekou",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-lite-preview-09-2025",
    name: "gemini-2.5-flash-lite-preview-09-2025",
    provider: "jiekou",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.36,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-1-20250805",
    name: "claude-opus-4-1-20250805",
    provider: "jiekou",
    inputPricePer1M: 13.5,
    outputPricePer1M: 67.5,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "grok-4-1-fast-non-reasoning",
    provider: "jiekou",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.45,
    contextWindow: 2000000,
    maxOutputTokens: 2000000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-chat-latest",
    name: "gpt-5-chat-latest",
    provider: "jiekou",
    inputPricePer1M: 1.125,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-5-20251101",
    name: "claude-opus-4-5-20251101",
    provider: "jiekou",
    inputPricePer1M: 4.5,
    outputPricePer1M: 22.5,
    contextWindow: 200000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex",
    name: "gpt-5.1-codex",
    provider: "jiekou",
    inputPricePer1M: 1.125,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex-max",
    name: "gpt-5.1-codex-max",
    provider: "jiekou",
    inputPricePer1M: 1.125,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-20250514",
    name: "claude-opus-4-20250514",
    provider: "jiekou",
    inputPricePer1M: 13.5,
    outputPricePer1M: 67.5,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "o3-mini",
    name: "o3-mini",
    provider: "jiekou",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.2",
    name: "gpt-5.2",
    provider: "jiekou",
    inputPricePer1M: 1.575,
    outputPricePer1M: 12.6,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-0709",
    name: "grok-4-0709",
    provider: "jiekou",
    inputPricePer1M: 2.7,
    outputPricePer1M: 13.5,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "gemini-2.5-flash-lite",
    provider: "jiekou",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.36,
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-20250514",
    name: "claude-sonnet-4-20250514",
    provider: "jiekou",
    inputPricePer1M: 2.7,
    outputPricePer1M: 13.5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex-mini",
    name: "gpt-5.1-codex-mini",
    provider: "jiekou",
    inputPricePer1M: 0.225,
    outputPricePer1M: 1.8,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-fast-reasoning",
    name: "grok-4-fast-reasoning",
    provider: "jiekou",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.45,
    contextWindow: 2000000,
    maxOutputTokens: 2000000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-6",
    name: "claude-opus-4-6",
    provider: "jiekou",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "claude-sonnet-4-5-20250929",
    provider: "jiekou",
    inputPricePer1M: 2.7,
    outputPricePer1M: 13.5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-reasoning",
    name: "grok-4-1-fast-reasoning",
    provider: "jiekou",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.45,
    contextWindow: 2000000,
    maxOutputTokens: 2000000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3-pro-preview",
    name: "gemini-3-pro-preview",
    provider: "jiekou",
    inputPricePer1M: 1.8,
    outputPricePer1M: 10.8,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-mini",
    name: "gpt-5-mini",
    provider: "jiekou",
    inputPricePer1M: 0.225,
    outputPricePer1M: 1.8,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-nano",
    name: "gpt-5-nano",
    provider: "jiekou",
    inputPricePer1M: 0.045,
    outputPricePer1M: 0.36,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-fast-non-reasoning",
    name: "grok-4-fast-non-reasoning",
    provider: "jiekou",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.45,
    contextWindow: 2000000,
    maxOutputTokens: 2000000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3-flash-preview",
    name: "gemini-3-flash-preview",
    provider: "jiekou",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-preview-05-20",
    name: "gemini-2.5-flash-preview-05-20",
    provider: "jiekou",
    inputPricePer1M: 0.135,
    outputPricePer1M: 3.15,
    contextWindow: 1048576,
    maxOutputTokens: 200000,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash-lite-preview-06-17",
    name: "gemini-2.5-flash-lite-preview-06-17",
    provider: "jiekou",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.36,
    contextWindow: 1048576,
    maxOutputTokens: 65535,
    inputModalities: ["text", "video", "image", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-pro-preview-06-05",
    name: "gemini-2.5-pro-preview-06-05",
    provider: "jiekou",
    inputPricePer1M: 1.125,
    outputPricePer1M: 9,
    contextWindow: 1048576,
    maxOutputTokens: 200000,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-codex",
    name: "gpt-5-codex",
    provider: "jiekou",
    inputPricePer1M: 1.125,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.2-codex",
    name: "gpt-5.2-codex",
    provider: "jiekou",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1",
    name: "gpt-5.1",
    provider: "jiekou",
    inputPricePer1M: 1.125,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "moonshotai/kimi-k2-instruct",
    name: "Kimi K2 Instruct",
    provider: "jiekou",
    inputPricePer1M: 0.57,
    outputPricePer1M: 2.3,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "jiekou",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2-0905",
    name: "Kimi K2 0905",
    provider: "jiekou",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimaxai/minimax-m1-80k",
    name: "MiniMax M1",
    provider: "jiekou",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.2,
    contextWindow: 1000000,
    maxOutputTokens: 40000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-vl-424b-a47b",
    name: "ERNIE 4.5 VL 424B A47B",
    provider: "jiekou",
    inputPricePer1M: 0.42,
    outputPricePer1M: 1.25,
    contextWindow: 123000,
    maxOutputTokens: 16000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-300b-a47b-paddle",
    name: "ERNIE 4.5 300B A47B",
    provider: "jiekou",
    inputPricePer1M: 0.28,
    outputPricePer1M: 1.1,
    contextWindow: 123000,
    maxOutputTokens: 12000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "xiaomimimo/mimo-v2-flash",
    name: "XiaomiMiMo/MiMo-V2-Flash",
    provider: "jiekou",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.7",
    name: "GLM-4.7",
    provider: "jiekou",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.5v",
    name: "GLM 4.5V",
    provider: "jiekou",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.8,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.5",
    name: "GLM-4.5",
    provider: "jiekou",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "jiekou",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.4,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-235b-a22b-instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    provider: "jiekou",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.8,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct",
    name: "Qwen3 Next 80B A3B Instruct",
    provider: "jiekou",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.5,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-next-80b-a3b-thinking",
    name: "Qwen3 Next 80B A3B Thinking",
    provider: "jiekou",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.5,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-235b-a22b-thinking-2507",
    name: "Qwen3 235B A22b Thinking 2507",
    provider: "jiekou",
    inputPricePer1M: 0.3,
    outputPricePer1M: 3,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-32b-fp8",
    name: "Qwen3 32B",
    provider: "jiekou",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.45,
    contextWindow: 40960,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-30b-a3b-fp8",
    name: "Qwen3 30B A3B",
    provider: "jiekou",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.45,
    contextWindow: 40960,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-coder-next",
    name: "qwen/qwen3-coder-next",
    provider: "jiekou",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.5,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-coder-480b-a35b-instruct",
    name: "Qwen3 Coder 480B A35B Instruct",
    provider: "jiekou",
    inputPricePer1M: 0.29,
    outputPricePer1M: 1.2,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-235b-a22b-fp8",
    name: "Qwen3 235B A22B",
    provider: "jiekou",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 40960,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-r1-0528",
    name: "DeepSeek R1 0528",
    provider: "jiekou",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.5,
    contextWindow: 163840,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3-0324",
    name: "DeepSeek V3 0324",
    provider: "jiekou",
    inputPricePer1M: 0.28,
    outputPricePer1M: 1.14,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3.1",
    name: "DeepSeek V3.1",
    provider: "jiekou",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 163840,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax/minimax-m2.1",
    name: "Minimax M2.1",
    provider: "jiekou",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class JiekouAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "jiekou", apiKey, models: MODELS, apiBase: "https://api.jiekou.ai/openai" });
  }
}
