import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "llama-4-scout-17b-16e-instruct-fp8",
    name: "Llama-4-Scout-17B-16E-Instruct-FP8",
    provider: "llama",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "cerebras-llama-4-maverick-17b-128e-instruct",
    name: "Cerebras-Llama-4-Maverick-17B-128E-Instruct",
    provider: "llama",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama-3.3-70B-Instruct",
    provider: "llama",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "groq-llama-4-maverick-17b-128e-instruct",
    name: "Groq-Llama-4-Maverick-17B-128E-Instruct",
    provider: "llama",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "cerebras-llama-4-scout-17b-16e-instruct",
    name: "Cerebras-Llama-4-Scout-17B-16E-Instruct",
    provider: "llama",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.3-8b-instruct",
    name: "Llama-3.3-8B-Instruct",
    provider: "llama",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-4-maverick-17b-128e-instruct-fp8",
    name: "Llama-4-Maverick-17B-128E-Instruct-FP8",
    provider: "llama",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class LlamaAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "llama", apiKey, models: MODELS, apiBase: "https://api.llama.com/compat/v1/" });
  }
}
