import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-coder-plus",
    name: "Qwen Coder Plus",
    provider: "llmgateway",
    inputPricePer1M: 0.502,
    outputPricePer1M: 1.004,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mistral-large-latest",
    name: "Mistral Large (latest)",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-235b-a22b-thinking",
    name: "Qwen3 VL 235B A22B Thinking",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-r1-0528",
    name: "DeepSeek R1 (0528)",
    provider: "llmgateway",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 64000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "devstral-small-2507",
    name: "Devstral Small",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-30b-a3b-thinking",
    name: "Qwen3 VL 30B A3B Thinking",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "llmgateway",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen25-coder-7b",
    name: "Qwen2.5 Coder 7B",
    provider: "llmgateway",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.05,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax-m2.7-highspeed",
    name: "MiniMax-M2.7-highspeed",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.22,
    contextWindow: 128000,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen-plus",
    name: "Qwen Plus",
    provider: "llmgateway",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.2,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o3",
    name: "o3",
    provider: "llmgateway",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "nemotron-3-ultra-550b",
    name: "Nemotron 3 Ultra 550B A55B",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax-M2.5",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "grok-4-20-beta-0309-non-reasoning",
    name: "Grok 4.20 (Non-Reasoning)",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "glm-4.7",
    name: "GLM-4.7",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "llmgateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    name: "Qwen3 235B A22B Instruct (2507)",
    provider: "llmgateway",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.58,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "llama-3-70b-instruct",
    name: "Llama 3 70B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.51,
    outputPricePer1M: 0.74,
    contextWindow: 8192,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3-Coder 30B-A3B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.25,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "seed-1-8-251228",
    name: "Seed 1.8 (251228)",
    provider: "llmgateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hermes-2-pro-llama-3-8b",
    name: "Hermes 2 Pro Llama 3 8B",
    provider: "llmgateway",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.14,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2",
    name: "Kimi K2",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "llama-3.1-70b-instruct",
    name: "Llama 3.1 70B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.72,
    outputPricePer1M: 0.72,
    contextWindow: 128000,
    maxOutputTokens: 2048,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.2-pro",
    name: "GPT-5.2 Pro",
    provider: "llmgateway",
    inputPricePer1M: 21,
    outputPricePer1M: 168,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax-m2.1",
    name: "MiniMax-M2.1",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    provider: "llmgateway",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.8,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "pixtral-large-latest",
    name: "Pixtral Large (latest)",
    provider: "llmgateway",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4-32b-0414-128k",
    name: "GLM-4 32B (0414-128k)",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "seed-1-6-flash-250715",
    name: "Seed 1.6 Flash (250715)",
    provider: "llmgateway",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.3,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-next-80b-a3b-instruct",
    name: "Qwen3-Next 80B-A3B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-8b-instruct",
    name: "Qwen3 VL 8B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.5,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-4o-mini-search-preview",
    name: "GPT-4o Mini Search Preview",
    provider: "llmgateway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5v",
    name: "GLM-4.5V",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.8,
    contextWindow: 64000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    provider: "llmgateway",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2-thinking-turbo",
    name: "Kimi K2 Thinking Turbo",
    provider: "llmgateway",
    inputPricePer1M: 1.15,
    outputPricePer1M: 8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.6-35b-a3b",
    name: "Qwen3.6 35B-A3B",
    provider: "llmgateway",
    inputPricePer1M: 0.248,
    outputPricePer1M: 1.485,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-3.5-turbo",
    name: "GPT-3.5-turbo",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 16385,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "seed-1-6-250615",
    name: "Seed 1.6 (250615)",
    provider: "llmgateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "llmgateway",
    inputPricePer1M: 2.5,
    outputPricePer1M: 7.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5",
    name: "GLM-4.5",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5-pro",
    name: "GPT-5 Pro",
    provider: "llmgateway",
    inputPricePer1M: 15,
    outputPricePer1M: 120,
    contextWindow: 400000,
    maxOutputTokens: 272000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "llmgateway",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "ministral-8b-2512",
    name: "Ministral 8B",
    provider: "llmgateway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.15,
    contextWindow: 262144,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-4",
    name: "GPT-4",
    provider: "llmgateway",
    inputPricePer1M: 30,
    outputPricePer1M: 60,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    provider: "llmgateway",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    provider: "llmgateway",
    inputPricePer1M: 1.2,
    outputPricePer1M: 6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-small-2506",
    name: "Mistral Small 3.2",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    provider: "llmgateway",
    inputPricePer1M: 1.5,
    outputPricePer1M: 9,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen-plus-latest",
    name: "Qwen Plus Latest",
    provider: "llmgateway",
    inputPricePer1M: 0.115,
    outputPricePer1M: 0.287,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-1-20250805",
    name: "Claude Opus 4.1",
    provider: "llmgateway",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    provider: "llmgateway",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.38,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "grok-4-3",
    name: "Grok 4.3",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "llama-4-scout-17b-instruct",
    name: "Llama 4 Scout 17B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.66,
    contextWindow: 8192,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama-3.3-70B-Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "sonar-reasoning-pro",
    name: "Sonar Reasoning Pro",
    provider: "llmgateway",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-20-non-reasoning",
    name: "Grok 4.20 (Non-Reasoning)",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "glm-4.7-flashx",
    name: "GLM-4.7-FlashX",
    provider: "llmgateway",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-30b-a3b-instruct-2507",
    name: "Qwen3 30B A3B Instruct (2507)",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "llmgateway",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    provider: "llmgateway",
    inputPricePer1M: 6,
    outputPricePer1M: 24,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "llmgateway",
    inputPricePer1M: 0.435,
    outputPricePer1M: 0.87,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-next-80b-a3b-thinking",
    name: "Qwen3-Next 80B-A3B (Thinking)",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 6,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.6",
    name: "GLM-4.6",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen35-397b-a17b",
    name: "Qwen3.5 397B-A17B",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-235b-a22b-thinking-2507",
    name: "Qwen3 235B A22B Thinking (2507)",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5 (latest)",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-pro-latest",
    name: "Gemini Pro Latest",
    provider: "llmgateway",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemma-3-1b-it",
    name: "Gemma 3 1B IT",
    provider: "llmgateway",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.3,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.5-x",
    name: "GLM-4.5 X",
    provider: "llmgateway",
    inputPricePer1M: 2.2,
    outputPricePer1M: 8.9,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "llmgateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 nano",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.25,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-20-beta-0309-reasoning",
    name: "Grok 4.20 (Reasoning)",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "glm-5.2",
    name: "GLM-5.2",
    provider: "llmgateway",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-4.5-airx",
    name: "GLM-4.5 AirX",
    provider: "llmgateway",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.5,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-chat-latest",
    name: "GPT-5 Chat (latest)",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "ministral-3b-2512",
    name: "Ministral 3B",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen2-5-vl-72b-instruct",
    name: "Qwen2.5-VL 72B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 2.8,
    outputPricePer1M: 8.4,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.6v-flashx",
    name: "GLM-4.6V FlashX",
    provider: "llmgateway",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.4,
    contextWindow: 128000,
    maxOutputTokens: 16000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-m3",
    name: "MiniMax-M3",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 512000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-plus",
    name: "Qwen3-VL Plus",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.6,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-5-20251101",
    name: "Claude Opus 4.5",
    provider: "llmgateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex",
    name: "GPT-5.1 Codex",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-m2",
    name: "MiniMax-M2",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 196608,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-3-5-sonnet-20241022",
    name: "Claude Sonnet 3.5 v2",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "llmgateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-20250514",
    name: "Claude Opus 4",
    provider: "llmgateway",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-max-2026-01-23",
    name: "Qwen3 Max (2026-01-23)",
    provider: "llmgateway",
    inputPricePer1M: 0.359,
    outputPricePer1M: 1.434,
    contextWindow: 256000,
    maxOutputTokens: 32800,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.3-chat-latest",
    name: "GPT-5.3 Chat (latest)",
    provider: "llmgateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    provider: "llmgateway",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-omni-turbo",
    name: "Qwen-Omni Turbo",
    provider: "llmgateway",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.27,
    contextWindow: 32768,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o3-mini",
    name: "o3-mini",
    provider: "llmgateway",
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-32b-fp8",
    name: "Qwen3 32B FP8",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "llmgateway",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.2",
    name: "GPT-5.2",
    provider: "llmgateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemma-3-27b",
    name: "Gemma 3 27B",
    provider: "llmgateway",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.27,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "llmgateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-0709",
    name: "Grok 4 (0709)",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-m2.7",
    name: "MiniMax-M2.7",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-flash",
    name: "Qwen Flash",
    provider: "llmgateway",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.4,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-4b-fp8",
    name: "Qwen3 4B FP8",
    provider: "llmgateway",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.03,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen2-5-vl-32b-instruct",
    name: "Qwen2.5 VL 32B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.2,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-20250514",
    name: "Claude Sonnet 4",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.1-codex-mini",
    name: "GPT-5.1 Codex mini",
    provider: "llmgateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-30b-a3b-thinking-2507",
    name: "Qwen3 30B A3B Thinking (2507)",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "seed-1-6-250915",
    name: "Seed 1.6 (250915)",
    provider: "llmgateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-5.2-chat-latest",
    name: "GPT-5.2 Chat",
    provider: "llmgateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-text-01",
    name: "MiniMax Text 01",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.1,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "grok-4-fast-reasoning",
    name: "Grok 4 Fast Reasoning",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 nano",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "llmgateway",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.25,
    contextWindow: 131072,
    maxOutputTokens: 32766,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen-vl-max",
    name: "Qwen-VL Max",
    provider: "llmgateway",
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.2,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-3-8b-instruct",
    name: "Llama 3 8B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.04,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-30b-a3b-fp8",
    name: "Qwen3 30B A3B FP8",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "sonar",
    name: "Sonar",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 1,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-max",
    name: "Qwen Max",
    provider: "llmgateway",
    inputPricePer1M: 1.6,
    outputPricePer1M: 6.4,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-3-7-sonnet-20250219",
    name: "Claude Sonnet 3.7",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "o1",
    name: "o1",
    provider: "llmgateway",
    inputPricePer1M: 15,
    outputPricePer1M: 60,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-m2.5-highspeed",
    name: "MiniMax-M2.5-highspeed",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v3.1",
    name: "DeepSeek V3.1",
    provider: "llmgateway",
    inputPricePer1M: 0.56,
    outputPricePer1M: 1.68,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    provider: "llmgateway",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.59,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "ministral-14b-2512",
    name: "Ministral 14B",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 262144,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "sonar-pro",
    name: "Sonar Pro",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.6v",
    name: "GLM-4.6V",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5 (latest)",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax-m2.1-lightning",
    name: "MiniMax M2.1 Lightning",
    provider: "llmgateway",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.48,
    contextWindow: 196608,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    provider: "llmgateway",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mimo-v2.5",
    name: "MiMo-V2.5",
    provider: "llmgateway",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2-omni",
    name: "MiMo-V2-Omni",
    provider: "llmgateway",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 mini",
    provider: "llmgateway",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "llmgateway",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "llmgateway",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "llmgateway",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "llmgateway",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-next",
    name: "Qwen3 Coder Next",
    provider: "llmgateway",
    inputPricePer1M: 0.108,
    outputPricePer1M: 0.675,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "llama-4-maverick-17b-instruct",
    name: "Llama 4 Maverick 17B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.97,
    contextWindow: 8192,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "Qwen3-Coder 480B-A35B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 1.5,
    outputPricePer1M: 7.5,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "devstral-2512",
    name: "Devstral 2",
    provider: "llmgateway",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemma-4-26b-a4b-it",
    name: "Gemma 4 26B A4B IT",
    provider: "llmgateway",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.34,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5 9B",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.15,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwq-plus",
    name: "QwQ Plus",
    provider: "llmgateway",
    inputPricePer1M: 0.8,
    outputPricePer1M: 2.4,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4-1-fast-reasoning",
    name: "Grok 4.1 Fast Reasoning",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-vl-30b-a3b-instruct",
    name: "Qwen3 VL 30B A3B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.7,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-vl-flash",
    name: "Qwen3 VL Flash",
    provider: "llmgateway",
    inputPricePer1M: 0.022,
    outputPricePer1M: 0.215,
    contextWindow: 1000000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "llmgateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mimo-v2-flash",
    name: "MiMo-V2-Flash",
    provider: "llmgateway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 mini",
    provider: "llmgateway",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "llama-3.1-nemotron-ultra-253b",
    name: "Llama 3.1 Nemotron Ultra 253B",
    provider: "llmgateway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.8,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "llmgateway",
    inputPricePer1M: 10,
    outputPricePer1M: 30,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemma-2-27b-it-together",
    name: "Gemma 2 27B IT",
    provider: "llmgateway",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.08,
    contextWindow: 8192,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "grok-build-0-1",
    name: "Grok Build 0.1",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano",
    provider: "llmgateway",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.4,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "llama-3.2-11b-instruct",
    name: "Llama 3.2 11B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.33,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-5.4-pro",
    name: "GPT-5.4 Pro",
    provider: "llmgateway",
    inputPricePer1M: 30,
    outputPricePer1M: 180,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.6v-flash",
    name: "GLM-4.6V Flash",
    provider: "llmgateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-4.5-air",
    name: "GLM-4.5-Air",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.1,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.7-code-highspeed",
    name: "Kimi K2.7 Code Highspeed",
    provider: "llmgateway",
    inputPricePer1M: 1.9,
    outputPricePer1M: 8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "llmgateway",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "llmgateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-vl-235b-a22b-instruct",
    name: "Qwen3 VL 235B A22B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.5,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mimo-v2-pro",
    name: "MiMo-V2-Pro",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-4o-search-preview",
    name: "GPT-4o Search Preview",
    provider: "llmgateway",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    provider: "llmgateway",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.05,
    contextWindow: 32768,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo-V2.5-Pro",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-5.5-pro",
    name: "GPT-5.5 Pro",
    provider: "llmgateway",
    inputPricePer1M: 30,
    outputPricePer1M: 180,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    provider: "llmgateway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "llmgateway",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.15,
    contextWindow: 131072,
    maxOutputTokens: 32766,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "glm-4.5-flash",
    name: "GLM-4.5-Flash",
    provider: "llmgateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "llmgateway",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-max-latest",
    name: "Qwen Max Latest",
    provider: "llmgateway",
    inputPricePer1M: 0.345,
    outputPricePer1M: 1.377,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mistral-large-2512",
    name: "Mistral Large 3",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    provider: "llmgateway",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.2,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "custom",
    name: "Custom Model",
    provider: "llmgateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-20-reasoning",
    name: "Grok 4.20 (Reasoning)",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "llmgateway",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.42,
    contextWindow: 163840,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.6-max-preview",
    name: "Qwen3.6 Max Preview",
    provider: "llmgateway",
    inputPricePer1M: 1.3,
    outputPricePer1M: 7.8,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "auto",
    name: "Auto Route",
    provider: "llmgateway",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    provider: "llmgateway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "codestral-2508",
    name: "Codestral",
    provider: "llmgateway",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-235b-a22b-fp8",
    name: "Qwen3 235B A22B FP8",
    provider: "llmgateway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-5.2-codex",
    name: "GPT-5.2 Codex",
    provider: "llmgateway",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen-vl-plus",
    name: "Qwen-VL Plus",
    provider: "llmgateway",
    inputPricePer1M: 0.21,
    outputPricePer1M: 0.63,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    provider: "llmgateway",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash-Lite",
    provider: "llmgateway",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.1",
    name: "GPT-5.1",
    provider: "llmgateway",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    provider: "llmgateway",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class LlmgatewayAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "llmgateway", apiKey, models: MODELS, apiBase: "https://api.llmgateway.io/v1" });
  }
}
