import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "sincap",
    name: "Sincap",
    provider: "llmtr",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "magibu-11b-v8",
    name: "Magibu 11B v8",
    provider: "llmtr",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gemma-4",
    name: "Gemma 4",
    provider: "llmtr",
    inputPricePer1M: 5,
    outputPricePer1M: 10,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "medgemma-4b",
    name: "MedGemma 4B",
    provider: "llmtr",
    inputPricePer1M: 3,
    outputPricePer1M: 5,
    contextWindow: 8192,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-6-35b",
    name: "Qwen3.6 35B-A3B",
    provider: "llmtr",
    inputPricePer1M: 5,
    outputPricePer1M: 10,
    contextWindow: 16384,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "trendyol-7b",
    name: "Trendyol 7B",
    provider: "llmtr",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
];

export class LlmtrAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "llmtr", apiKey, models: MODELS, apiBase: "https://llmtr.com/v1" });
  }
}
