import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "MiniMax-M2.1",
    name: "MiniMax-M2.1",
    provider: "minimax",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMax-M2.5-highspeed",
    name: "MiniMax-M2.5-highspeed",
    provider: "minimax",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMax-M2.7-highspeed",
    name: "MiniMax-M2.7-highspeed",
    provider: "minimax",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMax-M2",
    name: "MiniMax-M2",
    provider: "minimax",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 196608,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "minimax",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMax-M3",
    name: "MiniMax-M3",
    provider: "minimax",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 512000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMax-M2.7",
    name: "MiniMax-M2.7",
    provider: "minimax",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class MinimaxAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "minimax",
      apiKey,
      models: MODELS,
      apiBase: "https://api.minimax.io/anthropic/v1",
    });
  }
}
