import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "kimi-k2.7-code-highspeed",
    name: "Kimi K2.7 Code HighSpeed",
    provider: "moonshotai-cn",
    inputPricePer1M: 1.9,
    outputPricePer1M: 8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "moonshotai-cn",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "moonshotai-cn",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2-turbo-preview",
    name: "Kimi K2 Turbo",
    provider: "moonshotai-cn",
    inputPricePer1M: 2.4,
    outputPricePer1M: 10,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-0711-preview",
    name: "Kimi K2 0711",
    provider: "moonshotai-cn",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "moonshotai-cn",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "moonshotai-cn",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2-thinking-turbo",
    name: "Kimi K2 Thinking Turbo",
    provider: "moonshotai-cn",
    inputPricePer1M: 1.15,
    outputPricePer1M: 8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-0905-preview",
    name: "Kimi K2 0905",
    provider: "moonshotai-cn",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class MoonshotaiCnAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "moonshotai-cn", apiKey, models: MODELS, apiBase: "https://api.moonshot.cn/v1" });
  }
}
