import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama-3.3-70B-Instruct",
    provider: "nebius",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.4,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5-fast",
    name: "Kimi-K2.5-fast",
    provider: "nebius",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.5,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi-K2.5",
    provider: "nebius",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.5,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-3-27b-it",
    name: "Gemma-3-27b-it",
    provider: "nebius",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 110000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Thinking-fast",
    name: "Qwen3-Next-80B-A3B-Thinking-fast",
    provider: "nebius",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.2,
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen2.5-VL-72B-Instruct",
    name: "Qwen2.5-VL-72B-Instruct",
    provider: "nebius",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.75,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Embedding-8B",
    name: "Qwen3-Embedding-8B",
    provider: "nebius",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B",
    name: "Qwen3.5-397B-A17B",
    provider: "nebius",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B-fast",
    name: "Qwen3.5-397B-A17B-fast",
    provider: "nebius",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Instruct-2507",
    name: "Qwen3-30B-A3B-Instruct-2507",
    provider: "nebius",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
    name: "Qwen3-Next-80B-A3B-Thinking",
    provider: "nebius",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.2,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    provider: "nebius",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-32B",
    name: "Qwen3-32B",
    provider: "nebius",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507-fast",
    name: "Qwen3-235B-A22B-Thinking-2507-fast",
    provider: "nebius",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b-fast",
    name: "gpt-oss-120b-fast",
    provider: "nebius",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.5,
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "gpt-oss-120b",
    provider: "nebius",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "NousResearch/Hermes-4-405B",
    name: "Hermes-4-405B",
    provider: "nebius",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "NousResearch/Hermes-4-70B",
    name: "Hermes-4-70B",
    provider: "nebius",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.4,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B",
    name: "Nemotron-3-Nano-30B-A3B",
    provider: "nebius",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia/Nemotron-3-Nano-Omni",
    name: "Nemotron-3-Nano-Omni",
    provider: "nebius",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    contextWindow: 65536,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia/Llama-3_1-Nemotron-Ultra-253B-v1",
    name: "Llama-3.1-Nemotron-Ultra-253B-v1",
    provider: "nebius",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.8,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia/nemotron-3-super-120b-a12b",
    name: "Nemotron-3-Super-120B-A12B",
    provider: "nebius",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 256000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    provider: "nebius",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2-fast",
    name: "DeepSeek-V3.2-fast",
    provider: "nebius",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Pro",
    name: "DeepSeek V4 Pro",
    provider: "nebius",
    inputPricePer1M: 1.75,
    outputPricePer1M: 3.5,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2",
    name: "DeepSeek-V3.2",
    provider: "nebius",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.45,
    contextWindow: 163000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "nebius",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 196608,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5-fast",
    name: "MiniMax-M2.5-fast",
    provider: "nebius",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "PrimeIntellect/INTELLECT-3",
    name: "INTELLECT-3",
    provider: "nebius",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.1,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class NebiusAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "nebius",
      apiKey,
      models: MODELS,
      apiBase: "https://api.tokenfactory.nebius.com/v1",
    });
  }
}
