import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "kimi-k2.5-fast",
    name: "Kimi K2.5 Fast",
    provider: "neuralwatt",
    inputPricePer1M: 0.52,
    outputPricePer1M: 2.59,
    contextWindow: 262128,
    maxOutputTokens: 262128,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5-fast",
    name: "GLM 5 Fast",
    provider: "neuralwatt",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3.6,
    contextWindow: 202736,
    maxOutputTokens: 202736,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5.2",
    name: "GLM 5.2",
    provider: "neuralwatt",
    inputPricePer1M: 1.45,
    outputPricePer1M: 4.5,
    contextWindow: 1048560,
    maxOutputTokens: 1048560,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.5-397b-fast",
    name: "Qwen3.5 397B Fast",
    provider: "neuralwatt",
    inputPricePer1M: 0.69,
    outputPricePer1M: 4.14,
    contextWindow: 262128,
    maxOutputTokens: 262128,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5.1-fast",
    name: "GLM 5.1 Fast",
    provider: "neuralwatt",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3.6,
    contextWindow: 202736,
    maxOutputTokens: 202736,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.6-fast",
    name: "Kimi K2.6 Fast",
    provider: "neuralwatt",
    inputPricePer1M: 0.69,
    outputPricePer1M: 3.22,
    contextWindow: 262128,
    maxOutputTokens: 262128,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.6-35b-fast",
    name: "Qwen3.6 35B Fast",
    provider: "neuralwatt",
    inputPricePer1M: 0.29,
    outputPricePer1M: 1.15,
    contextWindow: 131056,
    maxOutputTokens: 131056,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "neuralwatt",
    inputPricePer1M: 0.69,
    outputPricePer1M: 3.22,
    contextWindow: 262128,
    maxOutputTokens: 262128,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    provider: "neuralwatt",
    inputPricePer1M: 0.52,
    outputPricePer1M: 2.59,
    contextWindow: 262128,
    maxOutputTokens: 262128,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.7-Code",
    name: "Kimi K2.7 Code",
    provider: "neuralwatt",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.6-35B-A3B",
    name: "Qwen3.6 35B A3B",
    provider: "neuralwatt",
    inputPricePer1M: 0.29,
    outputPricePer1M: 1.15,
    contextWindow: 131056,
    maxOutputTokens: 131056,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B-FP8",
    name: "Qwen3.5 397B A17B FP8",
    provider: "neuralwatt",
    inputPricePer1M: 0.69,
    outputPricePer1M: 4.14,
    contextWindow: 262128,
    maxOutputTokens: 262128,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1-FP8",
    name: "GLM 5.1 FP8",
    provider: "neuralwatt",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3.6,
    contextWindow: 202736,
    maxOutputTokens: 202736,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class NeuralwattAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "neuralwatt", apiKey, models: MODELS, apiBase: "https://api.neuralwatt.com/v1" });
  }
}
