import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "inclusionai/ling-2.6-1t",
    name: "Ling-2.6-1T",
    provider: "novita-ai",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "inclusionai/ring-2.6-1t",
    name: "Ring-2.6-1T",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "inclusionai/ling-2.6-flash",
    name: "Ling-2.6-flash",
    provider: "novita-ai",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "meta-llama/llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.05,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-3-70b-instruct",
    name: "Llama3 70B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.51,
    outputPricePer1M: 0.74,
    contextWindow: 8192,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "meta-llama/llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.59,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.135,
    outputPricePer1M: 0.4,
    contextWindow: 131072,
    maxOutputTokens: 120000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-3-8b-instruct",
    name: "Llama 3 8B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.04,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.05,
    contextWindow: 32768,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/llama-4-maverick-17b-128e-instruct-fp8",
    name: "Llama 4 Maverick Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.85,
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2-instruct",
    name: "Kimi K2 Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.57,
    outputPricePer1M: 2.3,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    provider: "novita-ai",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2-0905",
    name: "Kimi K2 0905",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimaxai/minimax-m1-80k",
    name: "MiniMax M1",
    provider: "novita-ai",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.2,
    contextWindow: 1000000,
    maxOutputTokens: 40000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-vl-28b-a3b",
    name: "ERNIE 4.5 VL 28B A3B",
    provider: "novita-ai",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.56,
    contextWindow: 30000,
    maxOutputTokens: 8000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-21B-a3b",
    name: "ERNIE 4.5 21B A3B",
    provider: "novita-ai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.28,
    contextWindow: 120000,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-vl-424b-a47b",
    name: "ERNIE 4.5 VL 424B A47B",
    provider: "novita-ai",
    inputPricePer1M: 0.42,
    outputPricePer1M: 1.25,
    contextWindow: 123000,
    maxOutputTokens: 16000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-21B-a3b-thinking",
    name: "ERNIE-4.5-21B-A3B-Thinking",
    provider: "novita-ai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.28,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-300b-a47b-paddle",
    name: "ERNIE 4.5 300B A47B",
    provider: "novita-ai",
    inputPricePer1M: 0.28,
    outputPricePer1M: 1.1,
    contextWindow: 123000,
    maxOutputTokens: 12000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "baidu/ernie-4.5-vl-28b-a3b-thinking",
    name: "ERNIE-4.5-VL-28B-A3B-Thinking",
    provider: "novita-ai",
    inputPricePer1M: 0.39,
    outputPricePer1M: 0.39,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-4-31b-it",
    name: "Gemma 4 31B",
    provider: "novita-ai",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.4,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-4-26b-a4b-it",
    name: "Gemma 4 26B A4B",
    provider: "novita-ai",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.4,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-3-12b-it",
    name: "Gemma 3 12B",
    provider: "novita-ai",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.1,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "google/gemma-3-27b-it",
    name: "Gemma 3 27B",
    provider: "novita-ai",
    inputPricePer1M: 0.119,
    outputPricePer1M: 0.2,
    contextWindow: 98304,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "microsoft/wizardlm-2-8x22b",
    name: "Wizardlm 2 8x22B",
    provider: "novita-ai",
    inputPricePer1M: 0.62,
    outputPricePer1M: 0.62,
    contextWindow: 65535,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "OpenAI GPT OSS 120B",
    provider: "novita-ai",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.25,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "OpenAI: GPT OSS 20B",
    provider: "novita-ai",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.15,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "sao10K/l31-70b-euryale-v2.2",
    name: "L31 70B Euryale V2.2",
    provider: "novita-ai",
    inputPricePer1M: 1.48,
    outputPricePer1M: 1.48,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "sao10K/L3-8B-stheno-v3.2",
    name: "L3 8B Stheno V3.2",
    provider: "novita-ai",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.05,
    contextWindow: 8192,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "sao10K/l3-8b-lunaris",
    name: "Sao10k L3 8B Lunaris\t",
    provider: "novita-ai",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.05,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "sao10K/l3-70b-euryale-v2.1",
    name: "L3 70B Euryale V2.1\t",
    provider: "novita-ai",
    inputPricePer1M: 1.48,
    outputPricePer1M: 1.48,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "baichuan/baichuan-m2-32b",
    name: "baichuan-m2-32b",
    provider: "novita-ai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.07,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistralai/mistral-nemo",
    name: "Mistral Nemo",
    provider: "novita-ai",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.17,
    contextWindow: 60288,
    maxOutputTokens: 16000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "xiaomimimo/mimo-v2-flash",
    name: "XiaomiMiMo/MiMo-V2-Flash",
    provider: "novita-ai",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "xiaomimimo/mimo-v2-pro",
    name: "MiMo-V2-Pro",
    provider: "novita-ai",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "xiaomimimo/mimo-v2.5-pro",
    name: "MiMo-V2.5-Pro",
    provider: "novita-ai",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gryphe/mythomax-l2-13b",
    name: "Mythomax L2 13B",
    provider: "novita-ai",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.09,
    contextWindow: 4096,
    maxOutputTokens: 3200,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.7",
    name: "GLM-4.7",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.5v",
    name: "GLM 4.5V",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.8,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "video", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.5",
    name: "GLM-4.5",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/autoglm-phone-9b-multilingual",
    name: "AutoGLM-Phone-9B-Multilingual",
    provider: "novita-ai",
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.138,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/glm-5.1",
    name: "GLM-5.1",
    provider: "novita-ai",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.6",
    name: "GLM 4.6",
    provider: "novita-ai",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.6v",
    name: "GLM 4.6V",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "video", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.5-air",
    name: "GLM 4.5 Air",
    provider: "novita-ai",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.85,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "novita-ai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.4,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/glm-5",
    name: "GLM-5",
    provider: "novita-ai",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "paddlepaddle/paddleocr-vl",
    name: "PaddleOCR-VL",
    provider: "novita-ai",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.02,
    contextWindow: 16384,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-vl-235b-a22b-thinking",
    name: "Qwen3 VL 235B A22B Thinking",
    provider: "novita-ai",
    inputPricePer1M: 0.98,
    outputPricePer1M: 3.95,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-vl-30b-a3b-thinking",
    name: "qwen/qwen3-vl-30b-a3b-thinking",
    provider: "novita-ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-235b-a22b-instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    provider: "novita-ai",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.58,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-coder-30b-a3b-instruct",
    name: "Qwen3 Coder 30b A3B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.27,
    contextWindow: 160000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-8b-fp8",
    name: "Qwen3 8B",
    provider: "novita-ai",
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.138,
    contextWindow: 128000,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-next-80b-a3b-instruct",
    name: "Qwen3 Next 80B A3B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.5,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-vl-8b-instruct",
    name: "qwen/qwen3-vl-8b-instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.5,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-omni-30b-a3b-thinking",
    name: "Qwen3 Omni 30B A3B Thinking",
    provider: "novita-ai",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.97,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "audio", "video", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3.7-max",
    name: "Qwen3.7-Max",
    provider: "novita-ai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 3.75,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen/qwen3-max",
    name: "Qwen3 Max",
    provider: "novita-ai",
    inputPricePer1M: 2.11,
    outputPricePer1M: 8.45,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen/qwen2.5-7b-instruct",
    name: "Qwen2.5 7B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.07,
    contextWindow: 32000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-next-80b-a3b-thinking",
    name: "Qwen3 Next 80B A3B Thinking",
    provider: "novita-ai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1.5,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-235b-a22b-thinking-2507",
    name: "Qwen3 235B A22b Thinking 2507",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 3,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen-mt-plus",
    name: "Qwen MT Plus",
    provider: "novita-ai",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.75,
    contextWindow: 16384,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-32b-fp8",
    name: "Qwen3 32B",
    provider: "novita-ai",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.45,
    contextWindow: 40960,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-4b-fp8",
    name: "Qwen3 4B",
    provider: "novita-ai",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.03,
    contextWindow: 128000,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen2.5-vl-72b-instruct",
    name: "Qwen2.5 VL 72B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.8,
    outputPricePer1M: 0.8,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3-30b-a3b-fp8",
    name: "Qwen3 30B A3B",
    provider: "novita-ai",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.45,
    contextWindow: 40960,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen/qwen3.5-27b",
    name: "Qwen3.5-27B",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.4,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen-2.5-72b-instruct",
    name: "Qwen 2.5 72B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.38,
    outputPricePer1M: 0.4,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-coder-next",
    name: "Qwen3 Coder Next",
    provider: "novita-ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.5,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3.5-35b-a3b",
    name: "Qwen3.5-35B-A3B",
    provider: "novita-ai",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-coder-480b-a35b-instruct",
    name: "Qwen3 Coder 480B A35B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.3,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3.5-397b-a17b",
    name: "Qwen3.5-397B-A17B",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-vl-30b-a3b-instruct",
    name: "qwen/qwen3-vl-30b-a3b-instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.7,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "video", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-omni-30b-a3b-instruct",
    name: "Qwen3 Omni 30B A3B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.97,
    contextWindow: 65536,
    maxOutputTokens: 16384,
    inputModalities: ["text", "video", "audio", "image"],
    outputModalities: ["text", "audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-vl-235b-a22b-instruct",
    name: "Qwen3 VL 235B A22B Instruct",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.5,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3.5-122b-a10b",
    name: "Qwen3.5-122B-A10B",
    provider: "novita-ai",
    inputPricePer1M: 0.4,
    outputPricePer1M: 3.2,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen/qwen3-235b-a22b-fp8",
    name: "Qwen3 235B A22B",
    provider: "novita-ai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 40960,
    maxOutputTokens: 20000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-r1-0528",
    name: "DeepSeek R1 0528",
    provider: "novita-ai",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.5,
    contextWindow: 163840,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "novita-ai",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1048576,
    maxOutputTokens: 393216,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3.1-terminus",
    name: "Deepseek V3.1 Terminus",
    provider: "novita-ai",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3-0324",
    name: "DeepSeek V3 0324",
    provider: "novita-ai",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.12,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-ocr",
    name: "DeepSeek-OCR",
    provider: "novita-ai",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.03,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-r1-distill-llama-70b",
    name: "DeepSeek R1 Distill LLama 70B",
    provider: "novita-ai",
    inputPricePer1M: 0.8,
    outputPricePer1M: 0.8,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-r1-turbo",
    name: "DeepSeek R1 (Turbo)\t",
    provider: "novita-ai",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.5,
    contextWindow: 64000,
    maxOutputTokens: 16000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-prover-v2-671b",
    name: "Deepseek Prover V2 671B",
    provider: "novita-ai",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.5,
    contextWindow: 160000,
    maxOutputTokens: 160000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "novita-ai",
    inputPricePer1M: 1.69,
    outputPricePer1M: 3.38,
    contextWindow: 1048576,
    maxOutputTokens: 393216,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3.2-exp",
    name: "Deepseek V3.2 Exp",
    provider: "novita-ai",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.41,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-ocr-2",
    name: "deepseek/deepseek-ocr-2",
    provider: "novita-ai",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.03,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-r1-distill-qwen-14b",
    name: "DeepSeek R1 Distill Qwen 14B",
    provider: "novita-ai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.15,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3.1",
    name: "DeepSeek V3.1",
    provider: "novita-ai",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-r1-0528-qwen3-8b",
    name: "DeepSeek R1 0528 Qwen3 8B",
    provider: "novita-ai",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.09,
    contextWindow: 128000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-r1-distill-qwen-32b",
    name: "DeepSeek R1 Distill Qwen 32B",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.3,
    contextWindow: 64000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3-turbo",
    name: "DeepSeek V3 (Turbo)\t",
    provider: "novita-ai",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.3,
    contextWindow: 64000,
    maxOutputTokens: 16000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3.2",
    name: "Deepseek V3.2",
    provider: "novita-ai",
    inputPricePer1M: 0.269,
    outputPricePer1M: 0.4,
    contextWindow: 163840,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax/minimax-m2.7-highspeed",
    name: "MiniMax-M2.7-highspeed",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax/minimax-m2.5",
    name: "MiniMax M2.5",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131100,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax/minimax-m2.1",
    name: "Minimax M2.1",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax/minimax-m2",
    name: "MiniMax-M2",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax/minimax-m2.7",
    name: "MiniMax M2.7",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax/minimax-m2.5-highspeed",
    name: "MiniMax M2.5 Highspeed",
    provider: "novita-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 204800,
    maxOutputTokens: 131100,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "kwaipilot/kat-coder-pro",
    name: "Kat Coder Pro",
    provider: "novita-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nousresearch/hermes-2-pro-llama-3-8b",
    name: "Hermes 2 Pro Llama 3 8B",
    provider: "novita-ai",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.14,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
];

export class NovitaAiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "novita-ai", apiKey, models: MODELS, apiBase: "https://api.novita.ai/openai" });
  }
}
