import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "opencode-go",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax M2.5",
    provider: "opencode-go",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    provider: "opencode-go",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "opencode-go",
    inputPricePer1M: 2.5,
    outputPricePer1M: 7.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "opencode-go",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    provider: "opencode-go",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 202752,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "opencode-go",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-5.2",
    name: "GLM-5.2",
    provider: "opencode-go",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax-m3",
    name: "MiniMax M3 (3x usage)",
    provider: "opencode-go",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 512000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.5-plus",
    name: "Qwen3.5 Plus",
    provider: "opencode-go",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.2,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax-m2.7",
    name: "MiniMax M2.7",
    provider: "opencode-go",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    provider: "opencode-go",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2.5",
    name: "MiMo V2.5",
    provider: "opencode-go",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2-omni",
    name: "MiMo V2 Omni",
    provider: "opencode-go",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    provider: "opencode-go",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2-pro",
    name: "MiMo V2 Pro",
    provider: "opencode-go",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    provider: "opencode-go",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 1048576,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "opencode-go",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202752,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    provider: "opencode-go",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class OpencodeGoAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "opencode-go",
      apiKey,
      models: MODELS,
      apiBase: "https://opencode.ai/zen/go/v1",
    });
  }
}
