import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "llama-3.1-8b-instruct",
    name: "Llama-3.1-8B-Instruct",
    provider: "ovhcloud",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.11,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3-Coder-30B-A3B-Instruct",
    provider: "ovhcloud",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.26,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3-32B",
    provider: "ovhcloud",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.25,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3guard-gen-8b",
    name: "Qwen3Guard-Gen-8B",
    provider: "ovhcloud",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3guard-gen-0.6b",
    name: "Qwen3Guard-Gen-0.6B",
    provider: "ovhcloud",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama-3_3-70b-instruct",
    name: "Meta-Llama-3_3-70B-Instruct",
    provider: "ovhcloud",
    inputPricePer1M: 0.74,
    outputPricePer1M: 0.74,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistral-small-3.2-24b-instruct-2506",
    name: "Mistral-Small-3.2-24B-Instruct-2506",
    provider: "ovhcloud",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.31,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen2.5-vl-72b-instruct",
    name: "Qwen2.5-VL-72B-Instruct",
    provider: "ovhcloud",
    inputPricePer1M: 1.01,
    outputPricePer1M: 1.01,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-oss-120b",
    name: "gpt-oss-120b",
    provider: "ovhcloud",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.47,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistral-7b-instruct-v0.3",
    name: "Mistral-7B-Instruct-v0.3",
    provider: "ovhcloud",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.11,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistral-nemo-instruct-2407",
    name: "Mistral-Nemo-Instruct-2407",
    provider: "ovhcloud",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.14,
    contextWindow: 65536,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.6-27b",
    name: "Qwen3.6-27B",
    provider: "ovhcloud",
    inputPricePer1M: 0.47,
    outputPricePer1M: 3.19,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5-9B",
    provider: "ovhcloud",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.18,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5-397B-A17B",
    provider: "ovhcloud",
    inputPricePer1M: 0.71,
    outputPricePer1M: 4.25,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gpt-oss-20b",
    name: "gpt-oss-20b",
    provider: "ovhcloud",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.18,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class OvhcloudAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "ovhcloud",
      apiKey,
      models: MODELS,
      apiBase: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
    });
  }
}
