import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "trytako/tako",
    name: "Tako",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 2048,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-code-fast-1",
    name: "Grok Code Fast 1",
    provider: "poe",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-4.1-fast-reasoning",
    name: "Grok-4.1-Fast-Reasoning",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-3-mini",
    name: "Grok 3 Mini",
    provider: "poe",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.5,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-4.1-fast-non-reasoning",
    name: "Grok-4.1-Fast-Non-Reasoning",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-3",
    name: "Grok 3",
    provider: "poe",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-4-fast-reasoning",
    name: "Grok-4-Fast-Reasoning",
    provider: "poe",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-4",
    name: "Grok-4",
    provider: "poe",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 256000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-4-fast-non-reasoning",
    name: "Grok-4-Fast-Non-Reasoning",
    provider: "poe",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xai/grok-4.20-multi-agent",
    name: "Grok-4.20-Multi-Agent",
    provider: "poe",
    inputPricePer1M: 2,
    outputPricePer1M: 6,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "topazlabs-co/topazlabs",
    name: "TopazLabs",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 204,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "fireworks-ai/kimi-k2.5-fw",
    name: "Kimi-K2.5-FW",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/veo-3.1-fast",
    name: "Veo-3.1-Fast",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/imagen-3",
    name: "Imagen-3",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/nano-banana-pro",
    name: "Nano-Banana-Pro",
    provider: "poe",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 65536,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/lyria",
    name: "Lyria",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3.1-flash-lite",
    name: "Gemini-3.1-Flash-Lite",
    provider: "poe",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/nano-banana",
    name: "Nano-Banana",
    provider: "poe",
    inputPricePer1M: 0.21,
    outputPricePer1M: 1.8,
    contextWindow: 65536,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-deep-research",
    name: "gemini-deep-research",
    provider: "poe",
    inputPricePer1M: 1.6,
    outputPricePer1M: 9.6,
    contextWindow: 1048576,
    maxOutputTokens: 0,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/veo-3",
    name: "Veo-3",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3-flash",
    name: "Gemini-3-Flash",
    provider: "poe",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2.4,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/imagen-3-fast",
    name: "Imagen-3-Fast",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini-2.5-Pro",
    provider: "poe",
    inputPricePer1M: 0.87,
    outputPricePer1M: 7,
    contextWindow: 1065535,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/veo-3.1",
    name: "Veo-3.1",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini-2.5-Flash",
    provider: "poe",
    inputPricePer1M: 0.21,
    outputPricePer1M: 1.8,
    contextWindow: 1065535,
    maxOutputTokens: 65535,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/imagen-4-fast",
    name: "Imagen-4-Fast",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3.5-flash",
    name: "Gemini-3.5-Flash",
    provider: "poe",
    inputPricePer1M: 1.5152,
    outputPricePer1M: 9.0909,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google/gemma-4-31b",
    name: "Gemma-4-31B",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/veo-3-fast",
    name: "Veo-3-Fast",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3-pro",
    name: "Gemini-3-Pro",
    provider: "poe",
    inputPricePer1M: 1.6,
    outputPricePer1M: 9.6,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-2.0-flash",
    name: "Gemini-2.0-Flash",
    provider: "poe",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.42,
    contextWindow: 990000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-2.5-flash-lite",
    name: "Gemini-2.5-Flash-Lite",
    provider: "poe",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.28,
    contextWindow: 1024000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/imagen-4",
    name: "Imagen-4",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/imagen-4-ultra",
    name: "Imagen-4-Ultra",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3.1-pro",
    name: "Gemini-3.1-Pro",
    provider: "poe",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/veo-2",
    name: "Veo-2",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 480,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-2.0-flash-lite",
    name: "Gemini-2.0-Flash-Lite",
    provider: "poe",
    inputPricePer1M: 0.052,
    outputPricePer1M: 0.21,
    contextWindow: 990000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "video", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "elevenlabs/elevenlabs-music",
    name: "ElevenLabs-Music",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 2000,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "elevenlabs/elevenlabs-v2.5-turbo",
    name: "ElevenLabs-v2.5-Turbo",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "elevenlabs/elevenlabs-v3",
    name: "ElevenLabs-v3",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/chatgpt-4o-latest",
    name: "ChatGPT-4o-Latest",
    provider: "poe",
    inputPricePer1M: 4.5,
    outputPricePer1M: 14,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-3.5-turbo-instruct",
    name: "GPT-3.5-Turbo-Instruct",
    provider: "poe",
    inputPricePer1M: 1.4,
    outputPricePer1M: 1.8,
    contextWindow: 3500,
    maxOutputTokens: 1024,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o3",
    name: "o3",
    provider: "poe",
    inputPricePer1M: 1.8,
    outputPricePer1M: 7.2,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2-instant",
    name: "GPT-5.2-Instant",
    provider: "poe",
    inputPricePer1M: 1.6,
    outputPricePer1M: 13,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4o-search",
    name: "GPT-4o-Search",
    provider: "poe",
    inputPricePer1M: 2.2,
    outputPricePer1M: 9,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2-pro",
    name: "GPT-5.2-Pro",
    provider: "poe",
    inputPricePer1M: 19,
    outputPricePer1M: 150,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4-classic-0314",
    name: "GPT-4-Classic-0314",
    provider: "poe",
    inputPricePer1M: 27,
    outputPricePer1M: 54,
    contextWindow: 8192,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5",
    name: "GPT-5",
    provider: "poe",
    inputPricePer1M: 1.1,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5-chat",
    name: "GPT-5-Chat",
    provider: "poe",
    inputPricePer1M: 1.1,
    outputPricePer1M: 9,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-3.5-turbo",
    name: "GPT-3.5-Turbo",
    provider: "poe",
    inputPricePer1M: 0.45,
    outputPricePer1M: 1.4,
    contextWindow: 16384,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5-pro",
    name: "GPT-5-Pro",
    provider: "poe",
    inputPricePer1M: 14,
    outputPricePer1M: 110,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o4-mini",
    name: "o4-mini",
    provider: "poe",
    inputPricePer1M: 0.99,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/sora-2",
    name: "Sora-2",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o3-pro",
    name: "o3-pro",
    provider: "poe",
    inputPricePer1M: 18,
    outputPricePer1M: 72,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4-classic",
    name: "GPT-4-Classic",
    provider: "poe",
    inputPricePer1M: 27,
    outputPricePer1M: 54,
    contextWindow: 8192,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4o-aug",
    name: "GPT-4o-Aug",
    provider: "poe",
    inputPricePer1M: 2.2,
    outputPricePer1M: 9,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4-nano",
    name: "GPT-5.4-Nano",
    provider: "poe",
    inputPricePer1M: 0.18,
    outputPricePer1M: 1.1,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/sora-2-pro",
    name: "Sora-2-Pro",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-codex",
    name: "GPT-5.1-Codex",
    provider: "poe",
    inputPricePer1M: 1.1,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.3-instant",
    name: "GPT-5.3-Instant",
    provider: "poe",
    inputPricePer1M: 1.6,
    outputPricePer1M: 13,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.3-codex-spark",
    name: "GPT-5.3-Codex-Spark",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-codex-max",
    name: "GPT-5.1-Codex-Max",
    provider: "poe",
    inputPricePer1M: 1.1,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/dall-e-3",
    name: "DALL-E-3",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 800,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o3-mini",
    name: "o3-mini",
    provider: "poe",
    inputPricePer1M: 0.99,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2",
    name: "GPT-5.2",
    provider: "poe",
    inputPricePer1M: 1.6,
    outputPricePer1M: 13,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.3-codex",
    name: "GPT-5.3-Codex",
    provider: "poe",
    inputPricePer1M: 1.6,
    outputPricePer1M: 13,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-codex-mini",
    name: "GPT-5.1-Codex-Mini",
    provider: "poe",
    inputPricePer1M: 0.22,
    outputPricePer1M: 1.8,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o4-mini-deep-research",
    name: "o4-mini-deep-research",
    provider: "poe",
    inputPricePer1M: 1.8,
    outputPricePer1M: 7.2,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-image-1.5",
    name: "gpt-image-1.5",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4.1-nano",
    name: "GPT-4.1-nano",
    provider: "poe",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.36,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-3.5-turbo-raw",
    name: "GPT-3.5-Turbo-Raw",
    provider: "poe",
    inputPricePer1M: 0.45,
    outputPricePer1M: 1.4,
    contextWindow: 4524,
    maxOutputTokens: 2048,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o1",
    name: "o1",
    provider: "poe",
    inputPricePer1M: 14,
    outputPricePer1M: 54,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o1-pro",
    name: "o1-pro",
    provider: "poe",
    inputPricePer1M: 140,
    outputPricePer1M: 540,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4",
    name: "GPT-5.4",
    provider: "poe",
    inputPricePer1M: 2.2,
    outputPricePer1M: 14,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["image"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4-mini",
    name: "GPT-5.4-Mini",
    provider: "poe",
    inputPricePer1M: 0.68,
    outputPricePer1M: 4,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4.1",
    name: "GPT-4.1",
    provider: "poe",
    inputPricePer1M: 1.8,
    outputPricePer1M: 7.2,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o3-deep-research",
    name: "o3-deep-research",
    provider: "poe",
    inputPricePer1M: 9,
    outputPricePer1M: 36,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5-mini",
    name: "GPT-5-mini",
    provider: "poe",
    inputPricePer1M: 0.22,
    outputPricePer1M: 1.8,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-image-1",
    name: "GPT-Image-1",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4.1-mini",
    name: "GPT-4.1-mini",
    provider: "poe",
    inputPricePer1M: 0.36,
    outputPricePer1M: 1.4,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4-turbo",
    name: "GPT-4-Turbo",
    provider: "poe",
    inputPricePer1M: 9,
    outputPricePer1M: 27,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-image-1-mini",
    name: "GPT-Image-1-Mini",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5-nano",
    name: "GPT-5-nano",
    provider: "poe",
    inputPricePer1M: 0.045,
    outputPricePer1M: 0.36,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4-pro",
    name: "GPT-5.4-Pro",
    provider: "poe",
    inputPricePer1M: 27,
    outputPricePer1M: 160,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/o3-mini-high",
    name: "o3-mini-high",
    provider: "poe",
    inputPricePer1M: 0.99,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.5-pro",
    name: "GPT-5.5-Pro",
    provider: "poe",
    inputPricePer1M: 27.2727,
    outputPricePer1M: 163.6364,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o-mini",
    provider: "poe",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.54,
    contextWindow: 124096,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-4o-mini-search",
    name: "GPT-4o-mini-Search",
    provider: "poe",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.54,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5-codex",
    name: "GPT-5-Codex",
    provider: "poe",
    inputPricePer1M: 1.1,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2-codex",
    name: "GPT-5.2-Codex",
    provider: "poe",
    inputPricePer1M: 1.6,
    outputPricePer1M: 13,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-instant",
    name: "GPT-5.1-Instant",
    provider: "poe",
    inputPricePer1M: 1.1,
    outputPricePer1M: 9,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-image-2",
    name: "GPT-Image-2",
    provider: "poe",
    inputPricePer1M: 5.0505,
    outputPricePer1M: 32.3232,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1",
    name: "GPT-5.1",
    provider: "poe",
    inputPricePer1M: 1.1,
    outputPricePer1M: 9,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.5",
    name: "GPT-5.5",
    provider: "poe",
    inputPricePer1M: 4.5455,
    outputPricePer1M: 27.2727,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text", "image"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "runwayml/runway",
    name: "Runway",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "runwayml/runway-gen-4-turbo",
    name: "Runway-Gen-4-Turbo",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cerebras/llama-3.1-8b-cs",
    name: "Llama-3.1-8B-CS",
    provider: "poe",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cerebras/qwen3-235b-2507-cs",
    name: "qwen3-235b-2507-cs",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cerebras/gpt-oss-120b-cs",
    name: "GPT-OSS-120B-CS",
    provider: "poe",
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.75,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cerebras/llama-3.3-70b-cs",
    name: "llama-3.3-70b-cs",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "cerebras/qwen3-32b-cs",
    name: "qwen3-32b-cs",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-3.5",
    name: "Claude-Sonnet-3.5",
    provider: "poe",
    inputPricePer1M: 2.6,
    outputPricePer1M: 13,
    contextWindow: 189096,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-3.7",
    name: "Claude-Sonnet-3.7",
    provider: "poe",
    inputPricePer1M: 2.6,
    outputPricePer1M: 13,
    contextWindow: 196608,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-3.5-june",
    name: "Claude-Sonnet-3.5-June",
    provider: "poe",
    inputPricePer1M: 2.6,
    outputPricePer1M: 13,
    contextWindow: 189096,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4.5",
    name: "Claude-Sonnet-4.5",
    provider: "poe",
    inputPricePer1M: 2.6,
    outputPricePer1M: 13,
    contextWindow: 983040,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4",
    name: "Claude-Sonnet-4",
    provider: "poe",
    inputPricePer1M: 2.6,
    outputPricePer1M: 13,
    contextWindow: 983040,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-haiku-4.5",
    name: "Claude-Haiku-4.5",
    provider: "poe",
    inputPricePer1M: 0.85,
    outputPricePer1M: 4.3,
    contextWindow: 192000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-haiku-3",
    name: "Claude-Haiku-3",
    provider: "poe",
    inputPricePer1M: 0.21,
    outputPricePer1M: 1.1,
    contextWindow: 189096,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.7",
    name: "Claude-Opus-4.7",
    provider: "poe",
    inputPricePer1M: 4.3,
    outputPricePer1M: 21,
    contextWindow: 1048576,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-haiku-3.5",
    name: "Claude-Haiku-3.5",
    provider: "poe",
    inputPricePer1M: 0.68,
    outputPricePer1M: 3.4,
    contextWindow: 189096,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.8",
    name: "Claude-Opus-4.8",
    provider: "poe",
    inputPricePer1M: 4.2929,
    outputPricePer1M: 21.4646,
    contextWindow: 1048576,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.1",
    name: "Claude-Opus-4.1",
    provider: "poe",
    inputPricePer1M: 13,
    outputPricePer1M: 64,
    contextWindow: 196608,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.5",
    name: "Claude-Opus-4.5",
    provider: "poe",
    inputPricePer1M: 4.3,
    outputPricePer1M: 21,
    contextWindow: 196608,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4.6",
    name: "Claude-Sonnet-4.6",
    provider: "poe",
    inputPricePer1M: 2.6,
    outputPricePer1M: 13,
    contextWindow: 983040,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4",
    name: "Claude-Opus-4",
    provider: "poe",
    inputPricePer1M: 13,
    outputPricePer1M: 64,
    contextWindow: 192512,
    maxOutputTokens: 28672,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.6",
    name: "Claude-Opus-4.6",
    provider: "poe",
    inputPricePer1M: 4.3,
    outputPricePer1M: 21,
    contextWindow: 983040,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "lumalabs/ray2",
    name: "Ray2",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 5000,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "poetools/claude-code",
    name: "claude-code",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "empiriolabs/deepseek-v4-pro-el",
    name: "DeepSeek-V4-Pro-EL",
    provider: "poe",
    inputPricePer1M: 1.67,
    outputPricePer1M: 3.33,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "empiriolabs/deepseek-v4-flash-el",
    name: "DeepSeek-V4-Flash-EL",
    provider: "poe",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "stabilityai/stablediffusionxl",
    name: "StableDiffusionXL",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "ideogramai/ideogram",
    name: "Ideogram",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 150,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "ideogramai/ideogram-v2a",
    name: "Ideogram-v2a",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 150,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "ideogramai/ideogram-v2",
    name: "Ideogram-v2",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 150,
    maxOutputTokens: 0,
    inputModalities: ["text", "image"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "ideogramai/ideogram-v2a-turbo",
    name: "Ideogram-v2a-Turbo",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 150,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/glm-4.7",
    name: "glm-4.7",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 205000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/minimax-m2.1",
    name: "minimax-m2.1",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 205000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/glm-4.6",
    name: "GLM-4.6",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/kimi-k2-thinking",
    name: "kimi-k2-thinking",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/kimi-k2.5",
    name: "Kimi-K2.5",
    provider: "poe",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 128000,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/glm-4.6v",
    name: "glm-4.6v",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/kimi-k2.6",
    name: "Kimi-K2.6",
    provider: "poe",
    inputPricePer1M: 0.96,
    outputPricePer1M: 4.04,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "novita/glm-4.7-flash",
    name: "glm-4.7-flash",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 65500,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/glm-4.7-n",
    name: "glm-4.7-n",
    provider: "poe",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 205000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/glm-5",
    name: "GLM-5",
    provider: "poe",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 205000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "novita/deepseek-v3.2",
    name: "DeepSeek-V3.2",
    provider: "poe",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.4,
    contextWindow: 128000,
    maxOutputTokens: 0,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class PoeAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "poe", apiKey, models: MODELS, apiBase: "https://api.poe.com/v1" });
  }
}
