import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    provider: "regolo-ai",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.25,
    contextWindow: 120000,
    maxOutputTokens: 120000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax 2.5",
    provider: "regolo-ai",
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.5,
    contextWindow: 190000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-small3.2",
    name: "Mistral Small 3.2",
    provider: "regolo-ai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.2,
    contextWindow: 120000,
    maxOutputTokens: 120000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-reranker-4b",
    name: "Qwen3-Reranker-4B",
    provider: "regolo-ai",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.12,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-embedding-8b",
    name: "Qwen3-Embedding-8B",
    provider: "regolo-ai",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 32768,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    provider: "regolo-ai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.7,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen-image",
    name: "Qwen-Image",
    provider: "regolo-ai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 8192,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["image"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.5-122b",
    name: "Qwen3.5-122B",
    provider: "regolo-ai",
    inputPricePer1M: 0.9,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-oss-120b",
    name: "GPT-OSS-120B",
    provider: "regolo-ai",
    inputPricePer1M: 1,
    outputPricePer1M: 4.2,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-coder-next",
    name: "Qwen3-Coder-Next",
    provider: "regolo-ai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 262144,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5-9B",
    provider: "regolo-ai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-small-4-119b",
    name: "Mistral Small 4 119B",
    provider: "regolo-ai",
    inputPricePer1M: 0.75,
    outputPricePer1M: 3,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "gpt-oss-20b",
    name: "GPT-OSS-20B",
    provider: "regolo-ai",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.8,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class RegoloAiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "regolo-ai", apiKey, models: MODELS, apiBase: "https://api.regolo.ai/v1" });
  }
}
