import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "route/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "routing-run",
    inputPricePer1M: 0.4928,
    outputPricePer1M: 0.7392,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/deepseek-v4-flash-6bit",
    name: "DeepSeek V4 Flash 6bit",
    provider: "routing-run",
    inputPricePer1M: 0.4928,
    outputPricePer1M: 0.7392,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/minimax-m2.7-highspeed",
    name: "MiniMax M2.7 Highspeed",
    provider: "routing-run",
    inputPricePer1M: 0.33,
    outputPricePer1M: 1.32,
    contextWindow: 100000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/glm-5.1-6bit",
    name: "GLM 5.1 6bit",
    provider: "routing-run",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 202752,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/minimax-m2.5",
    name: "MiniMax M2.5",
    provider: "routing-run",
    inputPricePer1M: 0.193,
    outputPricePer1M: 1.238,
    contextWindow: 100000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/mistral-small-2503",
    name: "Mistral Small 2503",
    provider: "routing-run",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    provider: "routing-run",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/step-3.5-flash-2603",
    name: "Step 3.5 Flash 2603",
    provider: "routing-run",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/glm-5.1",
    name: "GLM 5.1",
    provider: "routing-run",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 202752,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "routing-run",
    inputPricePer1M: 0.4928,
    outputPricePer1M: 0.7392,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/mistral-large-3",
    name: "Mistral Large 3",
    provider: "routing-run",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/deepseek-v4-pro-6bit",
    name: "DeepSeek V4 Pro 6bit",
    provider: "routing-run",
    inputPricePer1M: 0.4928,
    outputPricePer1M: 0.7392,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/mistral-medium-2505",
    name: "Mistral Medium 2505",
    provider: "routing-run",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "route/minimax-m2.7",
    name: "MiniMax M2.7",
    provider: "routing-run",
    inputPricePer1M: 0.33,
    outputPricePer1M: 1.32,
    contextWindow: 100000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/qwen3.6-27b-202k",
    name: "Qwen3.6 27B 202K",
    provider: "routing-run",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3.3,
    contextWindow: 202000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "routing-run",
    inputPricePer1M: 0.462,
    outputPricePer1M: 2.42,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/minimax-m2.5-highspeed",
    name: "MiniMax M2.5 Highspeed",
    provider: "routing-run",
    inputPricePer1M: 0.193,
    outputPricePer1M: 1.238,
    contextWindow: 100000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/kimi-k2.6-6bit",
    name: "Kimi K2.6 6bit",
    provider: "routing-run",
    inputPricePer1M: 0.462,
    outputPricePer1M: 2.42,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/mimo-v2.5",
    name: "MiMo V2.5",
    provider: "routing-run",
    inputPricePer1M: 0.45,
    outputPricePer1M: 1.35,
    contextWindow: 1000000,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/kimi-k2.6",
    name: "Kimi K2.6",
    provider: "routing-run",
    inputPricePer1M: 0.462,
    outputPricePer1M: 2.42,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/qwen3.6-27b",
    name: "Qwen3.6 27B",
    provider: "routing-run",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3.3,
    contextWindow: 202000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "route/mimo-v2.5-pro-6bit",
    name: "MiMo V2.5 Pro 6bit",
    provider: "routing-run",
    inputPricePer1M: 0.45,
    outputPricePer1M: 1.35,
    contextWindow: 1000000,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/stepfun-3.5-flash",
    name: "StepFun 3.5 Flash",
    provider: "routing-run",
    inputPricePer1M: 0.096,
    outputPricePer1M: 0.288,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    provider: "routing-run",
    inputPricePer1M: 0.45,
    outputPricePer1M: 1.35,
    contextWindow: 1000000,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/step-3.5-flash",
    name: "Step 3.5 Flash",
    provider: "routing-run",
    inputPricePer1M: 0.096,
    outputPricePer1M: 0.288,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "route/deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "routing-run",
    inputPricePer1M: 0.4928,
    outputPricePer1M: 0.7392,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class RoutingRunAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "routing-run", apiKey, models: MODELS, apiBase: "https://ai.routing.sh/v1" });
  }
}
