import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "qwen3-235b-a22b-instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    provider: "scaleway",
    inputPricePer1M: 0.75,
    outputPricePer1M: 2.25,
    contextWindow: 260000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3-Coder 30B-A3B Instruct",
    provider: "scaleway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-embedding-8b",
    name: "Qwen3 Embedding 8B",
    provider: "scaleway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0,
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "bge-multilingual-gemma2",
    name: "BGE Multilingual Gemma2",
    provider: "scaleway",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0,
    contextWindow: 8191,
    maxOutputTokens: 3072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3.6-35b-a3b",
    name: "Qwen3.6 35B A3B",
    provider: "scaleway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama-3.3-70B-Instruct",
    provider: "scaleway",
    inputPricePer1M: 0.9,
    outputPricePer1M: 0.9,
    contextWindow: 100000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "pixtral-12b-2409",
    name: "Pixtral 12B 2409",
    provider: "scaleway",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mistral-small-3.2-24b-instruct-2506",
    name: "Mistral Small 3.2 24B Instruct (2506)",
    provider: "scaleway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.35,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gpt-oss-120b",
    name: "GPT-OSS 120B",
    provider: "scaleway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gemma-4-26b-a4b-it",
    name: "Gemma 4 26B A4B IT",
    provider: "scaleway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.5,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistral-medium-3.5-128b",
    name: "Mistral Medium 3.5 128B",
    provider: "scaleway",
    inputPricePer1M: 1.5,
    outputPricePer1M: 7.5,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B A17B",
    provider: "scaleway",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "whisper-large-v3",
    name: "Whisper Large v3",
    provider: "scaleway",
    inputPricePer1M: 0.003,
    outputPricePer1M: 0,
    contextWindow: 0,
    maxOutputTokens: 8192,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gemma-3-27b-it",
    name: "Gemma-3-27B-IT",
    provider: "scaleway",
    inputPricePer1M: 0.25,
    outputPricePer1M: 0.5,
    contextWindow: 40000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "voxtral-small-24b-2507",
    name: "Voxtral Small 24B 2507",
    provider: "scaleway",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.35,
    contextWindow: 32000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "devstral-2-123b-instruct-2512",
    name: "Devstral 2 123B Instruct (2512)",
    provider: "scaleway",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class ScalewayAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "scaleway", apiKey, models: MODELS, apiBase: "https://api.scaleway.ai/v1" });
  }
}
