import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/Kimi-K2-Thinking",
    name: "moonshotai/Kimi-K2-Thinking",
    provider: "siliconflow",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.5,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "moonshotai/Kimi-K2-Instruct-0905",
    name: "moonshotai/Kimi-K2-Instruct-0905",
    provider: "siliconflow",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "moonshotai/Kimi-K2-Instruct",
    name: "moonshotai/Kimi-K2-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.58,
    outputPricePer1M: 2.29,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "moonshotai/Kimi-K2.6",
    provider: "siliconflow",
    inputPricePer1M: 0.77,
    outputPricePer1M: 4,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "moonshotai/Kimi-K2.5",
    provider: "siliconflow",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.25,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "baidu/ERNIE-4.5-300B-A47B",
    name: "baidu/ERNIE-4.5-300B-A47B",
    provider: "siliconflow",
    inputPricePer1M: 0.28,
    outputPricePer1M: 1.1,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "ByteDance-Seed/Seed-OSS-36B-Instruct",
    name: "ByteDance-Seed/Seed-OSS-36B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.21,
    outputPricePer1M: 0.57,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "stepfun-ai/Step-3.5-Flash",
    name: "stepfun-ai/Step-3.5-Flash",
    provider: "siliconflow",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google/gemma-4-31B-it",
    name: "Gemma 4 31B IT",
    provider: "siliconflow",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google/gemma-4-26B-A4B-it",
    name: "Gemma 4 26B A4B IT",
    provider: "siliconflow",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "inclusionAI/Ling-flash-2.0",
    name: "inclusionAI/Ling-flash-2.0",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.57,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-Omni-30B-A3B-Thinking",
    name: "Qwen/Qwen3-Omni-30B-A3B-Thinking",
    provider: "siliconflow",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 66000,
    maxOutputTokens: 66000,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-VL-72B-Instruct",
    name: "Qwen/Qwen2.5-VL-72B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.59,
    contextWindow: 131000,
    maxOutputTokens: 4000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-VL-32B-Instruct",
    name: "Qwen/Qwen2.5-VL-32B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.27,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Thinking-2507",
    name: "Qwen/Qwen3-30B-A3B-Thinking-2507",
    provider: "siliconflow",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.3,
    contextWindow: 262000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-7B-Instruct",
    name: "Qwen/Qwen2.5-7B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.05,
    contextWindow: 33000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-235B-A22B-Instruct",
    name: "Qwen/Qwen3-VL-235B-A22B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.5,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-32B-Instruct",
    name: "Qwen/Qwen2.5-32B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.18,
    contextWindow: 33000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    name: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 1.4,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    provider: "siliconflow",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.6,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-72B-Instruct-128K",
    name: "Qwen/Qwen2.5-72B-Instruct-128K",
    provider: "siliconflow",
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.59,
    contextWindow: 131000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    name: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.28,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Instruct-2507",
    name: "Qwen/Qwen3-30B-A3B-Instruct-2507",
    provider: "siliconflow",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.3,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-30B-A3B-Thinking",
    name: "Qwen/Qwen3-VL-30B-A3B-Thinking",
    provider: "siliconflow",
    inputPricePer1M: 0.29,
    outputPricePer1M: 1,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-8B-Thinking",
    name: "Qwen/Qwen3-VL-8B-Thinking",
    provider: "siliconflow",
    inputPricePer1M: 0.18,
    outputPricePer1M: 2,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-8B-Instruct",
    name: "Qwen/Qwen3-VL-8B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.68,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/QwQ-32B",
    name: "Qwen/QwQ-32B",
    provider: "siliconflow",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.58,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-Omni-30B-A3B-Captioner",
    name: "Qwen/Qwen3-Omni-30B-A3B-Captioner",
    provider: "siliconflow",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 66000,
    maxOutputTokens: 66000,
    inputModalities: ["audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-235B-A22B-Thinking",
    name: "Qwen/Qwen3-VL-235B-A22B-Thinking",
    provider: "siliconflow",
    inputPricePer1M: 0.45,
    outputPricePer1M: 3.5,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
    name: "Qwen/Qwen3-Next-80B-A3B-Thinking",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.57,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-Coder-32B-Instruct",
    name: "Qwen/Qwen2.5-Coder-32B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.18,
    contextWindow: 33000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-VL-7B-Instruct",
    name: "Qwen/Qwen2.5-VL-7B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.05,
    contextWindow: 33000,
    maxOutputTokens: 4000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-8B",
    name: "Qwen/Qwen3-8B",
    provider: "siliconflow",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.06,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    name: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    provider: "siliconflow",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.6,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-32B",
    name: "Qwen/Qwen3-32B",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.57,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-32B-Instruct",
    name: "Qwen/Qwen3-VL-32B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-14B-Instruct",
    name: "Qwen/Qwen2.5-14B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 33000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-14B",
    name: "Qwen/Qwen3-14B",
    provider: "siliconflow",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.28,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-235B-A22B",
    name: "Qwen/Qwen3-235B-A22B",
    provider: "siliconflow",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.42,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen2.5-72B-Instruct",
    name: "Qwen/Qwen2.5-72B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.59,
    contextWindow: 33000,
    maxOutputTokens: 4000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-Omni-30B-A3B-Instruct",
    name: "Qwen/Qwen3-Omni-30B-A3B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 66000,
    maxOutputTokens: 66000,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-30B-A3B-Instruct",
    name: "Qwen/Qwen3-VL-30B-A3B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.29,
    outputPricePer1M: 1,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-VL-32B-Thinking",
    name: "Qwen/Qwen3-VL-32B-Thinking",
    provider: "siliconflow",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.5,
    contextWindow: 262000,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "openai/gpt-oss-120b",
    provider: "siliconflow",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.45,
    contextWindow: 131000,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "openai/gpt-oss-20b",
    provider: "siliconflow",
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.18,
    contextWindow: 131000,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "tencent/Hy3-preview",
    name: "Hy3 preview",
    provider: "siliconflow",
    inputPricePer1M: 0.066,
    outputPricePer1M: 0.26,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "tencent/Hunyuan-A13B-Instruct",
    name: "tencent/Hunyuan-A13B-Instruct",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.57,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-5V-Turbo",
    name: "zai-org/GLM-5V-Turbo",
    provider: "siliconflow",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-4.6",
    name: "zai-org/GLM-4.6",
    provider: "siliconflow",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.9,
    contextWindow: 205000,
    maxOutputTokens: 205000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-4.6V",
    name: "zai-org/GLM-4.6V",
    provider: "siliconflow",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-5",
    name: "zai-org/GLM-5",
    provider: "siliconflow",
    inputPricePer1M: 0.95,
    outputPricePer1M: 2.55,
    contextWindow: 205000,
    maxOutputTokens: 205000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.7",
    name: "zai-org/GLM-4.7",
    provider: "siliconflow",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 205000,
    maxOutputTokens: 205000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-4.5V",
    name: "zai-org/GLM-4.5V",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.86,
    contextWindow: 66000,
    maxOutputTokens: 66000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-5.2",
    name: "GLM-5.2",
    provider: "siliconflow",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 205000,
    maxOutputTokens: 205000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.5-Air",
    name: "zai-org/GLM-4.5-Air",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.86,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-5.1",
    name: "zai-org/GLM-5.1",
    provider: "siliconflow",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 205000,
    maxOutputTokens: 205000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.5",
    name: "zai-org/GLM-4.5",
    provider: "siliconflow",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "siliconflow",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-R1",
    name: "deepseek-ai/DeepSeek-R1",
    provider: "siliconflow",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.18,
    contextWindow: 164000,
    maxOutputTokens: 164000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    provider: "siliconflow",
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.18,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.1-Terminus",
    name: "deepseek-ai/DeepSeek-V3.1-Terminus",
    provider: "siliconflow",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 164000,
    maxOutputTokens: 164000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "siliconflow",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.1",
    name: "deepseek-ai/DeepSeek-V3.1",
    provider: "siliconflow",
    inputPricePer1M: 0.27,
    outputPricePer1M: 1,
    contextWindow: 164000,
    maxOutputTokens: 164000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2-Exp",
    name: "deepseek-ai/DeepSeek-V3.2-Exp",
    provider: "siliconflow",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.41,
    contextWindow: 164000,
    maxOutputTokens: 164000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/deepseek-vl2",
    name: "deepseek-ai/deepseek-vl2",
    provider: "siliconflow",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.15,
    contextWindow: 4000,
    maxOutputTokens: 4000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2",
    name: "deepseek-ai/DeepSeek-V3.2",
    provider: "siliconflow",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.42,
    contextWindow: 164000,
    maxOutputTokens: 164000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-V3",
    name: "deepseek-ai/DeepSeek-V3",
    provider: "siliconflow",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1,
    contextWindow: 164000,
    maxOutputTokens: 164000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    provider: "siliconflow",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 131000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMaxAI/MiniMax-M2.5",
    provider: "siliconflow",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 197000,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class SiliconflowAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "siliconflow",
      apiKey,
      models: MODELS,
      apiBase: "https://api.siliconflow.com/v1",
    });
  }
}
