import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "openai-gpt-5.1",
    name: "GPT-5.1",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "snowflake-llama3.3-70b",
    name: "Llama-3.3-70B-Instruct",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-5.2",
    name: "GPT-5.2",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5 (latest)",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-5",
    name: "GPT-5",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-5.5",
    name: "GPT-5.5",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-5-nano",
    name: "GPT-5 Nano",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5 (latest)",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mistral-large2",
    name: "Mistral Large (latest)",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai-gpt-4.1",
    name: "GPT-4.1",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai-gpt-5.4",
    name: "GPT-5.4",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro Preview",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "snowflake-cortex",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 272000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class SnowflakeCortexAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "snowflake-cortex",
      apiKey,
      models: MODELS,
    });
  }
}
