import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8",
    name: "Llama 3.1 8B",
    provider: "stackit",
    inputPricePer1M: 0.16,
    outputPricePer1M: 0.27,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "neuralmagic/Mistral-Nemo-Instruct-2407-FP8",
    name: "Mistral Nemo",
    provider: "stackit",
    inputPricePer1M: 0.49,
    outputPricePer1M: 0.71,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "cortecs/Llama-3.3-70B-Instruct-FP8-Dynamic",
    name: "Llama 3.3 70B",
    provider: "stackit",
    inputPricePer1M: 0.49,
    outputPricePer1M: 0.71,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "google/gemma-3-27b-it",
    name: "Gemma 3 27B",
    provider: "stackit",
    inputPricePer1M: 0.49,
    outputPricePer1M: 0.71,
    contextWindow: 37000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-VL-Embedding-8B",
    name: "Qwen3-VL Embedding 8B",
    provider: "stackit",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.09,
    contextWindow: 32000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-VL-235B-A22B-Instruct-FP8",
    name: "Qwen3-VL 235B",
    provider: "stackit",
    inputPricePer1M: 1.64,
    outputPricePer1M: 1.91,
    contextWindow: 218000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS 120B",
    provider: "stackit",
    inputPricePer1M: 0.49,
    outputPricePer1M: 0.71,
    contextWindow: 131000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "intfloat/e5-mistral-7b-instruct",
    name: "E5 Mistral 7B",
    provider: "stackit",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.02,
    contextWindow: 4096,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
];

export class StackitAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "stackit",
      apiKey,
      models: MODELS,
      apiBase: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
    });
  }
}
