import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen3 235B A22B Thinking 2507",
    provider: "submodel",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
    name: "Qwen3 Coder 480B A35B Instruct",
    provider: "submodel",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    provider: "submodel",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "submodel",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.5,
    contextWindow: 131072,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.5-FP8",
    name: "GLM 4.5 FP8",
    provider: "submodel",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-4.5-Air",
    name: "GLM 4.5 Air",
    provider: "submodel",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.5,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3-0324",
    name: "DeepSeek V3 0324",
    provider: "submodel",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 75000,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-R1-0528",
    name: "DeepSeek R1 0528",
    provider: "submodel",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.15,
    contextWindow: 75000,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.1",
    name: "DeepSeek V3.1",
    provider: "submodel",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 75000,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class SubmodelAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "submodel", apiKey, models: MODELS, apiBase: "https://llm.submodel.ai/v1" });
  }
}
