import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

type SumopodModel = {
  id: string;
  name: string;
  inputPricePer1M: number;
  outputPricePer1M: number;
  contextWindow: number;
  maxOutputTokens?: number;
  inputModalities?: string[];
  reasoning?: boolean;
  toolCall?: boolean;
  structuredOutput?: boolean;
  weights?: Model["weights"];
};

function model(input: SumopodModel): Model {
  return {
    id: input.id,
    name: input.name,
    provider: "sumopod",
    inputPricePer1M: input.inputPricePer1M,
    outputPricePer1M: input.outputPricePer1M,
    contextWindow: input.contextWindow,
    maxOutputTokens: input.maxOutputTokens ?? input.contextWindow,
    inputModalities: input.inputModalities ?? ["text"],
    outputModalities: ["text"],
    reasoning: input.reasoning ?? true,
    toolCall: input.toolCall ?? true,
    structuredOutput: input.structuredOutput ?? true,
    weights: input.weights ?? "closed",
  };
}

const anthropicInput = ["text", "image", "pdf"];
const geminiInput = ["text", "image", "audio", "video", "pdf"];
const openAIInput = ["text", "image"];
const openAIPdfInput = ["text", "image", "pdf"];
const visionInput = ["text", "image"];
const pdfInput = ["text", "pdf"];

const MODELS: Model[] = [
  model({
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: anthropicInput,
  }),
  model({
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: anthropicInput,
  }),
  model({
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: anthropicInput,
  }),
  model({
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: anthropicInput,
  }),
  model({
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: openAIPdfInput,
    weights: "open",
  }),
  model({
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    inputPricePer1M: 0.43,
    outputPricePer1M: 0.87,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: pdfInput,
    weights: "open",
  }),
  model({
    id: "gemini/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1048576,
    maxOutputTokens: 64000,
    inputModalities: geminiInput,
  }),
  model({
    id: "gemini/gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1048576,
    maxOutputTokens: 64000,
    inputModalities: geminiInput,
  }),
  model({
    id: "gemini/gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 64000,
    inputModalities: geminiInput,
  }),
  model({
    id: "gemini/gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1048576,
    maxOutputTokens: 64000,
    inputModalities: geminiInput,
  }),
  model({
    id: "gemini/gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048576,
    maxOutputTokens: 64000,
    inputModalities: geminiInput,
  }),
  model({
    id: "gemini/gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    inputPricePer1M: 1.5,
    outputPricePer1M: 9,
    contextWindow: 1048576,
    maxOutputTokens: 64000,
    inputModalities: geminiInput,
  }),
  model({
    id: "gemini/gemini-embedding-001",
    name: "Gemini Embedding 001",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0,
    contextWindow: 2048,
    maxOutputTokens: 1,
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
  }),
  model({
    id: "glm-5",
    name: "GLM 5",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: visionInput,
  }),
  model({
    id: "glm-5-turbo",
    name: "GLM 5 Turbo",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: visionInput,
  }),
  model({
    id: "glm-5.1",
    name: "GLM 5.1",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: openAIPdfInput,
  }),
  model({
    id: "glm-5.2",
    name: "GLM 5.2",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: openAIPdfInput,
  }),
  model({
    id: "glm-5v-turbo",
    name: "GLM 5V Turbo",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: visionInput,
  }),
  model({
    id: "gpt-4.1",
    name: "GPT-4.1",
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: openAIInput,
    reasoning: false,
    structuredOutput: false,
  }),
  model({
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: openAIInput,
    reasoning: false,
  }),
  model({
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    inputModalities: openAIInput,
    reasoning: false,
  }),
  model({
    id: "gpt-4o",
    name: "GPT-4o",
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: openAIPdfInput,
    reasoning: false,
  }),
  model({
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: openAIInput,
    reasoning: false,
  }),
  model({
    id: "gpt-5",
    name: "GPT-5",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: openAIInput,
  }),
  model({
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: openAIInput,
  }),
  model({
    id: "gpt-5-nano",
    name: "GPT-5 Nano",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.4,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: openAIInput,
  }),
  model({
    id: "gpt-5.4",
    name: "GPT-5.4",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: openAIPdfInput,
  }),
  model({
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: openAIInput,
  }),
  model({
    id: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.25,
    contextWindow: 272000,
    maxOutputTokens: 128000,
    inputModalities: openAIInput,
  }),
  model({
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    inputPricePer1M: 0.67,
    outputPricePer1M: 3.39,
    contextWindow: 262100,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image", "video"],
    weights: "open",
  }),
  model({
    id: "kimi-k2.7",
    name: "Kimi K2.7",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262100,
    maxOutputTokens: 262000,
    inputModalities: ["text", "image", "video"],
    weights: "open",
  }),
  model({
    id: "mimo-v2.5",
    name: "MiMo V2.5",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1100000,
    maxOutputTokens: 16384,
    inputModalities: geminiInput,
    weights: "open",
  }),
  model({
    id: "mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    inputPricePer1M: 0.43,
    outputPricePer1M: 0.87,
    contextWindow: 1100000,
    maxOutputTokens: 16384,
    inputModalities: geminiInput,
    weights: "open",
  }),
  model({
    id: "MiniMax-M2.7-highspeed",
    name: "MiniMax M2.7 Highspeed",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.12,
    contextWindow: 204800,
    maxOutputTokens: 131100,
    weights: "open",
  }),
  model({
    id: "MiniMax-M3",
    name: "MiniMax M3",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
    weights: "open",
  }),
  model({
    id: "qwen3.6-flash",
    name: "Qwen 3.6 Flash",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: pdfInput,
  }),
  model({
    id: "qwen3.6-plus",
    name: "Qwen 3.6 Plus",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: pdfInput,
  }),
  model({
    id: "qwen3.7-max",
    name: "Qwen 3.7 Max",
    inputPricePer1M: 1.25,
    outputPricePer1M: 3.75,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: pdfInput,
  }),
  model({
    id: "qwen3.7-plus",
    name: "Qwen 3.7 Plus",
    inputPricePer1M: 0.32,
    outputPricePer1M: 1.28,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: pdfInput,
  }),
  model({
    id: "seed-2-0-code",
    name: "Seed 2.0 Code",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 256000,
    maxOutputTokens: 128000,
  }),
  model({
    id: "seed-2-0-lite",
    name: "Seed 2.0 Lite",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 224000,
    maxOutputTokens: 32768,
  }),
  model({
    id: "seed-2-0-mini",
    name: "Seed 2.0 Mini",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 224000,
    maxOutputTokens: 32768,
  }),
  model({
    id: "seed-2-0-pro",
    name: "Seed 2.0 Pro",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 256000,
    maxOutputTokens: 128000,
  }),
  model({
    id: "text-embedding-3-large",
    name: "text-embedding-3-large",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0,
    contextWindow: 8191,
    maxOutputTokens: 3072,
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
  }),
  model({
    id: "text-embedding-3-small",
    name: "text-embedding-3-small",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0,
    contextWindow: 8191,
    maxOutputTokens: 1536,
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
  }),
];

export class SumopodAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "sumopod", apiKey, models: MODELS, apiBase: "https://ai.sumopod.com/v1" });
  }
}
