import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "hf:meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    name: "Llama-4-Maverick-17B-128E-Instruct-FP8",
    provider: "synthetic",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.88,
    contextWindow: 524000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:meta-llama/Llama-4-Scout-17B-16E-Instruct",
    name: "Llama-4-Scout-17B-16E-Instruct",
    provider: "synthetic",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 328000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama-3.3-70B-Instruct",
    provider: "synthetic",
    inputPricePer1M: 0.9,
    outputPricePer1M: 0.9,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:meta-llama/Llama-3.1-70B-Instruct",
    name: "Llama-3.1-70B-Instruct",
    provider: "synthetic",
    inputPricePer1M: 0.9,
    outputPricePer1M: 0.9,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:meta-llama/Llama-3.1-405B-Instruct",
    name: "Llama-3.1-405B-Instruct",
    provider: "synthetic",
    inputPricePer1M: 3,
    outputPricePer1M: 3,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:meta-llama/Llama-3.1-8B-Instruct",
    name: "Llama-3.1-8B-Instruct",
    provider: "synthetic",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-R1",
    name: "DeepSeek R1",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-V3-0324",
    name: "DeepSeek V3 (0324)",
    provider: "synthetic",
    inputPricePer1M: 1.2,
    outputPricePer1M: 1.2,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-V3.1-Terminus",
    name: "DeepSeek V3.1 Terminus",
    provider: "synthetic",
    inputPricePer1M: 1.2,
    outputPricePer1M: 1.2,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-R1-0528",
    name: "DeepSeek R1 (0528)",
    provider: "synthetic",
    inputPricePer1M: 3,
    outputPricePer1M: 8,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-V3.1",
    name: "DeepSeek V3.1",
    provider: "synthetic",
    inputPricePer1M: 0.56,
    outputPricePer1M: 1.68,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-V3.2",
    name: "DeepSeek V3.2",
    provider: "synthetic",
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.4,
    contextWindow: 162816,
    maxOutputTokens: 8000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-V3",
    name: "DeepSeek V3",
    provider: "synthetic",
    inputPricePer1M: 1.25,
    outputPricePer1M: 1.25,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:moonshotai/Kimi-K2-Thinking",
    name: "Kimi K2 Thinking",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:moonshotai/Kimi-K2-Instruct-0905",
    name: "Kimi K2 0905",
    provider: "synthetic",
    inputPricePer1M: 1.2,
    outputPricePer1M: 1.2,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "synthetic",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:zai-org/GLM-4.7-Flash",
    name: "GLM-4.7-Flash",
    provider: "synthetic",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.4,
    contextWindow: 196608,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:zai-org/GLM-4.6",
    name: "GLM 4.6",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:zai-org/GLM-5",
    name: "GLM-5",
    provider: "synthetic",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 196608,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:zai-org/GLM-4.7",
    name: "GLM 4.7",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:zai-org/GLM-5.1",
    name: "GLM 5.1",
    provider: "synthetic",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 196608,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:MiniMaxAI/MiniMax-M2.1",
    name: "MiniMax-M2.1",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:MiniMaxAI/MiniMax-M2",
    name: "MiniMax-M2",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 196608,
    maxOutputTokens: 131000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "synthetic",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 191488,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:MiniMaxAI/MiniMax-M3",
    name: "MiniMax-M3",
    provider: "synthetic",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.2,
    contextWindow: 524288,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "synthetic",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:Qwen/Qwen3.5-397B-A17B",
    name: "Qwen3.5-97B-A17B",
    provider: "synthetic",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "hf:Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen3 235B A22B Thinking 2507",
    provider: "synthetic",
    inputPricePer1M: 0.65,
    outputPricePer1M: 3,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:Qwen/Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen 3 Coder 480B",
    provider: "synthetic",
    inputPricePer1M: 2,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:Qwen/Qwen2.5-Coder-32B-Instruct",
    name: "Qwen2.5-Coder-32B-Instruct",
    provider: "synthetic",
    inputPricePer1M: 0.8,
    outputPricePer1M: 0.8,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:Qwen/Qwen3-235B-A22B-Instruct-2507",
    name: "Qwen 3 235B Instruct",
    provider: "synthetic",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:nvidia/Kimi-K2.5-NVFP4",
    name: "Kimi K2.5 (NVFP4)",
    provider: "synthetic",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hf:nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4",
    name: "Nemotron 3 Super 120B",
    provider: "synthetic",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class SyntheticAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "synthetic",
      apiKey,
      models: MODELS,
      apiBase: "https://api.synthetic.new/openai/v1",
    });
  }
}
