import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "minimax-m2.5",
    name: "MiniMax-M2.5",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 204800,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi-K2.5",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "hunyuan-turbos",
    name: "Hunyuan-TurboS",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hunyuan-t1",
    name: "Hunyuan-T1",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "tc-code-latest",
    name: "Auto",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 202752,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hunyuan-2.0-instruct",
    name: "Tencent HY 2.0 Instruct",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "hunyuan-2.0-thinking",
    name: "Tencent HY 2.0 Think",
    provider: "tencent-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class TencentCodingPlanAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "tencent-coding-plan",
      apiKey,
      models: MODELS,
      apiBase: "https://api.lkeap.cloud.tencent.com/coding/v3",
    });
  }
}
