import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "LiquidAI/LFM2-24B-A2B",
    name: "LFM2-24B-A2B",
    provider: "togetherai",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.12,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/Meta-Llama-3-8B-Instruct-Lite",
    name: "Meta Llama 3 8B Instruct Lite",
    provider: "togetherai",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.14,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    name: "Llama 3.3 70B",
    provider: "togetherai",
    inputPricePer1M: 0.88,
    outputPricePer1M: 0.88,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "togetherai",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4.5,
    contextWindow: 262144,
    maxOutputTokens: 131000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    provider: "togetherai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.7-Code",
    name: "Kimi K2.7 Code",
    provider: "togetherai",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-4-31B-it",
    name: "Gemma 4 31B Instruct",
    provider: "togetherai",
    inputPricePer1M: 0.39,
    outputPricePer1M: 0.97,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google/gemma-3n-E4B-it",
    name: "Gemma 3N E4B Instruct",
    provider: "togetherai",
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.12,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.7-Max",
    name: "Qwen3.7 Max",
    provider: "togetherai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 3.75,
    contextWindow: 1000000,
    maxOutputTokens: 500000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "Qwen/Qwen3.6-Plus",
    name: "Qwen3.6 Plus",
    provider: "togetherai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 500000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B",
    name: "Qwen3.5 397B A17B",
    provider: "togetherai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 262144,
    maxOutputTokens: 130000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-Next-FP8",
    name: "Qwen3 Coder Next FP8",
    provider: "togetherai",
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.2,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
    name: "Qwen3 Coder 480B A35B Instruct",
    provider: "togetherai",
    inputPricePer1M: 2,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Instruct-2507-tput",
    name: "Qwen3 235B A22B Instruct 2507 FP8",
    provider: "togetherai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "Qwen/Qwen2.5-7B-Instruct-Turbo",
    name: "Qwen 2.5 7B Instruct Turbo",
    provider: "togetherai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.3,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3.5-9B",
    name: "Qwen3.5 9B",
    provider: "togetherai",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.25,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "togetherai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "togetherai",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.2,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "pearl-ai/gemma-4-31b-it",
    name: "Pearl AI Gemma 4 31B Instruct",
    provider: "togetherai",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.86,
    contextWindow: 32000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b",
    name: "Nemotron 3 Ultra 550B A55B",
    provider: "togetherai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 3.6,
    contextWindow: 512300,
    maxOutputTokens: 512300,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepcogito/cogito-v2-1-671b",
    name: "Cogito v2.1 671B",
    provider: "togetherai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 1.25,
    contextWindow: 163840,
    maxOutputTokens: 163840,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    provider: "togetherai",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1",
    name: "GLM-5.1",
    provider: "togetherai",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-R1",
    name: "DeepSeek-R1",
    provider: "togetherai",
    inputPricePer1M: 3,
    outputPricePer1M: 7,
    contextWindow: 163839,
    maxOutputTokens: 163839,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3-1",
    name: "DeepSeek V3.1",
    provider: "togetherai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.7,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Pro",
    name: "DeepSeek V4 Pro",
    provider: "togetherai",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 512000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3",
    name: "DeepSeek-V3",
    provider: "togetherai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 1.25,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "togetherai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M3",
    name: "MiniMax-M3",
    provider: "togetherai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 524288,
    maxOutputTokens: 250000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.7",
    name: "MiniMax-M2.7",
    provider: "togetherai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "essentialai/Rnj-1-Instruct",
    name: "Rnj-1 Instruct",
    provider: "togetherai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.15,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class TogetheraiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "togetherai", apiKey, models: MODELS });
  }
}
