import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "umans-kimi-k2.7",
    name: "Kimi K2.7 Code",
    provider: "umans-ai-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "umans-glm-5.1",
    name: "GLM 5.1",
    provider: "umans-ai-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "umans-coder",
    name: "Umans Coder",
    provider: "umans-ai-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "umans-flash",
    name: "Umans Flash",
    provider: "umans-ai-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "umans-glm-5.2",
    name: "GLM 5.2",
    provider: "umans-ai-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 405504,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "umans-qwen3.6-35b-a3b",
    name: "Qwen3.6 35B A3B",
    provider: "umans-ai-coding-plan",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class UmansAiCodingPlanAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "umans-ai-coding-plan",
      apiKey,
      models: MODELS,
      apiBase: "https://api.code.umans.ai/v1",
    });
  }
}
