import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "z-ai-glm-5-turbo",
    name: "GLM 5 Turbo",
    provider: "venice",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "grok-4-20-multi-agent",
    name: "Grok 4.20 Multi-Agent",
    provider: "venice",
    inputPricePer1M: 1.42,
    outputPricePer1M: 2.83,
    contextWindow: 2000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "venice",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.35,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google-gemma-4-31b-it",
    name: "Google Gemma 4 31B Instruct",
    provider: "venice",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.36,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2-6",
    name: "Kimi K2.6",
    provider: "venice",
    inputPricePer1M: 0.85,
    outputPricePer1M: 4.655,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    name: "Qwen 3 235B A22B Instruct 2507",
    provider: "venice",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.75,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia-nemotron-cascade-2-30b-a3b",
    name: "Nemotron Cascade 2 30B A3B",
    provider: "venice",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.8,
    contextWindow: 256000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-opus-4-7-fast",
    name: "Claude Opus 4.7 Fast",
    provider: "venice",
    inputPricePer1M: 36,
    outputPricePer1M: 180,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-55-pro",
    name: "GPT-5.5 Pro",
    provider: "venice",
    inputPricePer1M: 37.5,
    outputPricePer1M: 225,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    provider: "venice",
    inputPricePer1M: 0.7,
    outputPricePer1M: 2.8,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "qwen3-5-397b-a17b",
    name: "Qwen 3.5 397B",
    provider: "venice",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    provider: "venice",
    inputPricePer1M: 6,
    outputPricePer1M: 30,
    contextWindow: 198000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org-glm-5",
    name: "GLM 5",
    provider: "venice",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 198000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-5-35b-a3b",
    name: "Qwen 3.5 35B A3B",
    provider: "venice",
    inputPricePer1M: 0.3125,
    outputPricePer1M: 1.25,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "venice-uncensored-role-play",
    name: "Venice Role Play Uncensored",
    provider: "venice",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen-3-6-plus",
    name: "Qwen 3.6 Plus Uncensored",
    provider: "venice",
    inputPricePer1M: 0.625,
    outputPricePer1M: 3.75,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org-glm-4.6",
    name: "GLM 4.6",
    provider: "venice",
    inputPricePer1M: 0.85,
    outputPricePer1M: 2.75,
    contextWindow: 198000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai-gpt-4o-2024-11-20",
    name: "GPT-4o",
    provider: "venice",
    inputPricePer1M: 3.125,
    outputPricePer1M: 12.5,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4-3",
    name: "Grok 4.3",
    provider: "venice",
    inputPricePer1M: 1.42,
    outputPricePer1M: 2.83,
    contextWindow: 1000000,
    maxOutputTokens: 32000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen-3-7-plus",
    name: "Qwen 3.7 Plus",
    provider: "venice",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-m27",
    name: "MiniMax M2.7",
    provider: "venice",
    inputPricePer1M: 0.375,
    outputPricePer1M: 1.5,
    contextWindow: 198000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "kimi-k2-7-code",
    name: "Kimi K2.7 Code",
    provider: "venice",
    inputPricePer1M: 0.9,
    outputPricePer1M: 4.3,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "venice",
    inputPricePer1M: 1.73,
    outputPricePer1M: 3.796,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-235b-a22b-thinking-2507",
    name: "Qwen 3 235B A22B Thinking 2507",
    provider: "venice",
    inputPricePer1M: 0.45,
    outputPricePer1M: 3.5,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "venice",
    inputPricePer1M: 3.75,
    outputPricePer1M: 18.75,
    contextWindow: 198000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-4o-mini-2024-07-18",
    name: "GPT-4o Mini",
    provider: "venice",
    inputPricePer1M: 0.1875,
    outputPricePer1M: 0.75,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "venice",
    inputPricePer1M: 6,
    outputPricePer1M: 30,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-53-codex",
    name: "GPT-5.3 Codex",
    provider: "venice",
    inputPricePer1M: 2.19,
    outputPricePer1M: 17.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-54",
    name: "GPT-5.4",
    provider: "venice",
    inputPricePer1M: 3.13,
    outputPricePer1M: 18.8,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google-gemma-3-27b-it",
    name: "Google Gemma 3 27B Instruct",
    provider: "venice",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.2,
    contextWindow: 198000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax-m3",
    name: "MiniMax M3",
    provider: "venice",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 500000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "claude-opus-4-8-fast",
    name: "Claude Opus 4.8 Fast",
    provider: "venice",
    inputPricePer1M: 12,
    outputPricePer1M: 60,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemma-4-uncensored",
    name: "Gemma 4 Uncensored",
    provider: "venice",
    inputPricePer1M: 0.1625,
    outputPricePer1M: 0.5,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-next-80b",
    name: "Qwen 3 Next 80b",
    provider: "venice",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.9,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mistral-small-2603",
    name: "Mistral Small 4",
    provider: "venice",
    inputPricePer1M: 0.1875,
    outputPricePer1M: 0.75,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "venice",
    inputPricePer1M: 6,
    outputPricePer1M: 30,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org-glm-4.7-flash",
    name: "GLM 4.7 Flash",
    provider: "venice",
    inputPricePer1M: 0.125,
    outputPricePer1M: 0.5,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "google-gemma-4-26b-a4b-it",
    name: "Google Gemma 4 26B A4B Instruct",
    provider: "venice",
    inputPricePer1M: 0.1625,
    outputPricePer1M: 0.5,
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "grok-4-20",
    name: "Grok 4.20",
    provider: "venice",
    inputPricePer1M: 1.42,
    outputPricePer1M: 2.83,
    contextWindow: 2000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "hermes-3-llama-3.1-405b",
    name: "Hermes 3 Llama 3.1 405b",
    provider: "venice",
    inputPricePer1M: 1.1,
    outputPricePer1M: 3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "aion-labs-aion-2-0",
    name: "Aion 2.0",
    provider: "venice",
    inputPricePer1M: 1,
    outputPricePer1M: 2,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen3-vl-235b-a22b",
    name: "Qwen3 VL 235B",
    provider: "venice",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "xiaomi-mimo-v2-5",
    name: "MiMo-V2.5",
    provider: "venice",
    inputPricePer1M: 0.175,
    outputPricePer1M: 0.35,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "venice-uncensored-1-2",
    name: "Venice Uncensored 1.2",
    provider: "venice",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.9,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "gemini-3-5-flash",
    name: "Gemini 3.5 Flash",
    provider: "venice",
    inputPricePer1M: 1.55,
    outputPricePer1M: 9.45,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    provider: "venice",
    inputPricePer1M: 12,
    outputPricePer1M: 60,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-oss-120b",
    name: "OpenAI GPT OSS 120B",
    provider: "venice",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org-glm-5-2",
    name: "GLM 5.2",
    provider: "venice",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia-nemotron-3-nano-30b-a3b",
    name: "NVIDIA Nemotron 3 Nano 30B",
    provider: "venice",
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "venice",
    inputPricePer1M: 6,
    outputPricePer1M: 30,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "mistral-small-3-2-24b-instruct",
    name: "Mistral Small 3.2 24B Instruct",
    provider: "venice",
    inputPricePer1M: 0.09375,
    outputPricePer1M: 0.25,
    contextWindow: 256000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai-gpt-54-pro",
    name: "GPT-5.4 Pro",
    provider: "venice",
    inputPricePer1M: 37.5,
    outputPricePer1M: 225,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "minimax-m3-preview",
    name: "MiniMax M3 Preview",
    provider: "venice",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 524288,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "gemini-3-1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "venice",
    inputPricePer1M: 2.5,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-coder-480b-a35b-instruct-turbo",
    name: "Qwen 3 Coder 480B Turbo",
    provider: "venice",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3-6-27b",
    name: "Qwen 3.6 27B",
    provider: "venice",
    inputPricePer1M: 0.325,
    outputPricePer1M: 3.25,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai-gpt-52-codex",
    name: "GPT-5.2 Codex",
    provider: "venice",
    inputPricePer1M: 2.19,
    outputPricePer1M: 17.5,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "claude-opus-4-6-fast",
    name: "Claude Opus 4.6 Fast",
    provider: "venice",
    inputPricePer1M: 36,
    outputPricePer1M: 180,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen-3-7-max",
    name: "Qwen 3.7 Max",
    provider: "venice",
    inputPricePer1M: 2.7,
    outputPricePer1M: 8.05,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "olafangensan-glm-4.7-flash-heretic",
    name: "GLM 4.7 Flash Heretic",
    provider: "venice",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.8,
    contextWindow: 200000,
    maxOutputTokens: 24000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai-gpt-54-mini",
    name: "GPT-5.4 Mini",
    provider: "venice",
    inputPricePer1M: 0.9375,
    outputPricePer1M: 5.625,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-build-0-1",
    name: "Grok Build 0.1",
    provider: "venice",
    inputPricePer1M: 1,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org-glm-4.7",
    name: "GLM 4.7",
    provider: "venice",
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.65,
    contextWindow: 198000,
    maxOutputTokens: 16384,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "venice",
    inputPricePer1M: 3.6,
    outputPricePer1M: 18,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    provider: "venice",
    inputPricePer1M: 0.7,
    outputPricePer1M: 3.75,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "arcee-trinity-large-thinking",
    name: "Trinity Large Thinking",
    provider: "venice",
    inputPricePer1M: 0.3125,
    outputPricePer1M: 1.125,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai-gpt-55",
    name: "GPT-5.5",
    provider: "venice",
    inputPricePer1M: 6.25,
    outputPricePer1M: 37.5,
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "qwen3-5-9b",
    name: "Qwen 3.5 9B",
    provider: "venice",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.15,
    contextWindow: 256000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "mercury-2",
    name: "Mercury 2",
    provider: "venice",
    inputPricePer1M: 0.3125,
    outputPricePer1M: 0.9375,
    contextWindow: 128000,
    maxOutputTokens: 50000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "zai-org-glm-5-1",
    name: "GLM 5.1",
    provider: "venice",
    inputPricePer1M: 1.75,
    outputPricePer1M: 5.5,
    contextWindow: 200000,
    maxOutputTokens: 24000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "kimi-k2-5",
    name: "Kimi K2.5",
    provider: "venice",
    inputPricePer1M: 0.56,
    outputPricePer1M: 3.5,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "z-ai-glm-5v-turbo",
    name: "GLM 5V Turbo",
    provider: "venice",
    inputPricePer1M: 1.5,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "nvidia-nemotron-3-ultra-550b-a55b",
    name: "NVIDIA Nemotron 3 Ultra",
    provider: "venice",
    inputPricePer1M: 0.625,
    outputPricePer1M: 3.125,
    contextWindow: 256000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai-gpt-52",
    name: "GPT-5.2",
    provider: "venice",
    inputPricePer1M: 2.19,
    outputPricePer1M: 17.5,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "venice",
    inputPricePer1M: 0.33,
    outputPricePer1M: 0.48,
    contextWindow: 160000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "minimax-m25",
    name: "MiniMax M2.5",
    provider: "venice",
    inputPricePer1M: 0.34,
    outputPricePer1M: 1.19,
    contextWindow: 198000,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "llama-3.2-3b",
    name: "Llama 3.2 3B",
    provider: "venice",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class VeniceAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "venice", apiKey, models: MODELS });
  }
}
