import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "moonshotai/Kimi-K2.6",
    name: "Kimi K2.6",
    provider: "vultr",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "nvidia/Llama-3.1-Nemotron-Safety-Guard-8B-v3",
    name: "Llama 3.1 Nemotron Safety Guard",
    provider: "vultr",
    inputPricePer1M: 0.01,
    outputPricePer1M: 0.01,
    contextWindow: 8192,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-BF16",
    name: "NVIDIA Nemotron 3 Nano Omni",
    provider: "vultr",
    inputPricePer1M: 0.13,
    outputPricePer1M: 0.38,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "nvidia/DeepSeek-V3.2-NVFP4",
    name: "DeepSeek V3.2",
    provider: "vultr",
    inputPricePer1M: 0.55,
    outputPricePer1M: 1.65,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "nvidia/Nemotron-Cascade-2-30B-A3B",
    name: "NVIDIA Nemotron Cascade 2",
    provider: "vultr",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1-FP8",
    name: "GLM-5.1",
    provider: "vultr",
    inputPricePer1M: 0.85,
    outputPricePer1M: 3.1,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.7",
    name: "MiniMax-M2.7",
    provider: "vultr",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class VultrAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "vultr", apiKey, models: MODELS, apiBase: "https://api.vultrinference.com/v1" });
  }
}
