import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "wafer.ai",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen3.6-35B-A3B",
    name: "Qwen3.6-35B-A3B",
    provider: "wafer.ai",
    inputPricePer1M: 0.15,
    outputPricePer1M: 1,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7-Max",
    provider: "wafer.ai",
    inputPricePer1M: 5,
    outputPricePer1M: 15,
    contextWindow: 256000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "wafer.ai",
    inputPricePer1M: 1.74,
    outputPricePer1M: 3.48,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen3.5-397B-A17B",
    name: "Qwen3.5-397B-A17B",
    provider: "wafer.ai",
    inputPricePer1M: 0.43,
    outputPricePer1M: 2.6,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Kimi-K2.6",
    name: "Kimi-K2.6",
    provider: "wafer.ai",
    inputPricePer1M: 0.68,
    outputPricePer1M: 3.15,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "GLM-5.1",
    name: "GLM-5.1",
    provider: "wafer.ai",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 202752,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class WaferAiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "wafer.ai", apiKey, models: MODELS, apiBase: "https://pass.wafer.ai/v1" });
  }
}
