import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    name: "Llama 4 Scout 17B 16E Instruct",
    provider: "wandb",
    inputPricePer1M: 0.17,
    outputPricePer1M: 0.66,
    contextWindow: 64000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama-3.3-70B-Instruct",
    provider: "wandb",
    inputPricePer1M: 0.71,
    outputPricePer1M: 0.71,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-3.1-70B-Instruct",
    name: "Llama 3.1 70B",
    provider: "wandb",
    inputPricePer1M: 0.8,
    outputPricePer1M: 0.8,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "meta-llama/Llama-3.1-8B-Instruct",
    name: "Meta-Llama-3.1-8B-Instruct",
    provider: "wandb",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.22,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi K2.5",
    provider: "wandb",
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.85,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "microsoft/Phi-4-mini-instruct",
    name: "Phi-4-mini-instruct",
    provider: "wandb",
    inputPricePer1M: 0.08,
    outputPricePer1M: 0.35,
    contextWindow: 128000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen3-235B-A22B-Thinking-2507",
    provider: "wandb",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen3-Coder-480B-A35B-Instruct",
    provider: "wandb",
    inputPricePer1M: 1,
    outputPricePer1M: 1.5,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Instruct-2507",
    name: "Qwen3 30B A3B Instruct 2507",
    provider: "wandb",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    provider: "wandb",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "gpt-oss-120b",
    provider: "wandb",
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "gpt-oss-20b",
    provider: "wandb",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.2,
    contextWindow: 131072,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8",
    name: "NVIDIA Nemotron 3 Super 120B",
    provider: "wandb",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.8,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "OpenPipe/Qwen3-14B-Instruct",
    name: "OpenPipe Qwen3 14B Instruct",
    provider: "wandb",
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.22,
    contextWindow: 32768,
    maxOutputTokens: 32768,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5-FP8",
    name: "GLM 5",
    provider: "wandb",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 200000,
    maxOutputTokens: 200000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "zai-org/GLM-5.1",
    name: "GLM-5.1",
    provider: "wandb",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek-ai/DeepSeek-V3.1",
    name: "DeepSeek V3.1",
    provider: "wandb",
    inputPricePer1M: 0.55,
    outputPricePer1M: 1.65,
    contextWindow: 161000,
    maxOutputTokens: 161000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax M2.5",
    provider: "wandb",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 196608,
    maxOutputTokens: 196608,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
];

export class WandbAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "wandb", apiKey, models: MODELS, apiBase: "https://api.inference.wandb.ai/v1" });
  }
}
