import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "grok-4.20-multi-agent-0309",
    name: "Grok 4.20 Multi-Agent",
    provider: "xai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: false,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4.20-0309-non-reasoning",
    name: "Grok 4.20 (Non-Reasoning)",
    provider: "xai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-4.3",
    name: "Grok 4.3",
    provider: "xai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-imagine-image-quality",
    name: "Grok Imagine Image Quality",
    provider: "xai",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8000,
    maxOutputTokens: 0,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["image", "pdf"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-imagine-video",
    name: "Grok Imagine Video",
    provider: "xai",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1024,
    maxOutputTokens: 0,
    inputModalities: ["text", "image", "video", "pdf"],
    outputModalities: ["video"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-4.20-0309-reasoning",
    name: "Grok 4.20 (Reasoning)",
    provider: "xai",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "grok-imagine-image",
    name: "Grok Imagine Image",
    provider: "xai",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8000,
    maxOutputTokens: 0,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["image", "pdf"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "grok-build-0.1",
    name: "Grok Build 0.1",
    provider: "xai",
    inputPricePer1M: 1,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class XaiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "xai", apiKey, models: MODELS });
  }
}
