import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "mimo-v2.5-tts",
    name: "MiMo-V2.5-TTS",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo-V2.5-Pro",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2-pro",
    name: "MiMo-V2-Pro",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mimo-v2-tts",
    name: "MiMo-V2-TTS",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2-omni",
    name: "MiMo-V2-Omni",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mimo-v2.5",
    name: "MiMo-V2.5",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2.5-tts-voicedesign",
    name: "MiMo-V2.5-TTS-VoiceDesign",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2.5-tts-voiceclone",
    name: "MiMo-V2.5-TTS-VoiceClone",
    provider: "xiaomi-token-plan-sgp",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 8192,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["audio"],
    reasoning: false,
    toolCall: false,
    structuredOutput: false,
    weights: "open",
  },
];

export class XiaomiTokenPlanSgpAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({
      name: "xiaomi-token-plan-sgp",
      apiKey,
      models: MODELS,
      apiBase: "https://token-plan-sgp.xiaomimimo.com/v1",
    });
  }
}
