import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "mimo-v2.5-pro-ultraspeed",
    name: "MiMo-V2.5-Pro-UltraSpeed",
    provider: "xiaomi",
    inputPricePer1M: 1.305,
    outputPricePer1M: 2.61,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2.5",
    name: "MiMo-V2.5",
    provider: "xiaomi",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2-omni",
    name: "MiMo-V2-Omni",
    provider: "xiaomi",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 262144,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mimo-v2-flash",
    name: "MiMo-V2-Flash",
    provider: "xiaomi",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "mimo-v2-pro",
    name: "MiMo-V2-Pro",
    provider: "xiaomi",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo-V2.5-Pro",
    provider: "xiaomi",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
];

export class XiaomiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "xiaomi", apiKey, models: MODELS, apiBase: "https://api.xiaomimimo.com/v1" });
  }
}
