import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "glm-4.7",
    name: "GLM-4.7",
    provider: "zai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.5v",
    name: "GLM-4.5V",
    provider: "zai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.8,
    contextWindow: 64000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.5",
    name: "GLM-4.5",
    provider: "zai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.7-flashx",
    name: "GLM-4.7-FlashX",
    provider: "zai",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    provider: "zai",
    inputPricePer1M: 1.4,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "glm-4.6",
    name: "GLM-4.6",
    provider: "zai",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.6v",
    name: "GLM-4.6V",
    provider: "zai",
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5v-turbo",
    name: "GLM-5V-Turbo",
    provider: "zai",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "glm-4.5-air",
    name: "GLM-4.5-Air",
    provider: "zai",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.1,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "zai",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-4.5-flash",
    name: "GLM-4.5-Flash",
    provider: "zai",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 131072,
    maxOutputTokens: 98304,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "zai",
    inputPricePer1M: 1,
    outputPricePer1M: 3.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "glm-5-turbo",
    name: "GLM-5-Turbo",
    provider: "zai",
    inputPricePer1M: 1.2,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
];

export class ZaiAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "zai", apiKey, models: MODELS, apiBase: "https://api.z.ai/api/paas/v4" });
  }
}
