import { ModelsDevProviderAdapter } from "./models-dev-provider-adapter";
import type { Model } from "./types";

const MODELS: Model[] = [
  {
    id: "inclusionai/ling-1t",
    name: "Ling-1T",
    provider: "zenmux",
    inputPricePer1M: 0.56,
    outputPricePer1M: 2.24,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "inclusionai/ring-2.6-1t",
    name: "inclusionAI: Ring-2.6-1T",
    provider: "zenmux",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 262000,
    maxOutputTokens: 65000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "inclusionai/ring-1t",
    name: "Ring-1T",
    provider: "zenmux",
    inputPricePer1M: 0.56,
    outputPricePer1M: 2.24,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "moonshotai/kimi-k2.7-code-free",
    name: "Kimi K2.7 Code (Free)",
    provider: "zenmux",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2-thinking-turbo",
    name: "Kimi K2 Thinking Turbo",
    provider: "zenmux",
    inputPricePer1M: 1.15,
    outputPricePer1M: 8,
    contextWindow: 262000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "moonshotai/kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "zenmux",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262144,
    maxOutputTokens: 262144,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "zenmux",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "zenmux",
    inputPricePer1M: 0.58,
    outputPricePer1M: 3.02,
    contextWindow: 262000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    provider: "zenmux",
    inputPricePer1M: 0.95,
    outputPricePer1M: 4,
    contextWindow: 262140,
    maxOutputTokens: 262140,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "moonshotai/kimi-k2-0905",
    name: "Kimi K2 0905",
    provider: "zenmux",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.5,
    contextWindow: 262000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "baidu/ernie-5.0-thinking-preview",
    name: "ERNIE 5.0",
    provider: "zenmux",
    inputPricePer1M: 0.84,
    outputPricePer1M: 3.37,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "zenmux",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "zenmux",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 1048000,
    maxOutputTokens: 64000,
    inputModalities: ["pdf", "image", "text", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "zenmux",
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1048000,
    maxOutputTokens: 64000,
    inputModalities: ["pdf", "image", "text", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    provider: "zenmux",
    inputPricePer1M: 1.5,
    outputPricePer1M: 9,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "video", "audio", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "google/gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    provider: "zenmux",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1048000,
    maxOutputTokens: 64000,
    inputModalities: ["pdf", "image", "text", "audio"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "zenmux",
    inputPricePer1M: 2,
    outputPricePer1M: 12,
    contextWindow: 1048000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    provider: "zenmux",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1048000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf", "audio"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "google/gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    provider: "zenmux",
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.5,
    contextWindow: 1050000,
    maxOutputTokens: 65530,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-code-fast-1",
    name: "Grok Code Fast 1",
    provider: "zenmux",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.5,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-4.3",
    name: "Grok 4.3",
    provider: "zenmux",
    inputPricePer1M: 1.25,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 1000000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "x-ai/grok-4.1-fast-non-reasoning",
    name: "Grok 4.1 Fast Non Reasoning",
    provider: "zenmux",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-4",
    name: "Grok 4",
    provider: "zenmux",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-4-fast",
    name: "Grok 4 Fast",
    provider: "zenmux",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-4.2-fast-non-reasoning",
    name: "Grok 4.2 Fast Non Reasoning",
    provider: "zenmux",
    inputPricePer1M: 3,
    outputPricePer1M: 9,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-4.2-fast",
    name: "Grok 4.2 Fast",
    provider: "zenmux",
    inputPricePer1M: 3,
    outputPricePer1M: 9,
    contextWindow: 2000000,
    maxOutputTokens: 30000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-4.1-fast",
    name: "Grok 4.1 Fast",
    provider: "zenmux",
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.5,
    contextWindow: 2000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "x-ai/grok-build-0.1",
    name: "Grok Build 0.1",
    provider: "zenmux",
    inputPricePer1M: 1,
    outputPricePer1M: 2,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.7",
    name: "GLM 4.7",
    provider: "zenmux",
    inputPricePer1M: 0.28,
    outputPricePer1M: 1.14,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.5",
    name: "GLM 4.5",
    provider: "zenmux",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.54,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.7-flashx",
    name: "GLM 4.7 FlashX",
    provider: "zenmux",
    inputPricePer1M: 0.07,
    outputPricePer1M: 0.42,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-5.1",
    name: "GLM-5.1",
    provider: "zenmux",
    inputPricePer1M: 0.8781,
    outputPricePer1M: 3.5126,
    contextWindow: 200000,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.6",
    name: "GLM 4.6",
    provider: "zenmux",
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.54,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.6v-flash-free",
    name: "GLM 4.6V Flash (Free)",
    provider: "zenmux",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.7-flash-free",
    name: "GLM 4.7 Flash (Free)",
    provider: "zenmux",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.6v",
    name: "GLM 4.6V",
    provider: "zenmux",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.42,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-5v-turbo",
    name: "GLM 5V Turbo",
    provider: "zenmux",
    inputPricePer1M: 0.726,
    outputPricePer1M: 3.1946,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.6v-flash",
    name: "GLM 4.6V FlashX",
    provider: "zenmux",
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.21,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-4.5-air",
    name: "GLM 4.5 Air",
    provider: "zenmux",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.56,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "z-ai/glm-5",
    name: "GLM 5",
    provider: "zenmux",
    inputPricePer1M: 0.58,
    outputPricePer1M: 2.6,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "z-ai/glm-5-turbo",
    name: "GLM 5 Turbo",
    provider: "zenmux",
    inputPricePer1M: 0.88,
    outputPricePer1M: 3.48,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.5-instant",
    name: "GPT-5.5 Instant",
    provider: "zenmux",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2-pro",
    name: "GPT-5.2-Pro",
    provider: "zenmux",
    inputPricePer1M: 21,
    outputPricePer1M: 168,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5",
    name: "GPT-5",
    provider: "zenmux",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-chat",
    name: "GPT-5.1 Chat",
    provider: "zenmux",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["pdf", "image", "text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    provider: "zenmux",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.25,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.3-chat",
    name: "GPT-5.3 Chat",
    provider: "zenmux",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 128000,
    maxOutputTokens: 16380,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-codex",
    name: "GPT-5.1-Codex",
    provider: "zenmux",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2",
    name: "GPT-5.2",
    provider: "zenmux",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "zenmux",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1-codex-mini",
    name: "GPT-5.1-Codex-Mini",
    provider: "zenmux",
    inputPricePer1M: 0.25,
    outputPricePer1M: 2,
    contextWindow: 400000,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4",
    name: "GPT-5.4",
    provider: "zenmux",
    inputPricePer1M: 3.75,
    outputPricePer1M: 18.75,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    provider: "zenmux",
    inputPricePer1M: 0.75,
    outputPricePer1M: 4.5,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.4-pro",
    name: "GPT-5.4 Pro",
    provider: "zenmux",
    inputPricePer1M: 45,
    outputPricePer1M: 225,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.5-pro",
    name: "GPT-5.5 Pro",
    provider: "zenmux",
    inputPricePer1M: 30,
    outputPricePer1M: 180,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "openai/gpt-5-codex",
    name: "GPT-5 Codex",
    provider: "zenmux",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.2-codex",
    name: "GPT-5.2-Codex",
    provider: "zenmux",
    inputPricePer1M: 1.75,
    outputPricePer1M: 14,
    contextWindow: 400000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.1",
    name: "GPT-5.1",
    provider: "zenmux",
    inputPricePer1M: 1.25,
    outputPricePer1M: 10,
    contextWindow: 400000,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "openai/gpt-5.5",
    name: "GPT-5.5",
    provider: "zenmux",
    inputPricePer1M: 5,
    outputPricePer1M: 30,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "closed",
  },
  {
    id: "xiaomi/mimo-v2.5",
    name: "MiMo-V2.5",
    provider: "zenmux",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text", "image", "audio", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "xiaomi/mimo-v2-omni",
    name: "MiMo V2 Omni",
    provider: "zenmux",
    inputPricePer1M: 0.4,
    outputPricePer1M: 2,
    contextWindow: 265000,
    maxOutputTokens: 265000,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xiaomi/mimo-v2-flash",
    name: "MiMo-V2-Flash",
    provider: "zenmux",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 262144,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "xiaomi/mimo-v2-pro",
    name: "MiMo V2 Pro",
    provider: "zenmux",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "xiaomi/mimo-v2.5-pro",
    name: "MiMo-V2.5-Pro",
    provider: "zenmux",
    inputPricePer1M: 1,
    outputPricePer1M: 3,
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "sapiens-ai/agnes-1.5-pro",
    name: "Agnes 1.5 Pro",
    provider: "zenmux",
    inputPricePer1M: 0.16,
    outputPricePer1M: 0.8,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "sapiens-ai/agnes-1.5-lite",
    name: "Agnes 1.5 Lite",
    provider: "zenmux",
    inputPricePer1M: 0.12,
    outputPricePer1M: 0.6,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "volcengine/doubao-seed-2.0-pro",
    name: "Doubao-Seed-2.0-pro",
    provider: "zenmux",
    inputPricePer1M: 0.45,
    outputPricePer1M: 2.24,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "volcengine/doubao-seed-code",
    name: "Doubao-Seed-Code",
    provider: "zenmux",
    inputPricePer1M: 0.17,
    outputPricePer1M: 1.12,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "volcengine/doubao-seed-1.8",
    name: "Doubao-Seed-1.8",
    provider: "zenmux",
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.28,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "volcengine/doubao-seed-2.0-mini",
    name: "Doubao-Seed-2.0-mini",
    provider: "zenmux",
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.28,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "volcengine/doubao-seed-2.0-lite",
    name: "Doubao-Seed-2.0-lite",
    provider: "zenmux",
    inputPricePer1M: 0.09,
    outputPricePer1M: 0.51,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "volcengine/doubao-seed-2.0-code",
    name: "Doubao Seed 2.0 Code",
    provider: "zenmux",
    inputPricePer1M: 0.9,
    outputPricePer1M: 4.48,
    contextWindow: 256000,
    maxOutputTokens: 32000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3.5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "zenmux",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4.5",
    name: "Claude Sonnet 4.5",
    provider: "zenmux",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "zenmux",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "zenmux",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.7",
    name: "Claude Opus 4.7",
    provider: "zenmux",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-3.7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "zenmux",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.8",
    name: "Claude Opus 4.8",
    provider: "zenmux",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-fable-5",
    name: "Claude Fable 5",
    provider: "zenmux",
    inputPricePer1M: 10,
    outputPricePer1M: 50,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.1",
    name: "Claude Opus 4.1",
    provider: "zenmux",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.5",
    name: "Claude Opus 4.5",
    provider: "zenmux",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    inputModalities: ["pdf", "image", "text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-sonnet-4.6",
    name: "Claude Sonnet 4.6",
    provider: "zenmux",
    inputPricePer1M: 3,
    outputPricePer1M: 15,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4",
    name: "Claude Opus 4",
    provider: "zenmux",
    inputPricePer1M: 15,
    outputPricePer1M: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    inputModalities: ["image", "text", "pdf"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "anthropic/claude-opus-4.6",
    name: "Claude Opus 4.6",
    provider: "zenmux",
    inputPricePer1M: 5,
    outputPricePer1M: 25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    inputModalities: ["image", "text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "tencent/hy3-preview",
    name: "Hy3 preview",
    provider: "zenmux",
    inputPricePer1M: 0.172,
    outputPricePer1M: 0.572,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "stepfun/step-3",
    name: "Step-3",
    provider: "zenmux",
    inputPricePer1M: 0.21,
    outputPricePer1M: 0.57,
    contextWindow: 65536,
    maxOutputTokens: 64000,
    inputModalities: ["image", "text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "stepfun/step-3.7-flash",
    name: "Step 3.7 Flash",
    provider: "zenmux",
    inputPricePer1M: 0.2,
    outputPricePer1M: 1.15,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "stepfun/step-3.7-flash-free",
    name: "Step 3.7 Flash (Free)",
    provider: "zenmux",
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextWindow: 256000,
    maxOutputTokens: 256000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "stepfun/step-3.5-flash",
    name: "Step 3.5 Flash",
    provider: "zenmux",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "kuaishou/kat-coder-pro-v2",
    name: "KAT-Coder-Pro-V2",
    provider: "zenmux",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 256000,
    maxOutputTokens: 80000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3-coder-plus",
    name: "Qwen3-Coder-Plus",
    provider: "zenmux",
    inputPricePer1M: 1,
    outputPricePer1M: 5,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3.7-plus",
    name: "Qwen3.7 Plus",
    provider: "zenmux",
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "zenmux",
    inputPricePer1M: 2.5,
    outputPricePer1M: 7.5,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3-max",
    name: "Qwen3-Max-Thinking",
    provider: "zenmux",
    inputPricePer1M: 1.2,
    outputPricePer1M: 6,
    contextWindow: 256000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3.5-flash",
    name: "Qwen3.5 Flash",
    provider: "zenmux",
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1020000,
    maxOutputTokens: 1020000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3.5-plus",
    name: "Qwen3.5 Plus",
    provider: "zenmux",
    inputPricePer1M: 0.8,
    outputPricePer1M: 4.8,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "qwen/qwen3.6-plus",
    name: "Qwen3.6-Plus",
    provider: "zenmux",
    inputPricePer1M: 0.5,
    outputPricePer1M: 3,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "zenmux",
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "zenmux",
    inputPricePer1M: 0.435,
    outputPricePer1M: 0.87,
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: true,
    weights: "open",
  },
  {
    id: "deepseek/deepseek-v3.2-exp",
    name: "DeepSeek-V3.2-Exp",
    provider: "zenmux",
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.33,
    contextWindow: 163000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek/deepseek-chat",
    name: "DeepSeek-V3.2 (Non-thinking Mode)",
    provider: "zenmux",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.42,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: false,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "deepseek/deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "zenmux",
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.43,
    contextWindow: 128000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax/minimax-m2.7-highspeed",
    name: "MiniMax M2.7 highspeed",
    provider: "zenmux",
    inputPricePer1M: 0.611,
    outputPricePer1M: 2.4439,
    contextWindow: 204800,
    maxOutputTokens: 131070,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax/minimax-m2.5",
    name: "MiniMax M2.5",
    provider: "zenmux",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax/minimax-m2.5-lightning",
    name: "MiniMax M2.5 highspeed",
    provider: "zenmux",
    inputPricePer1M: 0.6,
    outputPricePer1M: 4.8,
    contextWindow: 204800,
    maxOutputTokens: 131072,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax/minimax-m2.1",
    name: "MiniMax M2.1",
    provider: "zenmux",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax/minimax-m3",
    name: "MiniMax-M3",
    provider: "zenmux",
    inputPricePer1M: 0.6,
    outputPricePer1M: 2.4,
    contextWindow: 512000,
    maxOutputTokens: 128000,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "open",
  },
  {
    id: "minimax/minimax-m2",
    name: "MiniMax M2",
    provider: "zenmux",
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
    contextWindow: 204000,
    maxOutputTokens: 64000,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
  {
    id: "minimax/minimax-m2.7",
    name: "MiniMax M2.7",
    provider: "zenmux",
    inputPricePer1M: 0.3055,
    outputPricePer1M: 1.2219,
    contextWindow: 204800,
    maxOutputTokens: 131070,
    inputModalities: ["text"],
    outputModalities: ["text"],
    reasoning: true,
    toolCall: true,
    structuredOutput: false,
    weights: "closed",
  },
];

export class ZenmuxAdapter extends ModelsDevProviderAdapter {
  constructor(apiKey: string) {
    super({ name: "zenmux", apiKey, models: MODELS, apiBase: "https://zenmux.ai/api/v1" });
  }
}
